<?php

/**
 * ParEmp filter form base class.
 *
 * @package    gesser
 * @subpackage filter
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseParEmpFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'emp_imp'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'temp_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cfxg_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ccxg_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fact_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'giro_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'girocppnum'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nota_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ped_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ord_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cotc_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cotp_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nde_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cb_num'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'pg_num'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nd_num'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ndcpp_num'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nc_num'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nccpp_num'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'chdv_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'chdvcppnum'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'comp_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'devp_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'devc_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ajus_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'depc_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tras_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'genk_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ords_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ordp_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ejep_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'inte_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'porc_db'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'post_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'postcppnum'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'reten_num'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'retencppnum' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ndr_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ndd_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'movc_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'movb_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desc_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desccppnum'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'num_kit'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fisi_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'docum1'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'docum2'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'temp_char1'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'temp_char2'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'temp_char3'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'temp_char4'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'temp_char5'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'temp_char6'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'temp_char7'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'temp_char8'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'p_comv_vol'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_comv_klu'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_comv_ven'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_comv_con'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_comv_r_c'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_comv_r_p'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_comv_tip'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_desc_art'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_desc_cat'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_desc_glo'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_desc_ofe'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_desc_lin'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_prec_isv'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_prec1_isv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_prec2_isv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_prec3_isv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_prec4_isv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_prec5_isv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_roundfac'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_roundinf'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_val_red'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'p_roundequ'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_roundsup'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_costo_do'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_com_auto'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_stock_neg' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_ent_new'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_aju_comi'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_doble_un'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_pront_pg'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_grab_ren'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para1'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para2'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para3'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para4'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para5'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para6'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para7'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para8'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para9'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para10'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_open_com'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_marg_cap'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_dir_ent'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_art_20'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_imp_kit'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_red_com'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_cyf_dol'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_ser_art'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_art_dol'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'mone_art'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'p_deb_ban'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_deb_aut'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_fact_alm'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_despacho'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_idb'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'val_idb'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tempor1'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fecha_res'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'fecha_fisi'  => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'open_fisi'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'serial'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cadena'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'inv_emp'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'temp_char'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fec_inte'    => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'temp_fech'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'ele_linea'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'lon_linea'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ele_categ'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'lon_categ'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ele_medid'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'lon_medid'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ele_item'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'lon_item'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ele_color'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'lon_color'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ele_carter'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'caracter'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dec_prec'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dec_cost'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cant_art'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'total_cod'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tipo_com'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipo_lib'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_us_in'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_in'    => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_mo'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_mo'    => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'logo'        => new sfWidgetFormFilterInput(),
      'revisado'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'trasnfe'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'p_sucursal'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'rowguid'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'p_licores'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_lotenro'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_lotefec'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'serverolap'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dataolap'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'p_loteaut'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipo_inve'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aju_posm'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aju_posa'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aju_negm'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aju_nega'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aju_posmc'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aju_posac'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aju_negmc'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aju_negac'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'plv_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'plc_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'pventa'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'turnosic'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tabislr'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'moneda'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'imp_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rma_cli'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rma_prov'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rma_entc'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rma_entp'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rma_regs'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'p_prov_new'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_ser_new'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'rmacliente'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rma_trans'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'garantia'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'reem_prov'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'des_ser'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ser_auto'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'pcontrol_1'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_2'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_3'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_4'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_5'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'idioma'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serie'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'aux01'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aux02'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'eprofit'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pais'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'emp_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dmc_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tax_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ced_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ent_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'artinmp'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tip_costo'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tip_cmat'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_aent'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cie_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'odp_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'req_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dev_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_asal'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'devmax'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'exp_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'inp_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cost_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'par_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'esc_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cierre_mes'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pla_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'men_num'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tipcosdev'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'max_lin'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dist_num'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'exp_numi'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'p_imp65'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'val_max'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'server'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'namedb'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'login'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'password'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'man_impr'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
    ));

    $this->setValidators(array(
      'emp_imp'     => new sfValidatorPass(array('required' => false)),
      'temp_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cfxg_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ccxg_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'giro_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'girocppnum'  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nota_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ped_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ord_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cotc_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cotp_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cb_num'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pg_num'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_num'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ndcpp_num'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_num'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nccpp_num'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'chdv_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'chdvcppnum'  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'comp_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'devp_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'devc_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ajus_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'depc_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tras_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'genk_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ords_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ordp_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ejep_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'inte_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'porc_db'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'post_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'postcppnum'  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'reten_num'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'retencppnum' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ndr_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ndd_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'movc_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'movb_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'desc_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'desccppnum'  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'num_kit'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fisi_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'docum1'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'docum2'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'temp_char1'  => new sfValidatorPass(array('required' => false)),
      'temp_char2'  => new sfValidatorPass(array('required' => false)),
      'temp_char3'  => new sfValidatorPass(array('required' => false)),
      'temp_char4'  => new sfValidatorPass(array('required' => false)),
      'temp_char5'  => new sfValidatorPass(array('required' => false)),
      'temp_char6'  => new sfValidatorPass(array('required' => false)),
      'temp_char7'  => new sfValidatorPass(array('required' => false)),
      'temp_char8'  => new sfValidatorPass(array('required' => false)),
      'p_comv_vol'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_comv_klu'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_comv_ven'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_comv_con'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_comv_r_c'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_comv_r_p'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_comv_tip'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_desc_art'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_desc_cat'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_desc_glo'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_desc_ofe'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_desc_lin'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_prec_isv'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_prec1_isv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_prec2_isv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_prec3_isv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_prec4_isv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_prec5_isv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_roundfac'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_roundinf'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_val_red'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'p_roundequ'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_roundsup'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_costo_do'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_com_auto'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_stock_neg' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_ent_new'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_aju_comi'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_doble_un'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_pront_pg'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_grab_ren'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para1'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para2'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para3'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para4'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para5'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para6'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para7'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para8'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para9'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para10'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_open_com'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_marg_cap'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_dir_ent'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_art_20'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_imp_kit'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_red_com'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_cyf_dol'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_ser_art'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_art_dol'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'mone_art'    => new sfValidatorPass(array('required' => false)),
      'p_deb_ban'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_deb_aut'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_fact_alm'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_despacho'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_idb'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'val_idb'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tempor1'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fecha_res'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'fecha_fisi'  => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'open_fisi'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'serial'      => new sfValidatorPass(array('required' => false)),
      'cadena'      => new sfValidatorPass(array('required' => false)),
      'inv_emp'     => new sfValidatorPass(array('required' => false)),
      'temp_char'   => new sfValidatorPass(array('required' => false)),
      'fec_inte'    => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'temp_fech'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'ele_linea'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'lon_linea'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ele_categ'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'lon_categ'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ele_medid'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'lon_medid'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ele_item'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'lon_item'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ele_color'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'lon_color'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ele_carter'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'caracter'    => new sfValidatorPass(array('required' => false)),
      'dec_prec'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dec_cost'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cant_art'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'total_cod'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tipo_com'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipo_lib'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_us_in'    => new sfValidatorPass(array('required' => false)),
      'fe_us_in'    => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_mo'    => new sfValidatorPass(array('required' => false)),
      'fe_us_mo'    => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'logo'        => new sfValidatorPass(array('required' => false)),
      'revisado'    => new sfValidatorPass(array('required' => false)),
      'trasnfe'     => new sfValidatorPass(array('required' => false)),
      'p_sucursal'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'rowguid'     => new sfValidatorPass(array('required' => false)),
      'p_licores'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_lotenro'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_lotefec'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'serverolap'  => new sfValidatorPass(array('required' => false)),
      'dataolap'    => new sfValidatorPass(array('required' => false)),
      'p_loteaut'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipo_inve'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'aju_posm'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_posa'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_negm'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_nega'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_posmc'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_posac'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_negmc'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_negac'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'plv_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'plc_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pventa'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'turnosic'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tabislr'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'moneda'      => new sfValidatorPass(array('required' => false)),
      'imp_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rma_cli'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rma_prov'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rma_entc'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rma_entp'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rma_regs'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'p_prov_new'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_ser_new'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'rmacliente'  => new sfValidatorPass(array('required' => false)),
      'rma_trans'   => new sfValidatorPass(array('required' => false)),
      'garantia'    => new sfValidatorPass(array('required' => false)),
      'reem_prov'   => new sfValidatorPass(array('required' => false)),
      'des_ser'     => new sfValidatorPass(array('required' => false)),
      'ser_auto'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'pcontrol_1'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_2'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_3'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_4'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_5'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'idioma'      => new sfValidatorPass(array('required' => false)),
      'serie'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'aux01'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'aux02'       => new sfValidatorPass(array('required' => false)),
      'eprofit'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pais'        => new sfValidatorPass(array('required' => false)),
      'emp_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dmc_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tax_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ced_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ent_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'artinmp'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tip_costo'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tip_cmat'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'co_aent'     => new sfValidatorPass(array('required' => false)),
      'cie_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'odp_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'req_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dev_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'co_asal'     => new sfValidatorPass(array('required' => false)),
      'devmax'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'exp_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'inp_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cost_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'par_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'esc_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cierre_mes'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pla_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'men_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tipcosdev'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'max_lin'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dist_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'exp_numi'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'p_imp65'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'val_max'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'server'      => new sfValidatorPass(array('required' => false)),
      'namedb'      => new sfValidatorPass(array('required' => false)),
      'login'       => new sfValidatorPass(array('required' => false)),
      'password'    => new sfValidatorPass(array('required' => false)),
      'man_impr'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
    ));

    $this->widgetSchema->setNameFormat('par_emp_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'ParEmp';
  }

  public function getFields()
  {
    return array(
      'cod_emp'     => 'Text',
      'emp_imp'     => 'Text',
      'temp_num'    => 'Number',
      'cfxg_num'    => 'Number',
      'ccxg_num'    => 'Number',
      'fact_num'    => 'Number',
      'giro_num'    => 'Number',
      'girocppnum'  => 'Number',
      'nota_num'    => 'Number',
      'ped_num'     => 'Number',
      'ord_num'     => 'Number',
      'cotc_num'    => 'Number',
      'cotp_num'    => 'Number',
      'nde_num'     => 'Number',
      'cb_num'      => 'Number',
      'pg_num'      => 'Number',
      'nd_num'      => 'Number',
      'ndcpp_num'   => 'Number',
      'nc_num'      => 'Number',
      'nccpp_num'   => 'Number',
      'chdv_num'    => 'Number',
      'chdvcppnum'  => 'Number',
      'comp_num'    => 'Number',
      'devp_num'    => 'Number',
      'devc_num'    => 'Number',
      'ajus_num'    => 'Number',
      'depc_num'    => 'Number',
      'tras_num'    => 'Number',
      'genk_num'    => 'Number',
      'ords_num'    => 'Number',
      'ordp_num'    => 'Number',
      'ejep_num'    => 'Number',
      'inte_num'    => 'Number',
      'porc_db'     => 'Number',
      'post_num'    => 'Number',
      'postcppnum'  => 'Number',
      'reten_num'   => 'Number',
      'retencppnum' => 'Number',
      'ndr_num'     => 'Number',
      'ndd_num'     => 'Number',
      'movc_num'    => 'Number',
      'movb_num'    => 'Number',
      'desc_num'    => 'Number',
      'desccppnum'  => 'Number',
      'num_kit'     => 'Number',
      'fisi_num'    => 'Number',
      'docum1'      => 'Number',
      'docum2'      => 'Number',
      'temp_char1'  => 'Text',
      'temp_char2'  => 'Text',
      'temp_char3'  => 'Text',
      'temp_char4'  => 'Text',
      'temp_char5'  => 'Text',
      'temp_char6'  => 'Text',
      'temp_char7'  => 'Text',
      'temp_char8'  => 'Text',
      'p_comv_vol'  => 'Boolean',
      'p_comv_klu'  => 'Boolean',
      'p_comv_ven'  => 'Boolean',
      'p_comv_con'  => 'Boolean',
      'p_comv_r_c'  => 'Boolean',
      'p_comv_r_p'  => 'Boolean',
      'p_comv_tip'  => 'Boolean',
      'p_desc_art'  => 'Boolean',
      'p_desc_cat'  => 'Boolean',
      'p_desc_glo'  => 'Boolean',
      'p_desc_ofe'  => 'Boolean',
      'p_desc_lin'  => 'Boolean',
      'p_prec_isv'  => 'Boolean',
      'p_prec1_isv' => 'Boolean',
      'p_prec2_isv' => 'Boolean',
      'p_prec3_isv' => 'Boolean',
      'p_prec4_isv' => 'Boolean',
      'p_prec5_isv' => 'Boolean',
      'p_roundfac'  => 'Boolean',
      'p_roundinf'  => 'Boolean',
      'p_val_red'   => 'Number',
      'p_roundequ'  => 'Boolean',
      'p_roundsup'  => 'Boolean',
      'p_costo_do'  => 'Boolean',
      'p_com_auto'  => 'Boolean',
      'p_stock_neg' => 'Boolean',
      'p_ent_new'   => 'Boolean',
      'p_aju_comi'  => 'Boolean',
      'p_doble_un'  => 'Boolean',
      'p_pront_pg'  => 'Boolean',
      'p_grab_ren'  => 'Boolean',
      'p_para1'     => 'Boolean',
      'p_para2'     => 'Boolean',
      'p_para3'     => 'Boolean',
      'p_para4'     => 'Boolean',
      'p_para5'     => 'Boolean',
      'p_para6'     => 'Boolean',
      'p_para7'     => 'Boolean',
      'p_para8'     => 'Boolean',
      'p_para9'     => 'Boolean',
      'p_para10'    => 'Boolean',
      'p_open_com'  => 'Boolean',
      'p_marg_cap'  => 'Boolean',
      'p_dir_ent'   => 'Boolean',
      'p_art_20'    => 'Boolean',
      'p_imp_kit'   => 'Boolean',
      'p_red_com'   => 'Boolean',
      'p_cyf_dol'   => 'Boolean',
      'p_ser_art'   => 'Boolean',
      'p_art_dol'   => 'Boolean',
      'mone_art'    => 'Text',
      'p_deb_ban'   => 'Boolean',
      'p_deb_aut'   => 'Boolean',
      'p_fact_alm'  => 'Boolean',
      'p_despacho'  => 'Boolean',
      'p_idb'       => 'Boolean',
      'val_idb'     => 'Number',
      'tempor1'     => 'Number',
      'fecha_res'   => 'Date',
      'fecha_fisi'  => 'Date',
      'open_fisi'   => 'Boolean',
      'serial'      => 'Text',
      'cadena'      => 'Text',
      'inv_emp'     => 'Text',
      'temp_char'   => 'Text',
      'fec_inte'    => 'Date',
      'temp_fech'   => 'Date',
      'ele_linea'   => 'Boolean',
      'lon_linea'   => 'Number',
      'ele_categ'   => 'Boolean',
      'lon_categ'   => 'Number',
      'ele_medid'   => 'Boolean',
      'lon_medid'   => 'Number',
      'ele_item'    => 'Boolean',
      'lon_item'    => 'Number',
      'ele_color'   => 'Boolean',
      'lon_color'   => 'Number',
      'ele_carter'  => 'Boolean',
      'caracter'    => 'Text',
      'dec_prec'    => 'Number',
      'dec_cost'    => 'Number',
      'cant_art'    => 'Number',
      'total_cod'   => 'Number',
      'tipo_com'    => 'Boolean',
      'tipo_lib'    => 'Boolean',
      'co_us_in'    => 'Text',
      'fe_us_in'    => 'Date',
      'co_us_mo'    => 'Text',
      'fe_us_mo'    => 'Date',
      'logo'        => 'Text',
      'revisado'    => 'Text',
      'trasnfe'     => 'Text',
      'p_sucursal'  => 'Boolean',
      'rowguid'     => 'Text',
      'p_licores'   => 'Boolean',
      'p_lotenro'   => 'Boolean',
      'p_lotefec'   => 'Boolean',
      'serverolap'  => 'Text',
      'dataolap'    => 'Text',
      'p_loteaut'   => 'Boolean',
      'tipo_inve'   => 'Number',
      'aju_posm'    => 'Number',
      'aju_posa'    => 'Number',
      'aju_negm'    => 'Number',
      'aju_nega'    => 'Number',
      'aju_posmc'   => 'Number',
      'aju_posac'   => 'Number',
      'aju_negmc'   => 'Number',
      'aju_negac'   => 'Number',
      'plv_num'     => 'Number',
      'plc_num'     => 'Number',
      'pventa'      => 'Number',
      'turnosic'    => 'Number',
      'tabislr'     => 'Number',
      'moneda'      => 'Text',
      'imp_num'     => 'Number',
      'rma_cli'     => 'Number',
      'rma_prov'    => 'Number',
      'rma_entc'    => 'Number',
      'rma_entp'    => 'Number',
      'rma_regs'    => 'Number',
      'p_prov_new'  => 'Boolean',
      'p_ser_new'   => 'Boolean',
      'rmacliente'  => 'Text',
      'rma_trans'   => 'Text',
      'garantia'    => 'Text',
      'reem_prov'   => 'Text',
      'des_ser'     => 'Text',
      'ser_auto'    => 'Number',
      'pcontrol_1'  => 'Boolean',
      'pcontrol_2'  => 'Boolean',
      'pcontrol_3'  => 'Boolean',
      'pcontrol_4'  => 'Boolean',
      'pcontrol_5'  => 'Boolean',
      'idioma'      => 'Text',
      'serie'       => 'Boolean',
      'aux01'       => 'Number',
      'aux02'       => 'Text',
      'eprofit'     => 'Boolean',
      'pais'        => 'Text',
      'emp_num'     => 'Number',
      'dmc_num'     => 'Number',
      'tax_num'     => 'Number',
      'ced_num'     => 'Number',
      'ent_num'     => 'Number',
      'artinmp'     => 'Boolean',
      'tip_costo'   => 'Number',
      'tip_cmat'    => 'Number',
      'co_aent'     => 'Text',
      'cie_num'     => 'Number',
      'odp_num'     => 'Number',
      'req_num'     => 'Number',
      'dev_num'     => 'Number',
      'co_asal'     => 'Text',
      'devmax'      => 'Boolean',
      'exp_num'     => 'Number',
      'inp_num'     => 'Number',
      'cost_num'    => 'Number',
      'par_num'     => 'Number',
      'esc_num'     => 'Number',
      'cierre_mes'  => 'Boolean',
      'pla_num'     => 'Number',
      'men_num'     => 'Number',
      'tipcosdev'   => 'Number',
      'max_lin'     => 'Number',
      'dist_num'    => 'Number',
      'exp_numi'    => 'Number',
      'p_imp65'     => 'Boolean',
      'val_max'     => 'Boolean',
      'server'      => 'Text',
      'namedb'      => 'Text',
      'login'       => 'Text',
      'password'    => 'Text',
      'man_impr'    => 'Boolean',
    );
  }
}
