<?php

/**
 * NotDep filter form base class.
 *
 * @package    gesser
 * @subpackage filter
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseNotDepFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'contrib'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'nombre'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rif'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nit'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'status'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'comentario' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'descrip'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'saldo'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fec_emis'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'fec_venc'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_cli'     => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Clientes'), 'add_empty' => true)),
      'co_ven'     => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Vendedor'), 'add_empty' => true)),
      'co_tran'    => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Transpor'), 'add_empty' => true)),
      'dir_ent'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'forma_pag'  => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Condicio'), 'add_empty' => true)),
      'tot_bruto'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tot_neto'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'glob_desc'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tot_reca'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'porc_gdesc' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'porc_reca'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'total_uc'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'total_cp'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tot_flete'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'monto_dev'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'totklu'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'anulada'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'impresa'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'iva'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'iva_dev'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'feccom'     => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'numcom'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tasa'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'moneda'     => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Moneda'), 'add_empty' => true)),
      'cta_contab' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'seriales'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tasag'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tasag10'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tasag20'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo1'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo2'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo3'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo4'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo5'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo6'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo7'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo8'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_us_in'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_in'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_mo'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_mo'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_el'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_el'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'revisado'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'trasnfe'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_sucu'    => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Almacen'), 'add_empty' => true)),
      'rowguid'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'mon_ilc'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'otros1'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'otros2'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'otros3'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aux01'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aux02'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'salestax'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'origen'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'origen_d'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'telefono'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'sta_prod'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
    ));

    $this->setValidators(array(
      'contrib'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'nombre'     => new sfValidatorPass(array('required' => false)),
      'rif'        => new sfValidatorPass(array('required' => false)),
      'nit'        => new sfValidatorPass(array('required' => false)),
      'status'     => new sfValidatorPass(array('required' => false)),
      'comentario' => new sfValidatorPass(array('required' => false)),
      'descrip'    => new sfValidatorPass(array('required' => false)),
      'saldo'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'fec_emis'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'fec_venc'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_cli'     => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Clientes'), 'column' => 'co_cli')),
      'co_ven'     => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Vendedor'), 'column' => 'co_ven')),
      'co_tran'    => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Transpor'), 'column' => 'co_tran')),
      'dir_ent'    => new sfValidatorPass(array('required' => false)),
      'forma_pag'  => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Condicio'), 'column' => 'co_cond')),
      'tot_bruto'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tot_neto'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'glob_desc'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tot_reca'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'porc_gdesc' => new sfValidatorPass(array('required' => false)),
      'porc_reca'  => new sfValidatorPass(array('required' => false)),
      'total_uc'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'total_cp'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tot_flete'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_dev'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'totklu'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'anulada'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'impresa'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'iva'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'iva_dev'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'feccom'     => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'numcom'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tasa'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'moneda'     => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Moneda'), 'column' => 'co_mone')),
      'cta_contab' => new sfValidatorPass(array('required' => false)),
      'seriales'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tasag'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tasag10'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tasag20'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'campo1'     => new sfValidatorPass(array('required' => false)),
      'campo2'     => new sfValidatorPass(array('required' => false)),
      'campo3'     => new sfValidatorPass(array('required' => false)),
      'campo4'     => new sfValidatorPass(array('required' => false)),
      'campo5'     => new sfValidatorPass(array('required' => false)),
      'campo6'     => new sfValidatorPass(array('required' => false)),
      'campo7'     => new sfValidatorPass(array('required' => false)),
      'campo8'     => new sfValidatorPass(array('required' => false)),
      'co_us_in'   => new sfValidatorPass(array('required' => false)),
      'fe_us_in'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_mo'   => new sfValidatorPass(array('required' => false)),
      'fe_us_mo'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_el'   => new sfValidatorPass(array('required' => false)),
      'fe_us_el'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'revisado'   => new sfValidatorPass(array('required' => false)),
      'trasnfe'    => new sfValidatorPass(array('required' => false)),
      'co_sucu'    => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Almacen'), 'column' => 'co_alma')),
      'rowguid'    => new sfValidatorPass(array('required' => false)),
      'mon_ilc'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'otros1'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'otros2'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'otros3'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'aux01'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'aux02'      => new sfValidatorPass(array('required' => false)),
      'salestax'   => new sfValidatorPass(array('required' => false)),
      'origen'     => new sfValidatorPass(array('required' => false)),
      'origen_d'   => new sfValidatorPass(array('required' => false)),
      'telefono'   => new sfValidatorPass(array('required' => false)),
      'sta_prod'   => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('not_dep_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'NotDep';
  }

  public function getFields()
  {
    return array(
      'fact_num'   => 'Number',
      'contrib'    => 'Boolean',
      'nombre'     => 'Text',
      'rif'        => 'Text',
      'nit'        => 'Text',
      'status'     => 'Text',
      'comentario' => 'Text',
      'descrip'    => 'Text',
      'saldo'      => 'Number',
      'fec_emis'   => 'Date',
      'fec_venc'   => 'Date',
      'co_cli'     => 'ForeignKey',
      'co_ven'     => 'ForeignKey',
      'co_tran'    => 'ForeignKey',
      'dir_ent'    => 'Text',
      'forma_pag'  => 'ForeignKey',
      'tot_bruto'  => 'Number',
      'tot_neto'   => 'Number',
      'glob_desc'  => 'Number',
      'tot_reca'   => 'Number',
      'porc_gdesc' => 'Text',
      'porc_reca'  => 'Text',
      'total_uc'   => 'Number',
      'total_cp'   => 'Number',
      'tot_flete'  => 'Number',
      'monto_dev'  => 'Number',
      'totklu'     => 'Number',
      'anulada'    => 'Boolean',
      'impresa'    => 'Boolean',
      'iva'        => 'Number',
      'iva_dev'    => 'Number',
      'feccom'     => 'Date',
      'numcom'     => 'Number',
      'tasa'       => 'Number',
      'moneda'     => 'ForeignKey',
      'cta_contab' => 'Text',
      'seriales'   => 'Number',
      'tasag'      => 'Number',
      'tasag10'    => 'Number',
      'tasag20'    => 'Number',
      'campo1'     => 'Text',
      'campo2'     => 'Text',
      'campo3'     => 'Text',
      'campo4'     => 'Text',
      'campo5'     => 'Text',
      'campo6'     => 'Text',
      'campo7'     => 'Text',
      'campo8'     => 'Text',
      'co_us_in'   => 'Text',
      'fe_us_in'   => 'Date',
      'co_us_mo'   => 'Text',
      'fe_us_mo'   => 'Date',
      'co_us_el'   => 'Text',
      'fe_us_el'   => 'Date',
      'revisado'   => 'Text',
      'trasnfe'    => 'Text',
      'co_sucu'    => 'ForeignKey',
      'rowguid'    => 'Text',
      'mon_ilc'    => 'Number',
      'otros1'     => 'Number',
      'otros2'     => 'Number',
      'otros3'     => 'Number',
      'aux01'      => 'Number',
      'aux02'      => 'Text',
      'salestax'   => 'Text',
      'origen'     => 'Text',
      'origen_d'   => 'Text',
      'telefono'   => 'Text',
      'sta_prod'   => 'Text',
    );
  }
}
