<?php

/**
 * RmaAmb filter form base class.
 *
 * @package    gesser
 * @subpackage filter
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseRmaAmbFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'amb_usua'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'amb_rma'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rma_num'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'nro_ent_pr' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'fec_emis'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vco_cli'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dco_cli'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_cli'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'rma_prov'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vco_tran'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dco_tran'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_tran'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'descrip'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vmoneda'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dmoneda'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'moneda'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vreng_1'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dreng_1'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reng_1'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vreng_2'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dreng_2'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reng_2'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vreng_3'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dreng_3'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reng_3'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_art'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_importar' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_seriales' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_anular'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_procesar' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_reversar' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_clien'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tamcol01'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol02'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol03'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol04'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol05'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol06'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol07'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol08'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol09'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol10'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol11'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol12'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol13'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol14'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol15'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol16'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol17'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol18'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol19'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol20'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol21'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol22'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol01'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol02'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol03'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol04'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol05'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol06'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol07'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol08'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol09'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol10'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol11'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol12'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol13'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol14'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol15'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol16'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol17'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol18'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol19'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol20'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol21'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol22'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'pseriales'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pnvo_prov'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'camb_doc'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'sin_docu'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'gar_venc'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'ser_nulo'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'saldo'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'fvenc'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'chdev'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'camb_art'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'entc_art'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'listar'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'num_listar' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'numcopia'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo1'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo2'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo3'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo4'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo5'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo6'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo7'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo8'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_us_in'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_in'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_mo'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_mo'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_el'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_el'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'revisado'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'trasnfe'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_sucu'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rowguid'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
    ));

    $this->setValidators(array(
      'amb_usua'   => new sfValidatorPass(array('required' => false)),
      'amb_rma'    => new sfValidatorPass(array('required' => false)),
      'rma_num'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'nro_ent_pr' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'fec_emis'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vco_cli'    => new sfValidatorPass(array('required' => false)),
      'dco_cli'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_cli'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'rma_prov'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vco_tran'   => new sfValidatorPass(array('required' => false)),
      'dco_tran'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_tran'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'descrip'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vmoneda'    => new sfValidatorPass(array('required' => false)),
      'dmoneda'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'moneda'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vreng_1'    => new sfValidatorPass(array('required' => false)),
      'dreng_1'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reng_1'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vreng_2'    => new sfValidatorPass(array('required' => false)),
      'dreng_2'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reng_2'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vreng_3'    => new sfValidatorPass(array('required' => false)),
      'dreng_3'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reng_3'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_art'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_importar' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_seriales' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_anular'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_procesar' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_reversar' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_clien'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tamcol01'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol02'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol03'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol04'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol05'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol06'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol07'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol08'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol09'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol10'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol11'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol12'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol13'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol14'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol15'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol16'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol17'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol18'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol19'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol20'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol21'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol22'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol01'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol02'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol03'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol04'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol05'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol06'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol07'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol08'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol09'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol10'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol11'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol12'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol13'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol14'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol15'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol16'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol17'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol18'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol19'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol20'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol21'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol22'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pseriales'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pnvo_prov'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'camb_doc'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'sin_docu'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'gar_venc'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'ser_nulo'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'saldo'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'fvenc'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'chdev'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'camb_art'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'entc_art'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'listar'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'num_listar' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'numcopia'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'campo1'     => new sfValidatorPass(array('required' => false)),
      'campo2'     => new sfValidatorPass(array('required' => false)),
      'campo3'     => new sfValidatorPass(array('required' => false)),
      'campo4'     => new sfValidatorPass(array('required' => false)),
      'campo5'     => new sfValidatorPass(array('required' => false)),
      'campo6'     => new sfValidatorPass(array('required' => false)),
      'campo7'     => new sfValidatorPass(array('required' => false)),
      'campo8'     => new sfValidatorPass(array('required' => false)),
      'co_us_in'   => new sfValidatorPass(array('required' => false)),
      'fe_us_in'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_mo'   => new sfValidatorPass(array('required' => false)),
      'fe_us_mo'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_el'   => new sfValidatorPass(array('required' => false)),
      'fe_us_el'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'revisado'   => new sfValidatorPass(array('required' => false)),
      'trasnfe'    => new sfValidatorPass(array('required' => false)),
      'co_sucu'    => new sfValidatorPass(array('required' => false)),
      'rowguid'    => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('rma_amb_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'RmaAmb';
  }

  public function getFields()
  {
    return array(
      'id'         => 'Number',
      'amb_usua'   => 'Text',
      'amb_rma'    => 'Text',
      'rma_num'    => 'Boolean',
      'nro_ent_pr' => 'Boolean',
      'fec_emis'   => 'Boolean',
      'vco_cli'    => 'Text',
      'dco_cli'    => 'Boolean',
      'co_cli'     => 'Boolean',
      'rma_prov'   => 'Boolean',
      'vco_tran'   => 'Text',
      'dco_tran'   => 'Boolean',
      'co_tran'    => 'Boolean',
      'descrip'    => 'Boolean',
      'vmoneda'    => 'Text',
      'dmoneda'    => 'Boolean',
      'moneda'     => 'Boolean',
      'vreng_1'    => 'Text',
      'dreng_1'    => 'Boolean',
      'reng_1'     => 'Boolean',
      'vreng_2'    => 'Text',
      'dreng_2'    => 'Boolean',
      'reng_2'     => 'Boolean',
      'vreng_3'    => 'Text',
      'dreng_3'    => 'Boolean',
      'reng_3'     => 'Boolean',
      'b_art'      => 'Boolean',
      'b_importar' => 'Boolean',
      'b_seriales' => 'Boolean',
      'b_anular'   => 'Boolean',
      'b_procesar' => 'Boolean',
      'b_reversar' => 'Boolean',
      'b_clien'    => 'Boolean',
      'tamcol01'   => 'Number',
      'tamcol02'   => 'Number',
      'tamcol03'   => 'Number',
      'tamcol04'   => 'Number',
      'tamcol05'   => 'Number',
      'tamcol06'   => 'Number',
      'tamcol07'   => 'Number',
      'tamcol08'   => 'Number',
      'tamcol09'   => 'Number',
      'tamcol10'   => 'Number',
      'tamcol11'   => 'Number',
      'tamcol12'   => 'Number',
      'tamcol13'   => 'Number',
      'tamcol14'   => 'Number',
      'tamcol15'   => 'Number',
      'tamcol16'   => 'Number',
      'tamcol17'   => 'Number',
      'tamcol18'   => 'Number',
      'tamcol19'   => 'Number',
      'tamcol20'   => 'Number',
      'tamcol21'   => 'Number',
      'tamcol22'   => 'Number',
      'poscol01'   => 'Number',
      'poscol02'   => 'Number',
      'poscol03'   => 'Number',
      'poscol04'   => 'Number',
      'poscol05'   => 'Number',
      'poscol06'   => 'Number',
      'poscol07'   => 'Number',
      'poscol08'   => 'Number',
      'poscol09'   => 'Number',
      'poscol10'   => 'Number',
      'poscol11'   => 'Number',
      'poscol12'   => 'Number',
      'poscol13'   => 'Number',
      'poscol14'   => 'Number',
      'poscol15'   => 'Number',
      'poscol16'   => 'Number',
      'poscol17'   => 'Number',
      'poscol18'   => 'Number',
      'poscol19'   => 'Number',
      'poscol20'   => 'Number',
      'poscol21'   => 'Number',
      'poscol22'   => 'Number',
      'pseriales'  => 'Boolean',
      'pnvo_prov'  => 'Boolean',
      'camb_doc'   => 'Boolean',
      'sin_docu'   => 'Boolean',
      'gar_venc'   => 'Boolean',
      'ser_nulo'   => 'Boolean',
      'saldo'      => 'Boolean',
      'fvenc'      => 'Boolean',
      'chdev'      => 'Boolean',
      'camb_art'   => 'Boolean',
      'entc_art'   => 'Boolean',
      'listar'     => 'Number',
      'num_listar' => 'Number',
      'numcopia'   => 'Number',
      'campo1'     => 'Text',
      'campo2'     => 'Text',
      'campo3'     => 'Text',
      'campo4'     => 'Text',
      'campo5'     => 'Text',
      'campo6'     => 'Text',
      'campo7'     => 'Text',
      'campo8'     => 'Text',
      'co_us_in'   => 'Text',
      'fe_us_in'   => 'Date',
      'co_us_mo'   => 'Text',
      'fe_us_mo'   => 'Date',
      'co_us_el'   => 'Text',
      'fe_us_el'   => 'Date',
      'revisado'   => 'Text',
      'trasnfe'    => 'Text',
      'co_sucu'    => 'Text',
      'rowguid'    => 'Text',
    );
  }
}
