<?php

/**
 * Ambclpro filter form base class.
 *
 * @package    gesser
 * @subpackage filter
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseAmbclproFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'co_cliv'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipod'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipov'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipo'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cli_desv'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'direc1v'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'direc2v'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'telefonosv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'faxv'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'inactivov'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'comentariv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'responsv'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'fecha_regv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'saldov'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'mont_crev'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'plaz_pagv'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'descppagov' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'con_zond'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_zonv'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_zon'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_segd'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_segv'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_seg'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'con_vend'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_venv'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_ven'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desc_globv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'horarcajav' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'frecuvistv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'lunesv'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'martesv'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'miercolesv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'juevesv'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'viernesv'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'sabadov'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'domingov'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'dir_ent2v'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'rifv'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'contribuv'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'dis_cenv'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'nitv'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'emailv'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_ingrd'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_ingrv'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_ingr'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tipo_perd'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipo_perv'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipo_per'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_tabv'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipo_adid'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipo_adiv'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipo_adi'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'matrizd'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'matrizv'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'matriz'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo1'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo2'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo3'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo4'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo5'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo6'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo7'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo8'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_us_in'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_in'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_mo'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_mo'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_el'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_el'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'revisado'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'trasnfe'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_sucu'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serialp'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'valido'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'rowguid'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'loginv'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'passwordv'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'estadov'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vpasswordv' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_paisv'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_paisd'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_pais'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'zipv'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'ciudadv'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'taxidv'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'formtypev'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'formtyped'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'formtype'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'websitev'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bwebsitev'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bemailv'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'salestaxv'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'salestaxd'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'salestax'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
    ));

    $this->setValidators(array(
      'co_cliv'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipod'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipov'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipo'       => new sfValidatorPass(array('required' => false)),
      'cli_desv'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'direc1v'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'direc2v'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'telefonosv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'faxv'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'inactivov'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'comentariv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'responsv'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'fecha_regv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'saldov'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'mont_crev'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'plaz_pagv'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'descppagov' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'con_zond'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_zonv'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_zon'     => new sfValidatorPass(array('required' => false)),
      'co_segd'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_segv'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_seg'     => new sfValidatorPass(array('required' => false)),
      'con_vend'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_venv'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_ven'     => new sfValidatorPass(array('required' => false)),
      'desc_globv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'horarcajav' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'frecuvistv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'lunesv'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'martesv'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'miercolesv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'juevesv'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'viernesv'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'sabadov'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'domingov'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'dir_ent2v'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'rifv'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'contribuv'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'dis_cenv'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'nitv'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'emailv'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_ingrd'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_ingrv'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_ingr'    => new sfValidatorPass(array('required' => false)),
      'tipo_perd'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipo_perv'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipo_per'   => new sfValidatorPass(array('required' => false)),
      'co_tabv'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipo_adid'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipo_adiv'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipo_adi'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'matrizd'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'matrizv'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'matriz'     => new sfValidatorPass(array('required' => false)),
      'campo1'     => new sfValidatorPass(array('required' => false)),
      'campo2'     => new sfValidatorPass(array('required' => false)),
      'campo3'     => new sfValidatorPass(array('required' => false)),
      'campo4'     => new sfValidatorPass(array('required' => false)),
      'campo5'     => new sfValidatorPass(array('required' => false)),
      'campo6'     => new sfValidatorPass(array('required' => false)),
      'campo7'     => new sfValidatorPass(array('required' => false)),
      'campo8'     => new sfValidatorPass(array('required' => false)),
      'co_us_in'   => new sfValidatorPass(array('required' => false)),
      'fe_us_in'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_mo'   => new sfValidatorPass(array('required' => false)),
      'fe_us_mo'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_el'   => new sfValidatorPass(array('required' => false)),
      'fe_us_el'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'revisado'   => new sfValidatorPass(array('required' => false)),
      'trasnfe'    => new sfValidatorPass(array('required' => false)),
      'co_sucu'    => new sfValidatorPass(array('required' => false)),
      'serialp'    => new sfValidatorPass(array('required' => false)),
      'valido'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'rowguid'    => new sfValidatorPass(array('required' => false)),
      'loginv'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'passwordv'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'estadov'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vpasswordv' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_paisv'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_paisd'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_pais'    => new sfValidatorPass(array('required' => false)),
      'zipv'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'ciudadv'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'taxidv'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'formtypev'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'formtyped'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'formtype'   => new sfValidatorPass(array('required' => false)),
      'websitev'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bwebsitev'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bemailv'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'salestaxv'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'salestaxd'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'salestax'   => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('ambclpro_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Ambclpro';
  }

  public function getFields()
  {
    return array(
      'amb_usua'   => 'Text',
      'tipo_cyp'   => 'Text',
      'co_cliv'    => 'Boolean',
      'tipod'      => 'Boolean',
      'tipov'      => 'Boolean',
      'tipo'       => 'Text',
      'cli_desv'   => 'Boolean',
      'direc1v'    => 'Boolean',
      'direc2v'    => 'Boolean',
      'telefonosv' => 'Boolean',
      'faxv'       => 'Boolean',
      'inactivov'  => 'Boolean',
      'comentariv' => 'Boolean',
      'responsv'   => 'Boolean',
      'fecha_regv' => 'Boolean',
      'saldov'     => 'Boolean',
      'mont_crev'  => 'Boolean',
      'plaz_pagv'  => 'Boolean',
      'descppagov' => 'Boolean',
      'con_zond'   => 'Boolean',
      'co_zonv'    => 'Boolean',
      'co_zon'     => 'Text',
      'co_segd'    => 'Boolean',
      'co_segv'    => 'Boolean',
      'co_seg'     => 'Text',
      'con_vend'   => 'Boolean',
      'co_venv'    => 'Boolean',
      'co_ven'     => 'Text',
      'desc_globv' => 'Boolean',
      'horarcajav' => 'Boolean',
      'frecuvistv' => 'Boolean',
      'lunesv'     => 'Boolean',
      'martesv'    => 'Boolean',
      'miercolesv' => 'Boolean',
      'juevesv'    => 'Boolean',
      'viernesv'   => 'Boolean',
      'sabadov'    => 'Boolean',
      'domingov'   => 'Boolean',
      'dir_ent2v'  => 'Boolean',
      'rifv'       => 'Boolean',
      'contribuv'  => 'Boolean',
      'dis_cenv'   => 'Boolean',
      'nitv'       => 'Boolean',
      'emailv'     => 'Boolean',
      'co_ingrd'   => 'Boolean',
      'co_ingrv'   => 'Boolean',
      'co_ingr'    => 'Text',
      'tipo_perd'  => 'Boolean',
      'tipo_perv'  => 'Boolean',
      'tipo_per'   => 'Text',
      'co_tabv'    => 'Boolean',
      'tipo_adid'  => 'Boolean',
      'tipo_adiv'  => 'Boolean',
      'tipo_adi'   => 'Number',
      'matrizd'    => 'Boolean',
      'matrizv'    => 'Boolean',
      'matriz'     => 'Text',
      'campo1'     => 'Text',
      'campo2'     => 'Text',
      'campo3'     => 'Text',
      'campo4'     => 'Text',
      'campo5'     => 'Text',
      'campo6'     => 'Text',
      'campo7'     => 'Text',
      'campo8'     => 'Text',
      'co_us_in'   => 'Text',
      'fe_us_in'   => 'Date',
      'co_us_mo'   => 'Text',
      'fe_us_mo'   => 'Date',
      'co_us_el'   => 'Text',
      'fe_us_el'   => 'Date',
      'revisado'   => 'Text',
      'trasnfe'    => 'Text',
      'co_sucu'    => 'Text',
      'serialp'    => 'Text',
      'valido'     => 'Boolean',
      'rowguid'    => 'Text',
      'loginv'     => 'Boolean',
      'passwordv'  => 'Boolean',
      'estadov'    => 'Boolean',
      'vpasswordv' => 'Boolean',
      'co_paisv'   => 'Boolean',
      'co_paisd'   => 'Boolean',
      'co_pais'    => 'Text',
      'zipv'       => 'Boolean',
      'ciudadv'    => 'Boolean',
      'taxidv'     => 'Boolean',
      'formtypev'  => 'Boolean',
      'formtyped'  => 'Boolean',
      'formtype'   => 'Text',
      'websitev'   => 'Boolean',
      'bwebsitev'  => 'Boolean',
      'bemailv'    => 'Boolean',
      'salestaxv'  => 'Boolean',
      'salestaxd'  => 'Boolean',
      'salestax'   => 'Text',
    );
  }
}
