<?php

/**
 * Amblcobr filter form base class.
 *
 * @package    gesser
 * @subpackage filter
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseAmblcobrFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'cob_num'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'recibo'        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vco_cli'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dco_cli'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_cli'        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vco_ven'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dco_ven'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_ven'        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'fec_con'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'monto_abo'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'dxpp'          => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reten'         => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vtipo_cob'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dtipo_cob'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipo_cob'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'num_doc'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vtarjeta'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dtarjeta'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tarjeta'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vcuenta'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dcuenta'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'cuenta'        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vbanco'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dbanco'        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'banco'         => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'fec_cheque'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vcaja'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dcaja'         => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'caja'          => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'monto_total'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bt_actualizar' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bt_cancelar'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bt_cheque'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bt_pago'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bt_reverso'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bt_despacho'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bt_facturas'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bt_caja'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bt_camb'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tasa'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dmoneda'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'moneda'        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vmoneda'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'p_abrir_ca'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_detal'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'campo1'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo2'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo3'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo4'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo5'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo6'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo7'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo8'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_us_in'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_in'      => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_mo'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_mo'      => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_el'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_el'      => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'revisado'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'trasnfe'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'p_para1'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para2'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para3'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para4'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para5'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_sucu'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rowguid'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'edppago'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bt_reactiva'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'bt_anulado'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'des_crip'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'max_per'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'permodret'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
    ));

    $this->setValidators(array(
      'cob_num'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'recibo'        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vco_cli'       => new sfValidatorPass(array('required' => false)),
      'dco_cli'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_cli'        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vco_ven'       => new sfValidatorPass(array('required' => false)),
      'dco_ven'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_ven'        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'fec_con'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'monto_abo'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'dxpp'          => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reten'         => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vtipo_cob'     => new sfValidatorPass(array('required' => false)),
      'dtipo_cob'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipo_cob'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'num_doc'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vtarjeta'      => new sfValidatorPass(array('required' => false)),
      'dtarjeta'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tarjeta'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vcuenta'       => new sfValidatorPass(array('required' => false)),
      'dcuenta'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'cuenta'        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vbanco'        => new sfValidatorPass(array('required' => false)),
      'dbanco'        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'banco'         => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'fec_cheque'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vcaja'         => new sfValidatorPass(array('required' => false)),
      'dcaja'         => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'caja'          => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'monto_total'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bt_actualizar' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bt_cancelar'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bt_cheque'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bt_pago'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bt_reverso'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bt_despacho'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bt_facturas'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bt_caja'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bt_camb'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tasa'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'dmoneda'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'moneda'        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vmoneda'       => new sfValidatorPass(array('required' => false)),
      'p_abrir_ca'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_detal'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'campo1'        => new sfValidatorPass(array('required' => false)),
      'campo2'        => new sfValidatorPass(array('required' => false)),
      'campo3'        => new sfValidatorPass(array('required' => false)),
      'campo4'        => new sfValidatorPass(array('required' => false)),
      'campo5'        => new sfValidatorPass(array('required' => false)),
      'campo6'        => new sfValidatorPass(array('required' => false)),
      'campo7'        => new sfValidatorPass(array('required' => false)),
      'campo8'        => new sfValidatorPass(array('required' => false)),
      'co_us_in'      => new sfValidatorPass(array('required' => false)),
      'fe_us_in'      => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_mo'      => new sfValidatorPass(array('required' => false)),
      'fe_us_mo'      => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_el'      => new sfValidatorPass(array('required' => false)),
      'fe_us_el'      => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'revisado'      => new sfValidatorPass(array('required' => false)),
      'trasnfe'       => new sfValidatorPass(array('required' => false)),
      'p_para1'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para2'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para3'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para4'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para5'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_sucu'       => new sfValidatorPass(array('required' => false)),
      'rowguid'       => new sfValidatorPass(array('required' => false)),
      'edppago'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bt_reactiva'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'bt_anulado'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'des_crip'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'max_per'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'permodret'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
    ));

    $this->widgetSchema->setNameFormat('amblcobr_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Amblcobr';
  }

  public function getFields()
  {
    return array(
      'ambusu'        => 'Text',
      'amb_blco'      => 'Text',
      'cob_num'       => 'Boolean',
      'recibo'        => 'Boolean',
      'vco_cli'       => 'Text',
      'dco_cli'       => 'Boolean',
      'co_cli'        => 'Boolean',
      'vco_ven'       => 'Text',
      'dco_ven'       => 'Boolean',
      'co_ven'        => 'Boolean',
      'fec_con'       => 'Boolean',
      'monto_abo'     => 'Boolean',
      'dxpp'          => 'Boolean',
      'reten'         => 'Boolean',
      'vtipo_cob'     => 'Text',
      'dtipo_cob'     => 'Boolean',
      'tipo_cob'      => 'Boolean',
      'num_doc'       => 'Boolean',
      'vtarjeta'      => 'Text',
      'dtarjeta'      => 'Boolean',
      'tarjeta'       => 'Boolean',
      'vcuenta'       => 'Text',
      'dcuenta'       => 'Boolean',
      'cuenta'        => 'Boolean',
      'vbanco'        => 'Text',
      'dbanco'        => 'Boolean',
      'banco'         => 'Boolean',
      'fec_cheque'    => 'Boolean',
      'vcaja'         => 'Text',
      'dcaja'         => 'Boolean',
      'caja'          => 'Boolean',
      'monto_total'   => 'Boolean',
      'bt_actualizar' => 'Boolean',
      'bt_cancelar'   => 'Boolean',
      'bt_cheque'     => 'Boolean',
      'bt_pago'       => 'Boolean',
      'bt_reverso'    => 'Boolean',
      'bt_despacho'   => 'Boolean',
      'bt_facturas'   => 'Boolean',
      'bt_caja'       => 'Boolean',
      'bt_camb'       => 'Boolean',
      'tasa'          => 'Number',
      'dmoneda'       => 'Boolean',
      'moneda'        => 'Boolean',
      'vmoneda'       => 'Text',
      'p_abrir_ca'    => 'Boolean',
      'p_detal'       => 'Boolean',
      'campo1'        => 'Text',
      'campo2'        => 'Text',
      'campo3'        => 'Text',
      'campo4'        => 'Text',
      'campo5'        => 'Text',
      'campo6'        => 'Text',
      'campo7'        => 'Text',
      'campo8'        => 'Text',
      'co_us_in'      => 'Text',
      'fe_us_in'      => 'Date',
      'co_us_mo'      => 'Text',
      'fe_us_mo'      => 'Date',
      'co_us_el'      => 'Text',
      'fe_us_el'      => 'Date',
      'revisado'      => 'Text',
      'trasnfe'       => 'Text',
      'p_para1'       => 'Boolean',
      'p_para2'       => 'Boolean',
      'p_para3'       => 'Boolean',
      'p_para4'       => 'Boolean',
      'p_para5'       => 'Boolean',
      'co_sucu'       => 'Text',
      'rowguid'       => 'Text',
      'edppago'       => 'Boolean',
      'bt_reactiva'   => 'Boolean',
      'bt_anulado'    => 'Boolean',
      'des_crip'      => 'Boolean',
      'max_per'       => 'Number',
      'permodret'     => 'Boolean',
    );
  }
}
