<?php

/**
 * Amblfact filter form base class.
 *
 * @package    gesser
 * @subpackage filter
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseAmblfactFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'fact_num'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'contrib'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'descrip'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'fec_emis'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'fec_venc'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vco_cli'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dco_cli'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_cli'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vco_ven'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dco_ven'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_ven'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vco_tran'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dco_tran'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_tran'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vforma_pag'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dforma_pag'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'forma_pag'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vmoneda'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dmoneda'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'moneda'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'monto_adi'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'com_relac'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'porc_gdesc'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'porc_reca'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tot_flete'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'stock_neg'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'cobrar_aut'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'num_listar'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'listar'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'pstock_neg'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pc1'          => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pc2'          => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pc3'          => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pc4'          => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pc5'          => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'saldo'        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'fvenc'        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'chdev'        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'numcopia'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'vreng_4'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dreng_4'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vsucursal'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'vreng_3'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dreng_3'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reng_3'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reng_4'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reng_5'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reng_6'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reng_7'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reng_8'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reng_9'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'reng_10'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_cobrar'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_importar'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_anular'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_seriales'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_notas'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_margen'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_margen'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'b_clien'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_fact'       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tamcol01'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol02'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol03'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol04'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol05'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol06'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol07'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol08'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol09'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol10'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol11'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol12'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol13'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol14'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol15'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol16'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol17'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol18'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol19'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tamcol20'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol01'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol02'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol03'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol04'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol05'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol06'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol07'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol08'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol09'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol10'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol11'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol12'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol13'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol14'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol15'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol16'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol17'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol18'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol19'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'poscol20'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo1'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo2'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo3'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo4'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo5'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo6'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo7'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo8'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_us_in'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_in'     => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_mo'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_mo'     => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_el'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_el'     => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'revisado'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'trasnfe'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'p_para1'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para2'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para3'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para4'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para5'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para6'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para7'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para8'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para9'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_para10'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'co_sucu'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rowguid'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'b_reactivar'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_dev_reng'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_art'        => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_devdinero'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'b_revdinero'  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'p_lotefec'    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_1'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_2'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_3'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_4'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_5'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'serie'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'pcontrol_6'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_7'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_8'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pcontrol_9'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tax'          => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'vtax'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dtax'         => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'numcontrol'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'serial_lleno' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'pimpfac'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'actforma'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'formapag'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'man_impr'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
    ));

    $this->setValidators(array(
      'fact_num'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'contrib'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'descrip'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'fec_emis'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'fec_venc'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vco_cli'      => new sfValidatorPass(array('required' => false)),
      'dco_cli'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_cli'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vco_ven'      => new sfValidatorPass(array('required' => false)),
      'dco_ven'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_ven'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vco_tran'     => new sfValidatorPass(array('required' => false)),
      'dco_tran'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_tran'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vforma_pag'   => new sfValidatorPass(array('required' => false)),
      'dforma_pag'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'forma_pag'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vmoneda'      => new sfValidatorPass(array('required' => false)),
      'dmoneda'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'moneda'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'monto_adi'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'com_relac'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'porc_gdesc'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'porc_reca'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tot_flete'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'stock_neg'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'cobrar_aut'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'num_listar'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'listar'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pstock_neg'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pc1'          => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pc2'          => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pc3'          => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pc4'          => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pc5'          => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'saldo'        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'fvenc'        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'chdev'        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'numcopia'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'vreng_4'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'dreng_4'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vsucursal'    => new sfValidatorPass(array('required' => false)),
      'vreng_3'      => new sfValidatorPass(array('required' => false)),
      'dreng_3'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reng_3'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reng_4'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reng_5'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reng_6'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reng_7'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reng_8'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reng_9'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'reng_10'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_cobrar'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_importar'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_anular'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_seriales'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_notas'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_margen'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_margen'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'b_clien'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_fact'       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tamcol01'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol02'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol03'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol04'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol05'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol06'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol07'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol08'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol09'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol10'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol11'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol12'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol13'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol14'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol15'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol16'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol17'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol18'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol19'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tamcol20'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol01'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol02'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol03'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol04'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol05'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol06'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol07'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol08'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol09'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol10'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol11'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol12'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol13'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol14'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol15'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol16'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol17'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol18'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol19'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'poscol20'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'campo1'       => new sfValidatorPass(array('required' => false)),
      'campo2'       => new sfValidatorPass(array('required' => false)),
      'campo3'       => new sfValidatorPass(array('required' => false)),
      'campo4'       => new sfValidatorPass(array('required' => false)),
      'campo5'       => new sfValidatorPass(array('required' => false)),
      'campo6'       => new sfValidatorPass(array('required' => false)),
      'campo7'       => new sfValidatorPass(array('required' => false)),
      'campo8'       => new sfValidatorPass(array('required' => false)),
      'co_us_in'     => new sfValidatorPass(array('required' => false)),
      'fe_us_in'     => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_mo'     => new sfValidatorPass(array('required' => false)),
      'fe_us_mo'     => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_el'     => new sfValidatorPass(array('required' => false)),
      'fe_us_el'     => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'revisado'     => new sfValidatorPass(array('required' => false)),
      'trasnfe'      => new sfValidatorPass(array('required' => false)),
      'p_para1'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para2'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para3'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para4'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para5'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para6'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para7'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para8'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para9'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_para10'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'co_sucu'      => new sfValidatorPass(array('required' => false)),
      'rowguid'      => new sfValidatorPass(array('required' => false)),
      'b_reactivar'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_dev_reng'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_art'        => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_devdinero'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'b_revdinero'  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'p_lotefec'    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_1'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_2'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_3'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_4'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_5'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'serie'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pcontrol_6'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_7'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_8'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pcontrol_9'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tax'          => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'vtax'         => new sfValidatorPass(array('required' => false)),
      'dtax'         => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'numcontrol'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'serial_lleno' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'pimpfac'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'actforma'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'formapag'     => new sfValidatorPass(array('required' => false)),
      'man_impr'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
    ));

    $this->widgetSchema->setNameFormat('amblfact_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Amblfact';
  }

  public function getFields()
  {
    return array(
      'amb_usua'     => 'Text',
      'amb_blfa'     => 'Text',
      'fact_num'     => 'Boolean',
      'contrib'      => 'Boolean',
      'descrip'      => 'Boolean',
      'fec_emis'     => 'Boolean',
      'fec_venc'     => 'Boolean',
      'vco_cli'      => 'Text',
      'dco_cli'      => 'Boolean',
      'co_cli'       => 'Boolean',
      'vco_ven'      => 'Text',
      'dco_ven'      => 'Boolean',
      'co_ven'       => 'Boolean',
      'vco_tran'     => 'Text',
      'dco_tran'     => 'Boolean',
      'co_tran'      => 'Boolean',
      'vforma_pag'   => 'Text',
      'dforma_pag'   => 'Boolean',
      'forma_pag'    => 'Boolean',
      'vmoneda'      => 'Text',
      'dmoneda'      => 'Boolean',
      'moneda'       => 'Boolean',
      'monto_adi'    => 'Boolean',
      'com_relac'    => 'Boolean',
      'porc_gdesc'   => 'Boolean',
      'porc_reca'    => 'Boolean',
      'tot_flete'    => 'Boolean',
      'stock_neg'    => 'Boolean',
      'cobrar_aut'   => 'Boolean',
      'num_listar'   => 'Number',
      'listar'       => 'Number',
      'pstock_neg'   => 'Boolean',
      'pc1'          => 'Boolean',
      'pc2'          => 'Boolean',
      'pc3'          => 'Boolean',
      'pc4'          => 'Boolean',
      'pc5'          => 'Boolean',
      'saldo'        => 'Boolean',
      'fvenc'        => 'Boolean',
      'chdev'        => 'Boolean',
      'numcopia'     => 'Number',
      'vreng_4'      => 'Number',
      'dreng_4'      => 'Boolean',
      'vsucursal'    => 'Text',
      'vreng_3'      => 'Text',
      'dreng_3'      => 'Boolean',
      'reng_3'       => 'Boolean',
      'reng_4'       => 'Boolean',
      'reng_5'       => 'Boolean',
      'reng_6'       => 'Boolean',
      'reng_7'       => 'Boolean',
      'reng_8'       => 'Boolean',
      'reng_9'       => 'Boolean',
      'reng_10'      => 'Boolean',
      'b_cobrar'     => 'Boolean',
      'b_importar'   => 'Boolean',
      'b_anular'     => 'Boolean',
      'b_seriales'   => 'Boolean',
      'b_notas'      => 'Boolean',
      'b_margen'     => 'Boolean',
      'p_margen'     => 'Number',
      'b_clien'      => 'Boolean',
      'b_fact'       => 'Boolean',
      'tamcol01'     => 'Number',
      'tamcol02'     => 'Number',
      'tamcol03'     => 'Number',
      'tamcol04'     => 'Number',
      'tamcol05'     => 'Number',
      'tamcol06'     => 'Number',
      'tamcol07'     => 'Number',
      'tamcol08'     => 'Number',
      'tamcol09'     => 'Number',
      'tamcol10'     => 'Number',
      'tamcol11'     => 'Number',
      'tamcol12'     => 'Number',
      'tamcol13'     => 'Number',
      'tamcol14'     => 'Number',
      'tamcol15'     => 'Number',
      'tamcol16'     => 'Number',
      'tamcol17'     => 'Number',
      'tamcol18'     => 'Number',
      'tamcol19'     => 'Number',
      'tamcol20'     => 'Number',
      'poscol01'     => 'Number',
      'poscol02'     => 'Number',
      'poscol03'     => 'Number',
      'poscol04'     => 'Number',
      'poscol05'     => 'Number',
      'poscol06'     => 'Number',
      'poscol07'     => 'Number',
      'poscol08'     => 'Number',
      'poscol09'     => 'Number',
      'poscol10'     => 'Number',
      'poscol11'     => 'Number',
      'poscol12'     => 'Number',
      'poscol13'     => 'Number',
      'poscol14'     => 'Number',
      'poscol15'     => 'Number',
      'poscol16'     => 'Number',
      'poscol17'     => 'Number',
      'poscol18'     => 'Number',
      'poscol19'     => 'Number',
      'poscol20'     => 'Number',
      'campo1'       => 'Text',
      'campo2'       => 'Text',
      'campo3'       => 'Text',
      'campo4'       => 'Text',
      'campo5'       => 'Text',
      'campo6'       => 'Text',
      'campo7'       => 'Text',
      'campo8'       => 'Text',
      'co_us_in'     => 'Text',
      'fe_us_in'     => 'Date',
      'co_us_mo'     => 'Text',
      'fe_us_mo'     => 'Date',
      'co_us_el'     => 'Text',
      'fe_us_el'     => 'Date',
      'revisado'     => 'Text',
      'trasnfe'      => 'Text',
      'p_para1'      => 'Boolean',
      'p_para2'      => 'Boolean',
      'p_para3'      => 'Boolean',
      'p_para4'      => 'Boolean',
      'p_para5'      => 'Boolean',
      'p_para6'      => 'Boolean',
      'p_para7'      => 'Boolean',
      'p_para8'      => 'Boolean',
      'p_para9'      => 'Boolean',
      'p_para10'     => 'Boolean',
      'co_sucu'      => 'Text',
      'rowguid'      => 'Text',
      'b_reactivar'  => 'Boolean',
      'p_dev_reng'   => 'Boolean',
      'b_art'        => 'Boolean',
      'b_devdinero'  => 'Boolean',
      'b_revdinero'  => 'Boolean',
      'p_lotefec'    => 'Boolean',
      'pcontrol_1'   => 'Boolean',
      'pcontrol_2'   => 'Boolean',
      'pcontrol_3'   => 'Boolean',
      'pcontrol_4'   => 'Boolean',
      'pcontrol_5'   => 'Boolean',
      'serie'        => 'Number',
      'pcontrol_6'   => 'Boolean',
      'pcontrol_7'   => 'Boolean',
      'pcontrol_8'   => 'Boolean',
      'pcontrol_9'   => 'Boolean',
      'tax'          => 'Boolean',
      'vtax'         => 'Text',
      'dtax'         => 'Boolean',
      'numcontrol'   => 'Boolean',
      'serial_lleno' => 'Boolean',
      'pimpfac'      => 'Boolean',
      'actforma'     => 'Boolean',
      'formapag'     => 'Text',
      'man_impr'     => 'Boolean',
    );
  }
}
