<?php

/**
 * DocumCc filter form base class.
 *
 * @package    gesser
 * @subpackage filter
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseDocumCcFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'anulado'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'movi'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aut'         => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'num_control' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_cli'      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Clientes'), 'add_empty' => true)),
      'contrib'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'fec_emis'    => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'fec_venc'    => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'observa'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'doc_orig'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nro_orig'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_ban'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nro_che'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_ven'      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Vendedor'), 'add_empty' => true)),
      'tipo'        => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Tabulado'), 'add_empty' => true)),
      'tasa'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'moneda'      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Moneda'), 'add_empty' => true)),
      'monto_imp'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'monto_gen'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'monto_a1'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'monto_a2'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'monto_bru'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'descuentos'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'monto_des'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'recargo'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'monto_rec'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'monto_otr'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'monto_net'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'saldo'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'feccom'      => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'numcom'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dis_cen'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'comis1'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'comis2'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'comis3'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'comis4'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'adicional'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo1'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo2'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo3'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo4'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo5'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo6'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo7'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'campo8'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_us_in'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_in'    => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_mo'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_mo'    => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'co_us_el'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fe_us_el'    => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'revisado'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'trasnfe'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'numcon'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'co_sucu'     => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Almacen'), 'add_empty' => true)),
      'rowguid'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'mon_ilc'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'otros1'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'otros2'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'otros3'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'reng_si'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'comis5'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'comis6'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'row_id'      => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'aux01'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aux02'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'salestax'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'origen'      => new sfWidgetFormFilterInput(),
      'origen_d'    => new sfWidgetFormFilterInput(),
      'fec_reg'     => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'prov_ter'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'reng_ter'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ven_ter'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'impfis'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'impfisfac'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
    ));

    $this->setValidators(array(
      'anulado'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'movi'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aut'         => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'num_control' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'co_cli'      => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Clientes'), 'column' => 'co_cli')),
      'contrib'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'fec_emis'    => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'fec_venc'    => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'observa'     => new sfValidatorPass(array('required' => false)),
      'doc_orig'    => new sfValidatorPass(array('required' => false)),
      'nro_orig'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'co_ban'      => new sfValidatorPass(array('required' => false)),
      'nro_che'     => new sfValidatorPass(array('required' => false)),
      'co_ven'      => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Vendedor'), 'column' => 'co_ven')),
      'tipo'        => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Tabulado'), 'column' => 'tipo')),
      'tasa'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'moneda'      => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Moneda'), 'column' => 'co_mone')),
      'monto_imp'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_gen'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_a1'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_a2'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_bru'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'descuentos'  => new sfValidatorPass(array('required' => false)),
      'monto_des'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'recargo'     => new sfValidatorPass(array('required' => false)),
      'monto_rec'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_otr'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_net'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'saldo'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'feccom'      => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'numcom'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dis_cen'     => new sfValidatorPass(array('required' => false)),
      'comis1'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comis2'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comis3'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comis4'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'adicional'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'campo1'      => new sfValidatorPass(array('required' => false)),
      'campo2'      => new sfValidatorPass(array('required' => false)),
      'campo3'      => new sfValidatorPass(array('required' => false)),
      'campo4'      => new sfValidatorPass(array('required' => false)),
      'campo5'      => new sfValidatorPass(array('required' => false)),
      'campo6'      => new sfValidatorPass(array('required' => false)),
      'campo7'      => new sfValidatorPass(array('required' => false)),
      'campo8'      => new sfValidatorPass(array('required' => false)),
      'co_us_in'    => new sfValidatorPass(array('required' => false)),
      'fe_us_in'    => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_mo'    => new sfValidatorPass(array('required' => false)),
      'fe_us_mo'    => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'co_us_el'    => new sfValidatorPass(array('required' => false)),
      'fe_us_el'    => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'revisado'    => new sfValidatorPass(array('required' => false)),
      'trasnfe'     => new sfValidatorPass(array('required' => false)),
      'numcon'      => new sfValidatorPass(array('required' => false)),
      'co_sucu'     => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Almacen'), 'column' => 'co_alma')),
      'rowguid'     => new sfValidatorPass(array('required' => false)),
      'mon_ilc'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'otros1'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'otros2'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'otros3'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'reng_si'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'comis5'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comis6'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'row_id'      => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'aux01'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'aux02'       => new sfValidatorPass(array('required' => false)),
      'salestax'    => new sfValidatorPass(array('required' => false)),
      'origen'      => new sfValidatorPass(array('required' => false)),
      'origen_d'    => new sfValidatorPass(array('required' => false)),
      'fec_reg'     => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'prov_ter'    => new sfValidatorPass(array('required' => false)),
      'reng_ter'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ven_ter'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'impfis'      => new sfValidatorPass(array('required' => false)),
      'impfisfac'   => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('docum_cc_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'DocumCc';
  }

  public function getFields()
  {
    return array(
      'tipo_doc'    => 'Text',
      'nro_doc'     => 'Number',
      'anulado'     => 'Boolean',
      'movi'        => 'Number',
      'aut'         => 'Boolean',
      'num_control' => 'Number',
      'co_cli'      => 'ForeignKey',
      'contrib'     => 'Boolean',
      'fec_emis'    => 'Date',
      'fec_venc'    => 'Date',
      'observa'     => 'Text',
      'doc_orig'    => 'Text',
      'nro_orig'    => 'Number',
      'co_ban'      => 'Text',
      'nro_che'     => 'Text',
      'co_ven'      => 'ForeignKey',
      'tipo'        => 'ForeignKey',
      'tasa'        => 'Number',
      'moneda'      => 'ForeignKey',
      'monto_imp'   => 'Number',
      'monto_gen'   => 'Number',
      'monto_a1'    => 'Number',
      'monto_a2'    => 'Number',
      'monto_bru'   => 'Number',
      'descuentos'  => 'Text',
      'monto_des'   => 'Number',
      'recargo'     => 'Text',
      'monto_rec'   => 'Number',
      'monto_otr'   => 'Number',
      'monto_net'   => 'Number',
      'saldo'       => 'Number',
      'feccom'      => 'Date',
      'numcom'      => 'Number',
      'dis_cen'     => 'Text',
      'comis1'      => 'Number',
      'comis2'      => 'Number',
      'comis3'      => 'Number',
      'comis4'      => 'Number',
      'adicional'   => 'Number',
      'campo1'      => 'Text',
      'campo2'      => 'Text',
      'campo3'      => 'Text',
      'campo4'      => 'Text',
      'campo5'      => 'Text',
      'campo6'      => 'Text',
      'campo7'      => 'Text',
      'campo8'      => 'Text',
      'co_us_in'    => 'Text',
      'fe_us_in'    => 'Date',
      'co_us_mo'    => 'Text',
      'fe_us_mo'    => 'Date',
      'co_us_el'    => 'Text',
      'fe_us_el'    => 'Date',
      'revisado'    => 'Text',
      'trasnfe'     => 'Text',
      'numcon'      => 'Text',
      'co_sucu'     => 'ForeignKey',
      'rowguid'     => 'Text',
      'mon_ilc'     => 'Number',
      'otros1'      => 'Number',
      'otros2'      => 'Number',
      'otros3'      => 'Number',
      'reng_si'     => 'Boolean',
      'comis5'      => 'Number',
      'comis6'      => 'Number',
      'row_id'      => 'Date',
      'aux01'       => 'Number',
      'aux02'       => 'Text',
      'salestax'    => 'Text',
      'origen'      => 'Text',
      'origen_d'    => 'Text',
      'fec_reg'     => 'Date',
      'prov_ter'    => 'Text',
      'reng_ter'    => 'Number',
      'ven_ter'     => 'Boolean',
      'impfis'      => 'Text',
      'impfisfac'   => 'Text',
    );
  }
}
