<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Transpor', 'profit');

/**
 * BaseTranspor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $co_tran
 * @property string $des_tran
 * @property string $resp_tra
 * @property string $campo1
 * @property string $campo2
 * @property string $campo3
 * @property string $campo4
 * @property string $dis_cen
 * @property string $co_us_in
 * @property timestamp $fe_us_in
 * @property string $co_us_mo
 * @property timestamp $fe_us_mo
 * @property string $co_us_el
 * @property timestamp $fe_us_el
 * @property string $revisado
 * @property string $trasnfe
 * @property string $co_sucu
 * @property string $rowguid
 * @property Doctrine_Collection $CotizC
 * @property Doctrine_Collection $DevCli
 * @property Doctrine_Collection $Factura
 * @property Doctrine_Collection $NotDep
 * @property Doctrine_Collection $NotEnt
 * @property Doctrine_Collection $Pedidos
 * @property Doctrine_Collection $Plavent
 * @property Doctrine_Collection $RmaProv
 * 
 * @method string              getCoTran()   Returns the current record's "co_tran" value
 * @method string              getDesTran()  Returns the current record's "des_tran" value
 * @method string              getRespTra()  Returns the current record's "resp_tra" value
 * @method string              getCampo1()   Returns the current record's "campo1" value
 * @method string              getCampo2()   Returns the current record's "campo2" value
 * @method string              getCampo3()   Returns the current record's "campo3" value
 * @method string              getCampo4()   Returns the current record's "campo4" value
 * @method string              getDisCen()   Returns the current record's "dis_cen" value
 * @method string              getCoUsIn()   Returns the current record's "co_us_in" value
 * @method timestamp           getFeUsIn()   Returns the current record's "fe_us_in" value
 * @method string              getCoUsMo()   Returns the current record's "co_us_mo" value
 * @method timestamp           getFeUsMo()   Returns the current record's "fe_us_mo" value
 * @method string              getCoUsEl()   Returns the current record's "co_us_el" value
 * @method timestamp           getFeUsEl()   Returns the current record's "fe_us_el" value
 * @method string              getRevisado() Returns the current record's "revisado" value
 * @method string              getTrasnfe()  Returns the current record's "trasnfe" value
 * @method string              getCoSucu()   Returns the current record's "co_sucu" value
 * @method string              getRowguid()  Returns the current record's "rowguid" value
 * @method Doctrine_Collection getCotizC()   Returns the current record's "CotizC" collection
 * @method Doctrine_Collection getDevCli()   Returns the current record's "DevCli" collection
 * @method Doctrine_Collection getFactura()  Returns the current record's "Factura" collection
 * @method Doctrine_Collection getNotDep()   Returns the current record's "NotDep" collection
 * @method Doctrine_Collection getNotEnt()   Returns the current record's "NotEnt" collection
 * @method Doctrine_Collection getPedidos()  Returns the current record's "Pedidos" collection
 * @method Doctrine_Collection getPlavent()  Returns the current record's "Plavent" collection
 * @method Doctrine_Collection getRmaProv()  Returns the current record's "RmaProv" collection
 * @method Transpor            setCoTran()   Sets the current record's "co_tran" value
 * @method Transpor            setDesTran()  Sets the current record's "des_tran" value
 * @method Transpor            setRespTra()  Sets the current record's "resp_tra" value
 * @method Transpor            setCampo1()   Sets the current record's "campo1" value
 * @method Transpor            setCampo2()   Sets the current record's "campo2" value
 * @method Transpor            setCampo3()   Sets the current record's "campo3" value
 * @method Transpor            setCampo4()   Sets the current record's "campo4" value
 * @method Transpor            setDisCen()   Sets the current record's "dis_cen" value
 * @method Transpor            setCoUsIn()   Sets the current record's "co_us_in" value
 * @method Transpor            setFeUsIn()   Sets the current record's "fe_us_in" value
 * @method Transpor            setCoUsMo()   Sets the current record's "co_us_mo" value
 * @method Transpor            setFeUsMo()   Sets the current record's "fe_us_mo" value
 * @method Transpor            setCoUsEl()   Sets the current record's "co_us_el" value
 * @method Transpor            setFeUsEl()   Sets the current record's "fe_us_el" value
 * @method Transpor            setRevisado() Sets the current record's "revisado" value
 * @method Transpor            setTrasnfe()  Sets the current record's "trasnfe" value
 * @method Transpor            setCoSucu()   Sets the current record's "co_sucu" value
 * @method Transpor            setRowguid()  Sets the current record's "rowguid" value
 * @method Transpor            setCotizC()   Sets the current record's "CotizC" collection
 * @method Transpor            setDevCli()   Sets the current record's "DevCli" collection
 * @method Transpor            setFactura()  Sets the current record's "Factura" collection
 * @method Transpor            setNotDep()   Sets the current record's "NotDep" collection
 * @method Transpor            setNotEnt()   Sets the current record's "NotEnt" collection
 * @method Transpor            setPedidos()  Sets the current record's "Pedidos" collection
 * @method Transpor            setPlavent()  Sets the current record's "Plavent" collection
 * @method Transpor            setRmaProv()  Sets the current record's "RmaProv" collection
 * 
 * @package    gesser
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTranspor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transpor');
        $this->hasColumn('co_tran', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('des_tran', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('resp_tra', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo1', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo2', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo3', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo4', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('dis_cen', 'string', 2147483647, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('co_us_in', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_in', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_mo', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_mo', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_el', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_el', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('revisado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('trasnfe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('co_sucu', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('rowguid', 'string', 36, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(newid())',
             'primary' => false,
             'autoincrement' => false,
             'length' => 36,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CotizC', array(
             'local' => 'co_tran',
             'foreign' => 'co_tran'));

        $this->hasMany('DevCli', array(
             'local' => 'co_tran',
             'foreign' => 'co_tran'));

        $this->hasMany('Factura', array(
             'local' => 'co_tran',
             'foreign' => 'co_tran'));

        $this->hasMany('NotDep', array(
             'local' => 'co_tran',
             'foreign' => 'co_tran'));

        $this->hasMany('NotEnt', array(
             'local' => 'co_tran',
             'foreign' => 'co_tran'));

        $this->hasMany('Pedidos', array(
             'local' => 'co_tran',
             'foreign' => 'co_tran'));

        $this->hasMany('Plavent', array(
             'local' => 'co_tran',
             'foreign' => 'co_tran'));

        $this->hasMany('RmaProv', array(
             'local' => 'co_tran',
             'foreign' => 'co_tran'));
    }
}