<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Moneda', 'profit');

/**
 * BaseMoneda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $co_mone
 * @property string $mone_des
 * @property decimal $cambio
 * @property string $campo1
 * @property string $campo2
 * @property string $campo3
 * @property string $campo4
 * @property string $co_us_in
 * @property timestamp $fe_us_in
 * @property string $co_us_mo
 * @property timestamp $fe_us_mo
 * @property string $co_us_el
 * @property timestamp $fe_us_el
 * @property string $revisado
 * @property string $trasnfe
 * @property string $co_sucu
 * @property string $rowguid
 * @property Doctrine_Collection $Ajuste
 * @property Doctrine_Collection $Cobros
 * @property Doctrine_Collection $Compras
 * @property Doctrine_Collection $CotizC
 * @property Doctrine_Collection $CotizP
 * @property Doctrine_Collection $DepCaj
 * @property Doctrine_Collection $DevCli
 * @property Doctrine_Collection $DevPro
 * @property Doctrine_Collection $DocumCc
 * @property Doctrine_Collection $DocumCp
 * @property Doctrine_Collection $Factura
 * @property Doctrine_Collection $Fisico
 * @property Doctrine_Collection $GeneKit
 * @property Doctrine_Collection $Import
 * @property Doctrine_Collection $MovBan
 * @property Doctrine_Collection $MovCaj
 * @property Doctrine_Collection $NotDep
 * @property Doctrine_Collection $NotEnt
 * @property Doctrine_Collection $NotRec
 * @property Doctrine_Collection $Ordenes
 * @property Doctrine_Collection $Pagos
 * @property Doctrine_Collection $Pedidos
 * @property Doctrine_Collection $Placom
 * @property Doctrine_Collection $Plavent
 * @property Doctrine_Collection $RengAco
 * @property Doctrine_Collection $RengAim
 * @property Doctrine_Collection $RmaEntc
 * @property Doctrine_Collection $RmaEntp
 * @property Doctrine_Collection $Tasas
 * 
 * @method string              getCoMone()   Returns the current record's "co_mone" value
 * @method string              getMoneDes()  Returns the current record's "mone_des" value
 * @method decimal             getCambio()   Returns the current record's "cambio" value
 * @method string              getCampo1()   Returns the current record's "campo1" value
 * @method string              getCampo2()   Returns the current record's "campo2" value
 * @method string              getCampo3()   Returns the current record's "campo3" value
 * @method string              getCampo4()   Returns the current record's "campo4" value
 * @method string              getCoUsIn()   Returns the current record's "co_us_in" value
 * @method timestamp           getFeUsIn()   Returns the current record's "fe_us_in" value
 * @method string              getCoUsMo()   Returns the current record's "co_us_mo" value
 * @method timestamp           getFeUsMo()   Returns the current record's "fe_us_mo" value
 * @method string              getCoUsEl()   Returns the current record's "co_us_el" value
 * @method timestamp           getFeUsEl()   Returns the current record's "fe_us_el" value
 * @method string              getRevisado() Returns the current record's "revisado" value
 * @method string              getTrasnfe()  Returns the current record's "trasnfe" value
 * @method string              getCoSucu()   Returns the current record's "co_sucu" value
 * @method string              getRowguid()  Returns the current record's "rowguid" value
 * @method Doctrine_Collection getAjuste()   Returns the current record's "Ajuste" collection
 * @method Doctrine_Collection getCobros()   Returns the current record's "Cobros" collection
 * @method Doctrine_Collection getCompras()  Returns the current record's "Compras" collection
 * @method Doctrine_Collection getCotizC()   Returns the current record's "CotizC" collection
 * @method Doctrine_Collection getCotizP()   Returns the current record's "CotizP" collection
 * @method Doctrine_Collection getDepCaj()   Returns the current record's "DepCaj" collection
 * @method Doctrine_Collection getDevCli()   Returns the current record's "DevCli" collection
 * @method Doctrine_Collection getDevPro()   Returns the current record's "DevPro" collection
 * @method Doctrine_Collection getDocumCc()  Returns the current record's "DocumCc" collection
 * @method Doctrine_Collection getDocumCp()  Returns the current record's "DocumCp" collection
 * @method Doctrine_Collection getFactura()  Returns the current record's "Factura" collection
 * @method Doctrine_Collection getFisico()   Returns the current record's "Fisico" collection
 * @method Doctrine_Collection getGeneKit()  Returns the current record's "GeneKit" collection
 * @method Doctrine_Collection getImport()   Returns the current record's "Import" collection
 * @method Doctrine_Collection getMovBan()   Returns the current record's "MovBan" collection
 * @method Doctrine_Collection getMovCaj()   Returns the current record's "MovCaj" collection
 * @method Doctrine_Collection getNotDep()   Returns the current record's "NotDep" collection
 * @method Doctrine_Collection getNotEnt()   Returns the current record's "NotEnt" collection
 * @method Doctrine_Collection getNotRec()   Returns the current record's "NotRec" collection
 * @method Doctrine_Collection getOrdenes()  Returns the current record's "Ordenes" collection
 * @method Doctrine_Collection getPagos()    Returns the current record's "Pagos" collection
 * @method Doctrine_Collection getPedidos()  Returns the current record's "Pedidos" collection
 * @method Doctrine_Collection getPlacom()   Returns the current record's "Placom" collection
 * @method Doctrine_Collection getPlavent()  Returns the current record's "Plavent" collection
 * @method Doctrine_Collection getRengAco()  Returns the current record's "RengAco" collection
 * @method Doctrine_Collection getRengAim()  Returns the current record's "RengAim" collection
 * @method Doctrine_Collection getRmaEntc()  Returns the current record's "RmaEntc" collection
 * @method Doctrine_Collection getRmaEntp()  Returns the current record's "RmaEntp" collection
 * @method Doctrine_Collection getTasas()    Returns the current record's "Tasas" collection
 * @method Moneda              setCoMone()   Sets the current record's "co_mone" value
 * @method Moneda              setMoneDes()  Sets the current record's "mone_des" value
 * @method Moneda              setCambio()   Sets the current record's "cambio" value
 * @method Moneda              setCampo1()   Sets the current record's "campo1" value
 * @method Moneda              setCampo2()   Sets the current record's "campo2" value
 * @method Moneda              setCampo3()   Sets the current record's "campo3" value
 * @method Moneda              setCampo4()   Sets the current record's "campo4" value
 * @method Moneda              setCoUsIn()   Sets the current record's "co_us_in" value
 * @method Moneda              setFeUsIn()   Sets the current record's "fe_us_in" value
 * @method Moneda              setCoUsMo()   Sets the current record's "co_us_mo" value
 * @method Moneda              setFeUsMo()   Sets the current record's "fe_us_mo" value
 * @method Moneda              setCoUsEl()   Sets the current record's "co_us_el" value
 * @method Moneda              setFeUsEl()   Sets the current record's "fe_us_el" value
 * @method Moneda              setRevisado() Sets the current record's "revisado" value
 * @method Moneda              setTrasnfe()  Sets the current record's "trasnfe" value
 * @method Moneda              setCoSucu()   Sets the current record's "co_sucu" value
 * @method Moneda              setRowguid()  Sets the current record's "rowguid" value
 * @method Moneda              setAjuste()   Sets the current record's "Ajuste" collection
 * @method Moneda              setCobros()   Sets the current record's "Cobros" collection
 * @method Moneda              setCompras()  Sets the current record's "Compras" collection
 * @method Moneda              setCotizC()   Sets the current record's "CotizC" collection
 * @method Moneda              setCotizP()   Sets the current record's "CotizP" collection
 * @method Moneda              setDepCaj()   Sets the current record's "DepCaj" collection
 * @method Moneda              setDevCli()   Sets the current record's "DevCli" collection
 * @method Moneda              setDevPro()   Sets the current record's "DevPro" collection
 * @method Moneda              setDocumCc()  Sets the current record's "DocumCc" collection
 * @method Moneda              setDocumCp()  Sets the current record's "DocumCp" collection
 * @method Moneda              setFactura()  Sets the current record's "Factura" collection
 * @method Moneda              setFisico()   Sets the current record's "Fisico" collection
 * @method Moneda              setGeneKit()  Sets the current record's "GeneKit" collection
 * @method Moneda              setImport()   Sets the current record's "Import" collection
 * @method Moneda              setMovBan()   Sets the current record's "MovBan" collection
 * @method Moneda              setMovCaj()   Sets the current record's "MovCaj" collection
 * @method Moneda              setNotDep()   Sets the current record's "NotDep" collection
 * @method Moneda              setNotEnt()   Sets the current record's "NotEnt" collection
 * @method Moneda              setNotRec()   Sets the current record's "NotRec" collection
 * @method Moneda              setOrdenes()  Sets the current record's "Ordenes" collection
 * @method Moneda              setPagos()    Sets the current record's "Pagos" collection
 * @method Moneda              setPedidos()  Sets the current record's "Pedidos" collection
 * @method Moneda              setPlacom()   Sets the current record's "Placom" collection
 * @method Moneda              setPlavent()  Sets the current record's "Plavent" collection
 * @method Moneda              setRengAco()  Sets the current record's "RengAco" collection
 * @method Moneda              setRengAim()  Sets the current record's "RengAim" collection
 * @method Moneda              setRmaEntc()  Sets the current record's "RmaEntc" collection
 * @method Moneda              setRmaEntp()  Sets the current record's "RmaEntp" collection
 * @method Moneda              setTasas()    Sets the current record's "Tasas" collection
 * 
 * @package    gesser
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMoneda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('moneda');
        $this->hasColumn('co_mone', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('mone_des', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('cambio', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('campo1', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo2', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo3', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo4', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('co_us_in', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_in', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_mo', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_mo', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_el', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_el', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('revisado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('trasnfe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('co_sucu', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('rowguid', 'string', 36, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(newid())',
             'primary' => false,
             'autoincrement' => false,
             'length' => 36,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Ajuste', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('Cobros', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('Compras', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('CotizC', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('CotizP', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('DepCaj', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('DevCli', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('DevPro', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('DocumCc', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('DocumCp', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('Factura', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('Fisico', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('GeneKit', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('Import', array(
             'local' => 'co_mone',
             'foreign' => 'co_mone'));

        $this->hasMany('MovBan', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('MovCaj', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('NotDep', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('NotEnt', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('NotRec', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('Ordenes', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('Pagos', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('Pedidos', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('Placom', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('Plavent', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('RengAco', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('RengAim', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('RmaEntc', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('RmaEntp', array(
             'local' => 'co_mone',
             'foreign' => 'moneda'));

        $this->hasMany('Tasas', array(
             'local' => 'co_mone',
             'foreign' => 'co_mone'));
    }
}