<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DocumCc', 'profit');

/**
 * BaseDocumCc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tipo_doc
 * @property integer $nro_doc
 * @property boolean $anulado
 * @property integer $movi
 * @property boolean $aut
 * @property integer $num_control
 * @property string $co_cli
 * @property boolean $contrib
 * @property timestamp $fec_emis
 * @property timestamp $fec_venc
 * @property string $observa
 * @property string $doc_orig
 * @property integer $nro_orig
 * @property string $co_ban
 * @property string $nro_che
 * @property string $co_ven
 * @property string $tipo
 * @property decimal $tasa
 * @property string $moneda
 * @property decimal $monto_imp
 * @property decimal $monto_gen
 * @property decimal $monto_a1
 * @property decimal $monto_a2
 * @property decimal $monto_bru
 * @property string $descuentos
 * @property decimal $monto_des
 * @property string $recargo
 * @property decimal $monto_rec
 * @property decimal $monto_otr
 * @property decimal $monto_net
 * @property decimal $saldo
 * @property timestamp $feccom
 * @property integer $numcom
 * @property string $dis_cen
 * @property decimal $comis1
 * @property decimal $comis2
 * @property decimal $comis3
 * @property decimal $comis4
 * @property decimal $adicional
 * @property string $campo1
 * @property string $campo2
 * @property string $campo3
 * @property string $campo4
 * @property string $campo5
 * @property string $campo6
 * @property string $campo7
 * @property string $campo8
 * @property string $co_us_in
 * @property timestamp $fe_us_in
 * @property string $co_us_mo
 * @property timestamp $fe_us_mo
 * @property string $co_us_el
 * @property timestamp $fe_us_el
 * @property string $revisado
 * @property string $trasnfe
 * @property string $numcon
 * @property string $co_sucu
 * @property string $rowguid
 * @property decimal $mon_ilc
 * @property decimal $otros1
 * @property decimal $otros2
 * @property decimal $otros3
 * @property boolean $reng_si
 * @property decimal $comis5
 * @property decimal $comis6
 * @property timestamp $row_id
 * @property decimal $aux01
 * @property string $aux02
 * @property string $salestax
 * @property string $origen
 * @property string $origen_d
 * @property timestamp $fec_reg
 * @property string $prov_ter
 * @property integer $reng_ter
 * @property boolean $ven_ter
 * @property string $impfis
 * @property string $impfisfac
 * @property Clientes $Clientes
 * @property Vendedor $Vendedor
 * @property Tabulado $Tabulado
 * @property Moneda $Moneda
 * @property Almacen $Almacen
 * 
 * @method string    getTipoDoc()     Returns the current record's "tipo_doc" value
 * @method integer   getNroDoc()      Returns the current record's "nro_doc" value
 * @method boolean   getAnulado()     Returns the current record's "anulado" value
 * @method integer   getMovi()        Returns the current record's "movi" value
 * @method boolean   getAut()         Returns the current record's "aut" value
 * @method integer   getNumControl()  Returns the current record's "num_control" value
 * @method string    getCoCli()       Returns the current record's "co_cli" value
 * @method boolean   getContrib()     Returns the current record's "contrib" value
 * @method timestamp getFecEmis()     Returns the current record's "fec_emis" value
 * @method timestamp getFecVenc()     Returns the current record's "fec_venc" value
 * @method string    getObserva()     Returns the current record's "observa" value
 * @method string    getDocOrig()     Returns the current record's "doc_orig" value
 * @method integer   getNroOrig()     Returns the current record's "nro_orig" value
 * @method string    getCoBan()       Returns the current record's "co_ban" value
 * @method string    getNroChe()      Returns the current record's "nro_che" value
 * @method string    getCoVen()       Returns the current record's "co_ven" value
 * @method string    getTipo()        Returns the current record's "tipo" value
 * @method decimal   getTasa()        Returns the current record's "tasa" value
 * @method string    getMoneda()      Returns the current record's "moneda" value
 * @method decimal   getMontoImp()    Returns the current record's "monto_imp" value
 * @method decimal   getMontoGen()    Returns the current record's "monto_gen" value
 * @method decimal   getMontoA1()     Returns the current record's "monto_a1" value
 * @method decimal   getMontoA2()     Returns the current record's "monto_a2" value
 * @method decimal   getMontoBru()    Returns the current record's "monto_bru" value
 * @method string    getDescuentos()  Returns the current record's "descuentos" value
 * @method decimal   getMontoDes()    Returns the current record's "monto_des" value
 * @method string    getRecargo()     Returns the current record's "recargo" value
 * @method decimal   getMontoRec()    Returns the current record's "monto_rec" value
 * @method decimal   getMontoOtr()    Returns the current record's "monto_otr" value
 * @method decimal   getMontoNet()    Returns the current record's "monto_net" value
 * @method decimal   getSaldo()       Returns the current record's "saldo" value
 * @method timestamp getFeccom()      Returns the current record's "feccom" value
 * @method integer   getNumcom()      Returns the current record's "numcom" value
 * @method string    getDisCen()      Returns the current record's "dis_cen" value
 * @method decimal   getComis1()      Returns the current record's "comis1" value
 * @method decimal   getComis2()      Returns the current record's "comis2" value
 * @method decimal   getComis3()      Returns the current record's "comis3" value
 * @method decimal   getComis4()      Returns the current record's "comis4" value
 * @method decimal   getAdicional()   Returns the current record's "adicional" value
 * @method string    getCampo1()      Returns the current record's "campo1" value
 * @method string    getCampo2()      Returns the current record's "campo2" value
 * @method string    getCampo3()      Returns the current record's "campo3" value
 * @method string    getCampo4()      Returns the current record's "campo4" value
 * @method string    getCampo5()      Returns the current record's "campo5" value
 * @method string    getCampo6()      Returns the current record's "campo6" value
 * @method string    getCampo7()      Returns the current record's "campo7" value
 * @method string    getCampo8()      Returns the current record's "campo8" value
 * @method string    getCoUsIn()      Returns the current record's "co_us_in" value
 * @method timestamp getFeUsIn()      Returns the current record's "fe_us_in" value
 * @method string    getCoUsMo()      Returns the current record's "co_us_mo" value
 * @method timestamp getFeUsMo()      Returns the current record's "fe_us_mo" value
 * @method string    getCoUsEl()      Returns the current record's "co_us_el" value
 * @method timestamp getFeUsEl()      Returns the current record's "fe_us_el" value
 * @method string    getRevisado()    Returns the current record's "revisado" value
 * @method string    getTrasnfe()     Returns the current record's "trasnfe" value
 * @method string    getNumcon()      Returns the current record's "numcon" value
 * @method string    getCoSucu()      Returns the current record's "co_sucu" value
 * @method string    getRowguid()     Returns the current record's "rowguid" value
 * @method decimal   getMonIlc()      Returns the current record's "mon_ilc" value
 * @method decimal   getOtros1()      Returns the current record's "otros1" value
 * @method decimal   getOtros2()      Returns the current record's "otros2" value
 * @method decimal   getOtros3()      Returns the current record's "otros3" value
 * @method boolean   getRengSi()      Returns the current record's "reng_si" value
 * @method decimal   getComis5()      Returns the current record's "comis5" value
 * @method decimal   getComis6()      Returns the current record's "comis6" value
 * @method timestamp getRowId()       Returns the current record's "row_id" value
 * @method decimal   getAux01()       Returns the current record's "aux01" value
 * @method string    getAux02()       Returns the current record's "aux02" value
 * @method string    getSalestax()    Returns the current record's "salestax" value
 * @method string    getOrigen()      Returns the current record's "origen" value
 * @method string    getOrigenD()     Returns the current record's "origen_d" value
 * @method timestamp getFecReg()      Returns the current record's "fec_reg" value
 * @method string    getProvTer()     Returns the current record's "prov_ter" value
 * @method integer   getRengTer()     Returns the current record's "reng_ter" value
 * @method boolean   getVenTer()      Returns the current record's "ven_ter" value
 * @method string    getImpfis()      Returns the current record's "impfis" value
 * @method string    getImpfisfac()   Returns the current record's "impfisfac" value
 * @method Clientes  getClientes()    Returns the current record's "Clientes" value
 * @method Vendedor  getVendedor()    Returns the current record's "Vendedor" value
 * @method Tabulado  getTabulado()    Returns the current record's "Tabulado" value
 * @method Moneda    getMoneda()      Returns the current record's "Moneda" value
 * @method Almacen   getAlmacen()     Returns the current record's "Almacen" value
 * @method DocumCc   setTipoDoc()     Sets the current record's "tipo_doc" value
 * @method DocumCc   setNroDoc()      Sets the current record's "nro_doc" value
 * @method DocumCc   setAnulado()     Sets the current record's "anulado" value
 * @method DocumCc   setMovi()        Sets the current record's "movi" value
 * @method DocumCc   setAut()         Sets the current record's "aut" value
 * @method DocumCc   setNumControl()  Sets the current record's "num_control" value
 * @method DocumCc   setCoCli()       Sets the current record's "co_cli" value
 * @method DocumCc   setContrib()     Sets the current record's "contrib" value
 * @method DocumCc   setFecEmis()     Sets the current record's "fec_emis" value
 * @method DocumCc   setFecVenc()     Sets the current record's "fec_venc" value
 * @method DocumCc   setObserva()     Sets the current record's "observa" value
 * @method DocumCc   setDocOrig()     Sets the current record's "doc_orig" value
 * @method DocumCc   setNroOrig()     Sets the current record's "nro_orig" value
 * @method DocumCc   setCoBan()       Sets the current record's "co_ban" value
 * @method DocumCc   setNroChe()      Sets the current record's "nro_che" value
 * @method DocumCc   setCoVen()       Sets the current record's "co_ven" value
 * @method DocumCc   setTipo()        Sets the current record's "tipo" value
 * @method DocumCc   setTasa()        Sets the current record's "tasa" value
 * @method DocumCc   setMoneda()      Sets the current record's "moneda" value
 * @method DocumCc   setMontoImp()    Sets the current record's "monto_imp" value
 * @method DocumCc   setMontoGen()    Sets the current record's "monto_gen" value
 * @method DocumCc   setMontoA1()     Sets the current record's "monto_a1" value
 * @method DocumCc   setMontoA2()     Sets the current record's "monto_a2" value
 * @method DocumCc   setMontoBru()    Sets the current record's "monto_bru" value
 * @method DocumCc   setDescuentos()  Sets the current record's "descuentos" value
 * @method DocumCc   setMontoDes()    Sets the current record's "monto_des" value
 * @method DocumCc   setRecargo()     Sets the current record's "recargo" value
 * @method DocumCc   setMontoRec()    Sets the current record's "monto_rec" value
 * @method DocumCc   setMontoOtr()    Sets the current record's "monto_otr" value
 * @method DocumCc   setMontoNet()    Sets the current record's "monto_net" value
 * @method DocumCc   setSaldo()       Sets the current record's "saldo" value
 * @method DocumCc   setFeccom()      Sets the current record's "feccom" value
 * @method DocumCc   setNumcom()      Sets the current record's "numcom" value
 * @method DocumCc   setDisCen()      Sets the current record's "dis_cen" value
 * @method DocumCc   setComis1()      Sets the current record's "comis1" value
 * @method DocumCc   setComis2()      Sets the current record's "comis2" value
 * @method DocumCc   setComis3()      Sets the current record's "comis3" value
 * @method DocumCc   setComis4()      Sets the current record's "comis4" value
 * @method DocumCc   setAdicional()   Sets the current record's "adicional" value
 * @method DocumCc   setCampo1()      Sets the current record's "campo1" value
 * @method DocumCc   setCampo2()      Sets the current record's "campo2" value
 * @method DocumCc   setCampo3()      Sets the current record's "campo3" value
 * @method DocumCc   setCampo4()      Sets the current record's "campo4" value
 * @method DocumCc   setCampo5()      Sets the current record's "campo5" value
 * @method DocumCc   setCampo6()      Sets the current record's "campo6" value
 * @method DocumCc   setCampo7()      Sets the current record's "campo7" value
 * @method DocumCc   setCampo8()      Sets the current record's "campo8" value
 * @method DocumCc   setCoUsIn()      Sets the current record's "co_us_in" value
 * @method DocumCc   setFeUsIn()      Sets the current record's "fe_us_in" value
 * @method DocumCc   setCoUsMo()      Sets the current record's "co_us_mo" value
 * @method DocumCc   setFeUsMo()      Sets the current record's "fe_us_mo" value
 * @method DocumCc   setCoUsEl()      Sets the current record's "co_us_el" value
 * @method DocumCc   setFeUsEl()      Sets the current record's "fe_us_el" value
 * @method DocumCc   setRevisado()    Sets the current record's "revisado" value
 * @method DocumCc   setTrasnfe()     Sets the current record's "trasnfe" value
 * @method DocumCc   setNumcon()      Sets the current record's "numcon" value
 * @method DocumCc   setCoSucu()      Sets the current record's "co_sucu" value
 * @method DocumCc   setRowguid()     Sets the current record's "rowguid" value
 * @method DocumCc   setMonIlc()      Sets the current record's "mon_ilc" value
 * @method DocumCc   setOtros1()      Sets the current record's "otros1" value
 * @method DocumCc   setOtros2()      Sets the current record's "otros2" value
 * @method DocumCc   setOtros3()      Sets the current record's "otros3" value
 * @method DocumCc   setRengSi()      Sets the current record's "reng_si" value
 * @method DocumCc   setComis5()      Sets the current record's "comis5" value
 * @method DocumCc   setComis6()      Sets the current record's "comis6" value
 * @method DocumCc   setRowId()       Sets the current record's "row_id" value
 * @method DocumCc   setAux01()       Sets the current record's "aux01" value
 * @method DocumCc   setAux02()       Sets the current record's "aux02" value
 * @method DocumCc   setSalestax()    Sets the current record's "salestax" value
 * @method DocumCc   setOrigen()      Sets the current record's "origen" value
 * @method DocumCc   setOrigenD()     Sets the current record's "origen_d" value
 * @method DocumCc   setFecReg()      Sets the current record's "fec_reg" value
 * @method DocumCc   setProvTer()     Sets the current record's "prov_ter" value
 * @method DocumCc   setRengTer()     Sets the current record's "reng_ter" value
 * @method DocumCc   setVenTer()      Sets the current record's "ven_ter" value
 * @method DocumCc   setImpfis()      Sets the current record's "impfis" value
 * @method DocumCc   setImpfisfac()   Sets the current record's "impfisfac" value
 * @method DocumCc   setClientes()    Sets the current record's "Clientes" value
 * @method DocumCc   setVendedor()    Sets the current record's "Vendedor" value
 * @method DocumCc   setTabulado()    Sets the current record's "Tabulado" value
 * @method DocumCc   setMoneda()      Sets the current record's "Moneda" value
 * @method DocumCc   setAlmacen()     Sets the current record's "Almacen" value
 * 
 * @package    gesser
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumCc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('docum_cc');
        $this->hasColumn('tipo_doc', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nro_doc', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('anulado', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('movi', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('aut', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('num_control', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('co_cli', 'string', 10, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('contrib', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('fec_emis', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(convert(varchar(10),getdate(),104))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('fec_venc', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(convert(varchar(10),getdate(),104))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('observa', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 120,
             ));
        $this->hasColumn('doc_orig', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nro_orig', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('co_ban', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(\'0\')',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('nro_che', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('co_ven', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('tipo', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(\'1\')',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('tasa', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(1)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('moneda', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('monto_imp', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('monto_gen', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('monto_a1', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('monto_a2', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('monto_bru', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('descuentos', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('monto_des', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('recargo', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('monto_rec', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('monto_otr', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('monto_net', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('saldo', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('feccom', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(\'01/01/1900\')',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('numcom', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('dis_cen', 'string', 2147483647, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('comis1', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('comis2', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('comis3', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('comis4', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('adicional', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('campo1', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo2', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo3', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo4', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo5', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo6', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo7', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo8', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('co_us_in', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_in', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_mo', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_mo', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_el', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_el', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('revisado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('trasnfe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('numcon', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('co_sucu', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('rowguid', 'string', 36, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(newid())',
             'primary' => false,
             'autoincrement' => false,
             'length' => 36,
             ));
        $this->hasColumn('mon_ilc', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('otros1', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('otros2', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('otros3', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('reng_si', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('comis5', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('comis6', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('row_id', 'timestamp', 8, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('aux01', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('aux02', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('salestax', 'string', 8, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('origen', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('origen_d', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('fec_reg', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(convert(varchar(10),\'01/01/1900\',104))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('prov_ter', 'string', 10, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('reng_ter', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ven_ter', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('impfis', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('impfisfac', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Clientes', array(
             'local' => 'co_cli',
             'foreign' => 'co_cli'));

        $this->hasOne('Vendedor', array(
             'local' => 'co_ven',
             'foreign' => 'co_ven'));

        $this->hasOne('Tabulado', array(
             'local' => 'tipo',
             'foreign' => 'tipo'));

        $this->hasOne('Moneda', array(
             'local' => 'moneda',
             'foreign' => 'co_mone'));

        $this->hasOne('Almacen', array(
             'local' => 'co_sucu',
             'foreign' => 'co_alma'));
    }
}