<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tax', 'profit');

/**
 * BaseTax
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tax_id
 * @property string $tax_des
 * @property string $entidad
 * @property decimal $tasa1
 * @property decimal $tasa2
 * @property decimal $tasa3
 * @property boolean $formula
 * @property decimal $limite
 * @property decimal $porc1
 * @property decimal $porc2
 * @property string $dis_cen
 * @property string $campo1
 * @property string $campo2
 * @property string $campo3
 * @property string $campo4
 * @property string $co_us_in
 * @property timestamp $fe_us_in
 * @property string $co_us_mo
 * @property timestamp $fe_us_mo
 * @property string $co_us_el
 * @property timestamp $fe_us_el
 * @property string $revisado
 * @property string $trasnfe
 * @property string $co_sucu
 * @property string $rowguid
 * @property Doctrine_Collection $RengTax
 * 
 * @method string              getTaxId()    Returns the current record's "tax_id" value
 * @method string              getTaxDes()   Returns the current record's "tax_des" value
 * @method string              getEntidad()  Returns the current record's "entidad" value
 * @method decimal             getTasa1()    Returns the current record's "tasa1" value
 * @method decimal             getTasa2()    Returns the current record's "tasa2" value
 * @method decimal             getTasa3()    Returns the current record's "tasa3" value
 * @method boolean             getFormula()  Returns the current record's "formula" value
 * @method decimal             getLimite()   Returns the current record's "limite" value
 * @method decimal             getPorc1()    Returns the current record's "porc1" value
 * @method decimal             getPorc2()    Returns the current record's "porc2" value
 * @method string              getDisCen()   Returns the current record's "dis_cen" value
 * @method string              getCampo1()   Returns the current record's "campo1" value
 * @method string              getCampo2()   Returns the current record's "campo2" value
 * @method string              getCampo3()   Returns the current record's "campo3" value
 * @method string              getCampo4()   Returns the current record's "campo4" value
 * @method string              getCoUsIn()   Returns the current record's "co_us_in" value
 * @method timestamp           getFeUsIn()   Returns the current record's "fe_us_in" value
 * @method string              getCoUsMo()   Returns the current record's "co_us_mo" value
 * @method timestamp           getFeUsMo()   Returns the current record's "fe_us_mo" value
 * @method string              getCoUsEl()   Returns the current record's "co_us_el" value
 * @method timestamp           getFeUsEl()   Returns the current record's "fe_us_el" value
 * @method string              getRevisado() Returns the current record's "revisado" value
 * @method string              getTrasnfe()  Returns the current record's "trasnfe" value
 * @method string              getCoSucu()   Returns the current record's "co_sucu" value
 * @method string              getRowguid()  Returns the current record's "rowguid" value
 * @method Doctrine_Collection getRengTax()  Returns the current record's "RengTax" collection
 * @method Tax                 setTaxId()    Sets the current record's "tax_id" value
 * @method Tax                 setTaxDes()   Sets the current record's "tax_des" value
 * @method Tax                 setEntidad()  Sets the current record's "entidad" value
 * @method Tax                 setTasa1()    Sets the current record's "tasa1" value
 * @method Tax                 setTasa2()    Sets the current record's "tasa2" value
 * @method Tax                 setTasa3()    Sets the current record's "tasa3" value
 * @method Tax                 setFormula()  Sets the current record's "formula" value
 * @method Tax                 setLimite()   Sets the current record's "limite" value
 * @method Tax                 setPorc1()    Sets the current record's "porc1" value
 * @method Tax                 setPorc2()    Sets the current record's "porc2" value
 * @method Tax                 setDisCen()   Sets the current record's "dis_cen" value
 * @method Tax                 setCampo1()   Sets the current record's "campo1" value
 * @method Tax                 setCampo2()   Sets the current record's "campo2" value
 * @method Tax                 setCampo3()   Sets the current record's "campo3" value
 * @method Tax                 setCampo4()   Sets the current record's "campo4" value
 * @method Tax                 setCoUsIn()   Sets the current record's "co_us_in" value
 * @method Tax                 setFeUsIn()   Sets the current record's "fe_us_in" value
 * @method Tax                 setCoUsMo()   Sets the current record's "co_us_mo" value
 * @method Tax                 setFeUsMo()   Sets the current record's "fe_us_mo" value
 * @method Tax                 setCoUsEl()   Sets the current record's "co_us_el" value
 * @method Tax                 setFeUsEl()   Sets the current record's "fe_us_el" value
 * @method Tax                 setRevisado() Sets the current record's "revisado" value
 * @method Tax                 setTrasnfe()  Sets the current record's "trasnfe" value
 * @method Tax                 setCoSucu()   Sets the current record's "co_sucu" value
 * @method Tax                 setRowguid()  Sets the current record's "rowguid" value
 * @method Tax                 setRengTax()  Sets the current record's "RengTax" collection
 * 
 * @package    gesser
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTax extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Tax');
        $this->hasColumn('tax_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('tax_des', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('entidad', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('tasa1', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('tasa2', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('tasa3', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('formula', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('limite', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('porc1', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('porc2', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('dis_cen', 'string', 2147483647, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('campo1', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo2', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo3', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo4', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('co_us_in', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_in', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_mo', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_mo', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_el', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_el', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('revisado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('trasnfe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('co_sucu', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('rowguid', 'string', 36, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(newid())',
             'primary' => false,
             'autoincrement' => false,
             'length' => 36,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RengTax', array(
             'local' => 'tax_id',
             'foreign' => 'tax_id'));
    }
}