<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ParConc', 'profit');

/**
 * BaseParConc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $co_conf
 * @property string $des_conf
 * @property string $co_ban
 * @property boolean $opc_doc
 * @property integer $tip_conc
 * @property integer $cantidad
 * @property boolean $opc_fec
 * @property integer $margen
 * @property integer $margen2
 * @property string $co_sucu
 * @property string $revisado
 * @property string $trasnfe
 * @property string $campo1
 * @property string $campo2
 * @property string $campo3
 * @property string $campo4
 * @property string $co_us_in
 * @property timestamp $fe_us_in
 * @property string $co_us_mo
 * @property timestamp $fe_us_mo
 * @property string $co_us_el
 * @property timestamp $fe_us_el
 * @property string $rowguid
 * @property Bancos $Bancos
 * 
 * @method string    getCoConf()   Returns the current record's "co_conf" value
 * @method string    getDesConf()  Returns the current record's "des_conf" value
 * @method string    getCoBan()    Returns the current record's "co_ban" value
 * @method boolean   getOpcDoc()   Returns the current record's "opc_doc" value
 * @method integer   getTipConc()  Returns the current record's "tip_conc" value
 * @method integer   getCantidad() Returns the current record's "cantidad" value
 * @method boolean   getOpcFec()   Returns the current record's "opc_fec" value
 * @method integer   getMargen()   Returns the current record's "margen" value
 * @method integer   getMargen2()  Returns the current record's "margen2" value
 * @method string    getCoSucu()   Returns the current record's "co_sucu" value
 * @method string    getRevisado() Returns the current record's "revisado" value
 * @method string    getTrasnfe()  Returns the current record's "trasnfe" value
 * @method string    getCampo1()   Returns the current record's "campo1" value
 * @method string    getCampo2()   Returns the current record's "campo2" value
 * @method string    getCampo3()   Returns the current record's "campo3" value
 * @method string    getCampo4()   Returns the current record's "campo4" value
 * @method string    getCoUsIn()   Returns the current record's "co_us_in" value
 * @method timestamp getFeUsIn()   Returns the current record's "fe_us_in" value
 * @method string    getCoUsMo()   Returns the current record's "co_us_mo" value
 * @method timestamp getFeUsMo()   Returns the current record's "fe_us_mo" value
 * @method string    getCoUsEl()   Returns the current record's "co_us_el" value
 * @method timestamp getFeUsEl()   Returns the current record's "fe_us_el" value
 * @method string    getRowguid()  Returns the current record's "rowguid" value
 * @method Bancos    getBancos()   Returns the current record's "Bancos" value
 * @method ParConc   setCoConf()   Sets the current record's "co_conf" value
 * @method ParConc   setDesConf()  Sets the current record's "des_conf" value
 * @method ParConc   setCoBan()    Sets the current record's "co_ban" value
 * @method ParConc   setOpcDoc()   Sets the current record's "opc_doc" value
 * @method ParConc   setTipConc()  Sets the current record's "tip_conc" value
 * @method ParConc   setCantidad() Sets the current record's "cantidad" value
 * @method ParConc   setOpcFec()   Sets the current record's "opc_fec" value
 * @method ParConc   setMargen()   Sets the current record's "margen" value
 * @method ParConc   setMargen2()  Sets the current record's "margen2" value
 * @method ParConc   setCoSucu()   Sets the current record's "co_sucu" value
 * @method ParConc   setRevisado() Sets the current record's "revisado" value
 * @method ParConc   setTrasnfe()  Sets the current record's "trasnfe" value
 * @method ParConc   setCampo1()   Sets the current record's "campo1" value
 * @method ParConc   setCampo2()   Sets the current record's "campo2" value
 * @method ParConc   setCampo3()   Sets the current record's "campo3" value
 * @method ParConc   setCampo4()   Sets the current record's "campo4" value
 * @method ParConc   setCoUsIn()   Sets the current record's "co_us_in" value
 * @method ParConc   setFeUsIn()   Sets the current record's "fe_us_in" value
 * @method ParConc   setCoUsMo()   Sets the current record's "co_us_mo" value
 * @method ParConc   setFeUsMo()   Sets the current record's "fe_us_mo" value
 * @method ParConc   setCoUsEl()   Sets the current record's "co_us_el" value
 * @method ParConc   setFeUsEl()   Sets the current record's "fe_us_el" value
 * @method ParConc   setRowguid()  Sets the current record's "rowguid" value
 * @method ParConc   setBancos()   Sets the current record's "Bancos" value
 * 
 * @package    gesser
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParConc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('par_conc');
        $this->hasColumn('co_conf', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('des_conf', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('co_ban', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('opc_doc', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('tip_conc', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('opc_fec', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('margen', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('margen2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('co_sucu', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('revisado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('trasnfe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('campo1', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo2', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo3', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo4', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('co_us_in', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_in', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_mo', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_mo', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_el', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_el', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('rowguid', 'string', 36, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(newid())',
             'primary' => false,
             'autoincrement' => false,
             'length' => 36,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Bancos', array(
             'local' => 'co_ban',
             'foreign' => 'co_ban'));
    }
}