<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RengMen', 'profit');

/**
 * BaseRengMen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $men_num
 * @property integer $reng_num
 * @property integer $odp_num
 * @property string $co_art
 * @property decimal $cantidad
 * @property decimal $pendpro
 * @property decimal $stockop
 * @property decimal $stockact
 * @property decimal $diasinv
 * @property integer $diasprod
 * @property integer $holgura
 * @property decimal $cantprod
 * @property string $periodo
 * @property integer $cod_ced
 * @property decimal $mesprox
 * @property decimal $comprom
 * @property boolean $producir
 * @property string $rowguid
 * @property Spmenenc $Spmenenc
 * 
 * @method integer  getMenNum()   Returns the current record's "men_num" value
 * @method integer  getRengNum()  Returns the current record's "reng_num" value
 * @method integer  getOdpNum()   Returns the current record's "odp_num" value
 * @method string   getCoArt()    Returns the current record's "co_art" value
 * @method decimal  getCantidad() Returns the current record's "cantidad" value
 * @method decimal  getPendpro()  Returns the current record's "pendpro" value
 * @method decimal  getStockop()  Returns the current record's "stockop" value
 * @method decimal  getStockact() Returns the current record's "stockact" value
 * @method decimal  getDiasinv()  Returns the current record's "diasinv" value
 * @method integer  getDiasprod() Returns the current record's "diasprod" value
 * @method integer  getHolgura()  Returns the current record's "holgura" value
 * @method decimal  getCantprod() Returns the current record's "cantprod" value
 * @method string   getPeriodo()  Returns the current record's "periodo" value
 * @method integer  getCodCed()   Returns the current record's "cod_ced" value
 * @method decimal  getMesprox()  Returns the current record's "mesprox" value
 * @method decimal  getComprom()  Returns the current record's "comprom" value
 * @method boolean  getProducir() Returns the current record's "producir" value
 * @method string   getRowguid()  Returns the current record's "rowguid" value
 * @method Spmenenc getSpmenenc() Returns the current record's "Spmenenc" value
 * @method RengMen  setMenNum()   Sets the current record's "men_num" value
 * @method RengMen  setRengNum()  Sets the current record's "reng_num" value
 * @method RengMen  setOdpNum()   Sets the current record's "odp_num" value
 * @method RengMen  setCoArt()    Sets the current record's "co_art" value
 * @method RengMen  setCantidad() Sets the current record's "cantidad" value
 * @method RengMen  setPendpro()  Sets the current record's "pendpro" value
 * @method RengMen  setStockop()  Sets the current record's "stockop" value
 * @method RengMen  setStockact() Sets the current record's "stockact" value
 * @method RengMen  setDiasinv()  Sets the current record's "diasinv" value
 * @method RengMen  setDiasprod() Sets the current record's "diasprod" value
 * @method RengMen  setHolgura()  Sets the current record's "holgura" value
 * @method RengMen  setCantprod() Sets the current record's "cantprod" value
 * @method RengMen  setPeriodo()  Sets the current record's "periodo" value
 * @method RengMen  setCodCed()   Sets the current record's "cod_ced" value
 * @method RengMen  setMesprox()  Sets the current record's "mesprox" value
 * @method RengMen  setComprom()  Sets the current record's "comprom" value
 * @method RengMen  setProducir() Sets the current record's "producir" value
 * @method RengMen  setRowguid()  Sets the current record's "rowguid" value
 * @method RengMen  setSpmenenc() Sets the current record's "Spmenenc" value
 * 
 * @package    gesser
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRengMen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reng_men');
        $this->hasColumn('men_num', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('reng_num', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('odp_num', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('co_art', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('cantidad', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('pendpro', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('stockop', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('stockact', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('diasinv', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('diasprod', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('holgura', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantprod', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('periodo', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('cod_ced', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mesprox', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('comprom', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('producir', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('rowguid', 'string', 36, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(newid())',
             'primary' => false,
             'autoincrement' => false,
             'length' => 36,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Spmenenc', array(
             'local' => 'men_num',
             'foreign' => 'men_num'));
    }
}