<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NotRec', 'profit');

/**
 * BaseNotRec
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fact_num
 * @property string $factura
 * @property boolean $contrib
 * @property string $dis_cen
 * @property string $nombre
 * @property string $rif
 * @property string $nit
 * @property string $status
 * @property string $comentario
 * @property string $descrip
 * @property decimal $saldo
 * @property timestamp $fec_emis
 * @property timestamp $fec_venc
 * @property string $co_cli
 * @property string $co_ven
 * @property string $co_tran
 * @property string $dir_ent
 * @property string $forma_pag
 * @property decimal $tot_bruto
 * @property decimal $tot_neto
 * @property decimal $glob_desc
 * @property decimal $tot_reca
 * @property string $porc_gdesc
 * @property string $porc_reca
 * @property decimal $total_uc
 * @property decimal $total_cp
 * @property decimal $tot_flete
 * @property decimal $monto_dev
 * @property decimal $totklu
 * @property boolean $anulada
 * @property boolean $impresa
 * @property decimal $iva
 * @property decimal $iva_dev
 * @property timestamp $feccom
 * @property integer $numcom
 * @property decimal $tasa
 * @property string $moneda
 * @property string $cta_contab
 * @property integer $seriales
 * @property decimal $tasag
 * @property decimal $tasag10
 * @property decimal $tasag20
 * @property string $campo1
 * @property string $campo2
 * @property string $campo3
 * @property string $campo4
 * @property string $campo5
 * @property string $campo6
 * @property string $campo7
 * @property string $campo8
 * @property string $co_us_in
 * @property timestamp $fe_us_in
 * @property string $co_us_mo
 * @property timestamp $fe_us_mo
 * @property string $co_us_el
 * @property timestamp $fe_us_el
 * @property string $revisado
 * @property string $trasnfe
 * @property string $co_sucu
 * @property string $rowguid
 * @property decimal $mon_ilc
 * @property decimal $otros1
 * @property decimal $otros2
 * @property decimal $otros3
 * @property decimal $aux01
 * @property string $aux02
 * @property string $salestax
 * @property string $origen
 * @property string $origen_d
 * @property string $sta_prod
 * @property string $telefono
 * @property Prov $Prov
 * @property Condicio $Condicio
 * @property Moneda $Moneda
 * @property Almacen $Almacen
 * 
 * @method integer   getFactNum()    Returns the current record's "fact_num" value
 * @method string    getFactura()    Returns the current record's "factura" value
 * @method boolean   getContrib()    Returns the current record's "contrib" value
 * @method string    getDisCen()     Returns the current record's "dis_cen" value
 * @method string    getNombre()     Returns the current record's "nombre" value
 * @method string    getRif()        Returns the current record's "rif" value
 * @method string    getNit()        Returns the current record's "nit" value
 * @method string    getStatus()     Returns the current record's "status" value
 * @method string    getComentario() Returns the current record's "comentario" value
 * @method string    getDescrip()    Returns the current record's "descrip" value
 * @method decimal   getSaldo()      Returns the current record's "saldo" value
 * @method timestamp getFecEmis()    Returns the current record's "fec_emis" value
 * @method timestamp getFecVenc()    Returns the current record's "fec_venc" value
 * @method string    getCoCli()      Returns the current record's "co_cli" value
 * @method string    getCoVen()      Returns the current record's "co_ven" value
 * @method string    getCoTran()     Returns the current record's "co_tran" value
 * @method string    getDirEnt()     Returns the current record's "dir_ent" value
 * @method string    getFormaPag()   Returns the current record's "forma_pag" value
 * @method decimal   getTotBruto()   Returns the current record's "tot_bruto" value
 * @method decimal   getTotNeto()    Returns the current record's "tot_neto" value
 * @method decimal   getGlobDesc()   Returns the current record's "glob_desc" value
 * @method decimal   getTotReca()    Returns the current record's "tot_reca" value
 * @method string    getPorcGdesc()  Returns the current record's "porc_gdesc" value
 * @method string    getPorcReca()   Returns the current record's "porc_reca" value
 * @method decimal   getTotalUc()    Returns the current record's "total_uc" value
 * @method decimal   getTotalCp()    Returns the current record's "total_cp" value
 * @method decimal   getTotFlete()   Returns the current record's "tot_flete" value
 * @method decimal   getMontoDev()   Returns the current record's "monto_dev" value
 * @method decimal   getTotklu()     Returns the current record's "totklu" value
 * @method boolean   getAnulada()    Returns the current record's "anulada" value
 * @method boolean   getImpresa()    Returns the current record's "impresa" value
 * @method decimal   getIva()        Returns the current record's "iva" value
 * @method decimal   getIvaDev()     Returns the current record's "iva_dev" value
 * @method timestamp getFeccom()     Returns the current record's "feccom" value
 * @method integer   getNumcom()     Returns the current record's "numcom" value
 * @method decimal   getTasa()       Returns the current record's "tasa" value
 * @method string    getMoneda()     Returns the current record's "moneda" value
 * @method string    getCtaContab()  Returns the current record's "cta_contab" value
 * @method integer   getSeriales()   Returns the current record's "seriales" value
 * @method decimal   getTasag()      Returns the current record's "tasag" value
 * @method decimal   getTasag10()    Returns the current record's "tasag10" value
 * @method decimal   getTasag20()    Returns the current record's "tasag20" value
 * @method string    getCampo1()     Returns the current record's "campo1" value
 * @method string    getCampo2()     Returns the current record's "campo2" value
 * @method string    getCampo3()     Returns the current record's "campo3" value
 * @method string    getCampo4()     Returns the current record's "campo4" value
 * @method string    getCampo5()     Returns the current record's "campo5" value
 * @method string    getCampo6()     Returns the current record's "campo6" value
 * @method string    getCampo7()     Returns the current record's "campo7" value
 * @method string    getCampo8()     Returns the current record's "campo8" value
 * @method string    getCoUsIn()     Returns the current record's "co_us_in" value
 * @method timestamp getFeUsIn()     Returns the current record's "fe_us_in" value
 * @method string    getCoUsMo()     Returns the current record's "co_us_mo" value
 * @method timestamp getFeUsMo()     Returns the current record's "fe_us_mo" value
 * @method string    getCoUsEl()     Returns the current record's "co_us_el" value
 * @method timestamp getFeUsEl()     Returns the current record's "fe_us_el" value
 * @method string    getRevisado()   Returns the current record's "revisado" value
 * @method string    getTrasnfe()    Returns the current record's "trasnfe" value
 * @method string    getCoSucu()     Returns the current record's "co_sucu" value
 * @method string    getRowguid()    Returns the current record's "rowguid" value
 * @method decimal   getMonIlc()     Returns the current record's "mon_ilc" value
 * @method decimal   getOtros1()     Returns the current record's "otros1" value
 * @method decimal   getOtros2()     Returns the current record's "otros2" value
 * @method decimal   getOtros3()     Returns the current record's "otros3" value
 * @method decimal   getAux01()      Returns the current record's "aux01" value
 * @method string    getAux02()      Returns the current record's "aux02" value
 * @method string    getSalestax()   Returns the current record's "salestax" value
 * @method string    getOrigen()     Returns the current record's "origen" value
 * @method string    getOrigenD()    Returns the current record's "origen_d" value
 * @method string    getStaProd()    Returns the current record's "sta_prod" value
 * @method string    getTelefono()   Returns the current record's "telefono" value
 * @method Prov      getProv()       Returns the current record's "Prov" value
 * @method Condicio  getCondicio()   Returns the current record's "Condicio" value
 * @method Moneda    getMoneda()     Returns the current record's "Moneda" value
 * @method Almacen   getAlmacen()    Returns the current record's "Almacen" value
 * @method NotRec    setFactNum()    Sets the current record's "fact_num" value
 * @method NotRec    setFactura()    Sets the current record's "factura" value
 * @method NotRec    setContrib()    Sets the current record's "contrib" value
 * @method NotRec    setDisCen()     Sets the current record's "dis_cen" value
 * @method NotRec    setNombre()     Sets the current record's "nombre" value
 * @method NotRec    setRif()        Sets the current record's "rif" value
 * @method NotRec    setNit()        Sets the current record's "nit" value
 * @method NotRec    setStatus()     Sets the current record's "status" value
 * @method NotRec    setComentario() Sets the current record's "comentario" value
 * @method NotRec    setDescrip()    Sets the current record's "descrip" value
 * @method NotRec    setSaldo()      Sets the current record's "saldo" value
 * @method NotRec    setFecEmis()    Sets the current record's "fec_emis" value
 * @method NotRec    setFecVenc()    Sets the current record's "fec_venc" value
 * @method NotRec    setCoCli()      Sets the current record's "co_cli" value
 * @method NotRec    setCoVen()      Sets the current record's "co_ven" value
 * @method NotRec    setCoTran()     Sets the current record's "co_tran" value
 * @method NotRec    setDirEnt()     Sets the current record's "dir_ent" value
 * @method NotRec    setFormaPag()   Sets the current record's "forma_pag" value
 * @method NotRec    setTotBruto()   Sets the current record's "tot_bruto" value
 * @method NotRec    setTotNeto()    Sets the current record's "tot_neto" value
 * @method NotRec    setGlobDesc()   Sets the current record's "glob_desc" value
 * @method NotRec    setTotReca()    Sets the current record's "tot_reca" value
 * @method NotRec    setPorcGdesc()  Sets the current record's "porc_gdesc" value
 * @method NotRec    setPorcReca()   Sets the current record's "porc_reca" value
 * @method NotRec    setTotalUc()    Sets the current record's "total_uc" value
 * @method NotRec    setTotalCp()    Sets the current record's "total_cp" value
 * @method NotRec    setTotFlete()   Sets the current record's "tot_flete" value
 * @method NotRec    setMontoDev()   Sets the current record's "monto_dev" value
 * @method NotRec    setTotklu()     Sets the current record's "totklu" value
 * @method NotRec    setAnulada()    Sets the current record's "anulada" value
 * @method NotRec    setImpresa()    Sets the current record's "impresa" value
 * @method NotRec    setIva()        Sets the current record's "iva" value
 * @method NotRec    setIvaDev()     Sets the current record's "iva_dev" value
 * @method NotRec    setFeccom()     Sets the current record's "feccom" value
 * @method NotRec    setNumcom()     Sets the current record's "numcom" value
 * @method NotRec    setTasa()       Sets the current record's "tasa" value
 * @method NotRec    setMoneda()     Sets the current record's "moneda" value
 * @method NotRec    setCtaContab()  Sets the current record's "cta_contab" value
 * @method NotRec    setSeriales()   Sets the current record's "seriales" value
 * @method NotRec    setTasag()      Sets the current record's "tasag" value
 * @method NotRec    setTasag10()    Sets the current record's "tasag10" value
 * @method NotRec    setTasag20()    Sets the current record's "tasag20" value
 * @method NotRec    setCampo1()     Sets the current record's "campo1" value
 * @method NotRec    setCampo2()     Sets the current record's "campo2" value
 * @method NotRec    setCampo3()     Sets the current record's "campo3" value
 * @method NotRec    setCampo4()     Sets the current record's "campo4" value
 * @method NotRec    setCampo5()     Sets the current record's "campo5" value
 * @method NotRec    setCampo6()     Sets the current record's "campo6" value
 * @method NotRec    setCampo7()     Sets the current record's "campo7" value
 * @method NotRec    setCampo8()     Sets the current record's "campo8" value
 * @method NotRec    setCoUsIn()     Sets the current record's "co_us_in" value
 * @method NotRec    setFeUsIn()     Sets the current record's "fe_us_in" value
 * @method NotRec    setCoUsMo()     Sets the current record's "co_us_mo" value
 * @method NotRec    setFeUsMo()     Sets the current record's "fe_us_mo" value
 * @method NotRec    setCoUsEl()     Sets the current record's "co_us_el" value
 * @method NotRec    setFeUsEl()     Sets the current record's "fe_us_el" value
 * @method NotRec    setRevisado()   Sets the current record's "revisado" value
 * @method NotRec    setTrasnfe()    Sets the current record's "trasnfe" value
 * @method NotRec    setCoSucu()     Sets the current record's "co_sucu" value
 * @method NotRec    setRowguid()    Sets the current record's "rowguid" value
 * @method NotRec    setMonIlc()     Sets the current record's "mon_ilc" value
 * @method NotRec    setOtros1()     Sets the current record's "otros1" value
 * @method NotRec    setOtros2()     Sets the current record's "otros2" value
 * @method NotRec    setOtros3()     Sets the current record's "otros3" value
 * @method NotRec    setAux01()      Sets the current record's "aux01" value
 * @method NotRec    setAux02()      Sets the current record's "aux02" value
 * @method NotRec    setSalestax()   Sets the current record's "salestax" value
 * @method NotRec    setOrigen()     Sets the current record's "origen" value
 * @method NotRec    setOrigenD()    Sets the current record's "origen_d" value
 * @method NotRec    setStaProd()    Sets the current record's "sta_prod" value
 * @method NotRec    setTelefono()   Sets the current record's "telefono" value
 * @method NotRec    setProv()       Sets the current record's "Prov" value
 * @method NotRec    setCondicio()   Sets the current record's "Condicio" value
 * @method NotRec    setMoneda()     Sets the current record's "Moneda" value
 * @method NotRec    setAlmacen()    Sets the current record's "Almacen" value
 * 
 * @package    gesser
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotRec extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('not_rec');
        $this->hasColumn('fact_num', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('factura', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('contrib', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('dis_cen', 'string', 2147483647, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('nombre', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('rif', 'string', 18, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('nit', 'string', 18, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('comentario', 'string', 2147483647, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('descrip', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('saldo', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('fec_emis', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(CONVERT([varchar](10),getdate(),(104)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('fec_venc', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(CONVERT([varchar](10),getdate(),(104)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_cli', 'string', 10, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('co_ven', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('co_tran', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('dir_ent', 'string', 2147483647, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('forma_pag', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('tot_bruto', 'decimal', 22, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 22,
             ));
        $this->hasColumn('tot_neto', 'decimal', 22, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 22,
             ));
        $this->hasColumn('glob_desc', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('tot_reca', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('porc_gdesc', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('porc_reca', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('total_uc', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('total_cp', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('tot_flete', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('monto_dev', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('totklu', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('anulada', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('impresa', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('iva', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('iva_dev', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('feccom', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(\'01/01/1900\')',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('numcom', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tasa', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('moneda', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('cta_contab', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('seriales', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tasag', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('tasag10', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('tasag20', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('campo1', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo2', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo3', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo4', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo5', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo6', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo7', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo8', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('co_us_in', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('fe_us_in', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond, -datepart(millisecond,getdate()),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_mo', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('fe_us_mo', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond, -datepart(millisecond,getdate()),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_el', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('fe_us_el', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond, -datepart(millisecond,getdate()),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('revisado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('trasnfe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('co_sucu', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('rowguid', 'string', 36, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(newid())',
             'primary' => false,
             'autoincrement' => false,
             'length' => 36,
             ));
        $this->hasColumn('mon_ilc', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('otros1', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('otros2', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('otros3', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('aux01', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('aux02', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('salestax', 'string', 8, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('origen', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('origen_d', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('sta_prod', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'default' => '(space((1)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space((60)))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Prov', array(
             'local' => 'co_cli',
             'foreign' => 'co_prov'));

        $this->hasOne('Condicio', array(
             'local' => 'forma_pag',
             'foreign' => 'co_cond'));

        $this->hasOne('Moneda', array(
             'local' => 'moneda',
             'foreign' => 'co_mone'));

        $this->hasOne('Almacen', array(
             'local' => 'co_sucu',
             'foreign' => 'co_alma'));
    }
}