<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tabulado', 'profit');

/**
 * BaseTabulado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tipo
 * @property string $descripcio
 * @property decimal $porc_vent
 * @property decimal $porc_comp
 * @property decimal $porc_cxs
 * @property decimal $porc_otro
 * @property string $revisado
 * @property string $trasnfe
 * @property string $rowguid
 * @property Doctrine_Collection $Art
 * @property Doctrine_Collection $DocumCc
 * @property Doctrine_Collection $DocumCp
 * @property Doctrine_Collection $RengCac
 * @property Doctrine_Collection $RengDvc
 * @property Doctrine_Collection $RengFac
 * @property Doctrine_Collection $RengNdd
 * @property Doctrine_Collection $RengPed
 * 
 * @method string              getTipo()       Returns the current record's "tipo" value
 * @method string              getDescripcio() Returns the current record's "descripcio" value
 * @method decimal             getPorcVent()   Returns the current record's "porc_vent" value
 * @method decimal             getPorcComp()   Returns the current record's "porc_comp" value
 * @method decimal             getPorcCxs()    Returns the current record's "porc_cxs" value
 * @method decimal             getPorcOtro()   Returns the current record's "porc_otro" value
 * @method string              getRevisado()   Returns the current record's "revisado" value
 * @method string              getTrasnfe()    Returns the current record's "trasnfe" value
 * @method string              getRowguid()    Returns the current record's "rowguid" value
 * @method Doctrine_Collection getArt()        Returns the current record's "Art" collection
 * @method Doctrine_Collection getDocumCc()    Returns the current record's "DocumCc" collection
 * @method Doctrine_Collection getDocumCp()    Returns the current record's "DocumCp" collection
 * @method Doctrine_Collection getRengCac()    Returns the current record's "RengCac" collection
 * @method Doctrine_Collection getRengDvc()    Returns the current record's "RengDvc" collection
 * @method Doctrine_Collection getRengFac()    Returns the current record's "RengFac" collection
 * @method Doctrine_Collection getRengNdd()    Returns the current record's "RengNdd" collection
 * @method Doctrine_Collection getRengPed()    Returns the current record's "RengPed" collection
 * @method Tabulado            setTipo()       Sets the current record's "tipo" value
 * @method Tabulado            setDescripcio() Sets the current record's "descripcio" value
 * @method Tabulado            setPorcVent()   Sets the current record's "porc_vent" value
 * @method Tabulado            setPorcComp()   Sets the current record's "porc_comp" value
 * @method Tabulado            setPorcCxs()    Sets the current record's "porc_cxs" value
 * @method Tabulado            setPorcOtro()   Sets the current record's "porc_otro" value
 * @method Tabulado            setRevisado()   Sets the current record's "revisado" value
 * @method Tabulado            setTrasnfe()    Sets the current record's "trasnfe" value
 * @method Tabulado            setRowguid()    Sets the current record's "rowguid" value
 * @method Tabulado            setArt()        Sets the current record's "Art" collection
 * @method Tabulado            setDocumCc()    Sets the current record's "DocumCc" collection
 * @method Tabulado            setDocumCp()    Sets the current record's "DocumCp" collection
 * @method Tabulado            setRengCac()    Sets the current record's "RengCac" collection
 * @method Tabulado            setRengDvc()    Sets the current record's "RengDvc" collection
 * @method Tabulado            setRengFac()    Sets the current record's "RengFac" collection
 * @method Tabulado            setRengNdd()    Sets the current record's "RengNdd" collection
 * @method Tabulado            setRengPed()    Sets the current record's "RengPed" collection
 * 
 * @package    gesser
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTabulado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tabulado');
        $this->hasColumn('tipo', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('descripcio', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('porc_vent', 'decimal', 12, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('porc_comp', 'decimal', 12, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('porc_cxs', 'decimal', 12, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('porc_otro', 'decimal', 12, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('revisado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('trasnfe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('rowguid', 'string', 36, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(newid())',
             'primary' => false,
             'autoincrement' => false,
             'length' => 36,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Art', array(
             'local' => 'tipo',
             'foreign' => 'tipo_imp'));

        $this->hasMany('DocumCc', array(
             'local' => 'tipo',
             'foreign' => 'tipo'));

        $this->hasMany('DocumCp', array(
             'local' => 'tipo',
             'foreign' => 'tipo'));

        $this->hasMany('RengCac', array(
             'local' => 'tipo',
             'foreign' => 'tipo_imp'));

        $this->hasMany('RengDvc', array(
             'local' => 'tipo',
             'foreign' => 'tipo_imp'));

        $this->hasMany('RengFac', array(
             'local' => 'tipo',
             'foreign' => 'tipo_imp'));

        $this->hasMany('RengNdd', array(
             'local' => 'tipo',
             'foreign' => 'tipo_imp'));

        $this->hasMany('RengPed', array(
             'local' => 'tipo',
             'foreign' => 'tipo_imp'));
    }
}