<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cuentas', 'profit');

/**
 * BaseCuentas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cod_cta
 * @property string $co_banco
 * @property string $num_cta
 * @property string $dis_cen
 * @property string $sucursal
 * @property string $cta_contab
 * @property string $telefono
 * @property timestamp $mes_ini
 * @property decimal $saldo_i
 * @property decimal $saldo_ic
 * @property decimal $saldo_a
 * @property decimal $saldo_c
 * @property string $moneda
 * @property string $campo1
 * @property string $campo2
 * @property string $campo3
 * @property string $campo4
 * @property string $co_us_in
 * @property timestamp $fe_us_in
 * @property string $co_us_mo
 * @property timestamp $fe_us_mo
 * @property string $co_us_el
 * @property timestamp $fe_us_el
 * @property string $revisado
 * @property string $trasnfe
 * @property string $co_sucu
 * @property string $rowguid
 * @property boolean $inactivo
 * @property timestamp $row_id
 * @property boolean $usa_chra
 * @property string $ejec_cu
 * @property string $direccion
 * @property string $email
 * @property decimal $saldo_co
 * @property string $tipo_cu
 * @property timestamp $fecini
 * @property timestamp $fec_chra
 * @property Bancos $Bancos
 * @property Doctrine_Collection $Chequeras
 * @property Doctrine_Collection $ConcAut
 * @property Doctrine_Collection $DepCaj
 * @property Doctrine_Collection $MovBan
 * 
 * @method string              getCodCta()     Returns the current record's "cod_cta" value
 * @method string              getCoBanco()    Returns the current record's "co_banco" value
 * @method string              getNumCta()     Returns the current record's "num_cta" value
 * @method string              getDisCen()     Returns the current record's "dis_cen" value
 * @method string              getSucursal()   Returns the current record's "sucursal" value
 * @method string              getCtaContab()  Returns the current record's "cta_contab" value
 * @method string              getTelefono()   Returns the current record's "telefono" value
 * @method timestamp           getMesIni()     Returns the current record's "mes_ini" value
 * @method decimal             getSaldoI()     Returns the current record's "saldo_i" value
 * @method decimal             getSaldoIc()    Returns the current record's "saldo_ic" value
 * @method decimal             getSaldoA()     Returns the current record's "saldo_a" value
 * @method decimal             getSaldoC()     Returns the current record's "saldo_c" value
 * @method string              getMoneda()     Returns the current record's "moneda" value
 * @method string              getCampo1()     Returns the current record's "campo1" value
 * @method string              getCampo2()     Returns the current record's "campo2" value
 * @method string              getCampo3()     Returns the current record's "campo3" value
 * @method string              getCampo4()     Returns the current record's "campo4" value
 * @method string              getCoUsIn()     Returns the current record's "co_us_in" value
 * @method timestamp           getFeUsIn()     Returns the current record's "fe_us_in" value
 * @method string              getCoUsMo()     Returns the current record's "co_us_mo" value
 * @method timestamp           getFeUsMo()     Returns the current record's "fe_us_mo" value
 * @method string              getCoUsEl()     Returns the current record's "co_us_el" value
 * @method timestamp           getFeUsEl()     Returns the current record's "fe_us_el" value
 * @method string              getRevisado()   Returns the current record's "revisado" value
 * @method string              getTrasnfe()    Returns the current record's "trasnfe" value
 * @method string              getCoSucu()     Returns the current record's "co_sucu" value
 * @method string              getRowguid()    Returns the current record's "rowguid" value
 * @method boolean             getInactivo()   Returns the current record's "inactivo" value
 * @method timestamp           getRowId()      Returns the current record's "row_id" value
 * @method boolean             getUsaChra()    Returns the current record's "usa_chra" value
 * @method string              getEjecCu()     Returns the current record's "ejec_cu" value
 * @method string              getDireccion()  Returns the current record's "direccion" value
 * @method string              getEmail()      Returns the current record's "email" value
 * @method decimal             getSaldoCo()    Returns the current record's "saldo_co" value
 * @method string              getTipoCu()     Returns the current record's "tipo_cu" value
 * @method timestamp           getFecini()     Returns the current record's "fecini" value
 * @method timestamp           getFecChra()    Returns the current record's "fec_chra" value
 * @method Bancos              getBancos()     Returns the current record's "Bancos" value
 * @method Doctrine_Collection getChequeras()  Returns the current record's "Chequeras" collection
 * @method Doctrine_Collection getConcAut()    Returns the current record's "ConcAut" collection
 * @method Doctrine_Collection getDepCaj()     Returns the current record's "DepCaj" collection
 * @method Doctrine_Collection getMovBan()     Returns the current record's "MovBan" collection
 * @method Cuentas             setCodCta()     Sets the current record's "cod_cta" value
 * @method Cuentas             setCoBanco()    Sets the current record's "co_banco" value
 * @method Cuentas             setNumCta()     Sets the current record's "num_cta" value
 * @method Cuentas             setDisCen()     Sets the current record's "dis_cen" value
 * @method Cuentas             setSucursal()   Sets the current record's "sucursal" value
 * @method Cuentas             setCtaContab()  Sets the current record's "cta_contab" value
 * @method Cuentas             setTelefono()   Sets the current record's "telefono" value
 * @method Cuentas             setMesIni()     Sets the current record's "mes_ini" value
 * @method Cuentas             setSaldoI()     Sets the current record's "saldo_i" value
 * @method Cuentas             setSaldoIc()    Sets the current record's "saldo_ic" value
 * @method Cuentas             setSaldoA()     Sets the current record's "saldo_a" value
 * @method Cuentas             setSaldoC()     Sets the current record's "saldo_c" value
 * @method Cuentas             setMoneda()     Sets the current record's "moneda" value
 * @method Cuentas             setCampo1()     Sets the current record's "campo1" value
 * @method Cuentas             setCampo2()     Sets the current record's "campo2" value
 * @method Cuentas             setCampo3()     Sets the current record's "campo3" value
 * @method Cuentas             setCampo4()     Sets the current record's "campo4" value
 * @method Cuentas             setCoUsIn()     Sets the current record's "co_us_in" value
 * @method Cuentas             setFeUsIn()     Sets the current record's "fe_us_in" value
 * @method Cuentas             setCoUsMo()     Sets the current record's "co_us_mo" value
 * @method Cuentas             setFeUsMo()     Sets the current record's "fe_us_mo" value
 * @method Cuentas             setCoUsEl()     Sets the current record's "co_us_el" value
 * @method Cuentas             setFeUsEl()     Sets the current record's "fe_us_el" value
 * @method Cuentas             setRevisado()   Sets the current record's "revisado" value
 * @method Cuentas             setTrasnfe()    Sets the current record's "trasnfe" value
 * @method Cuentas             setCoSucu()     Sets the current record's "co_sucu" value
 * @method Cuentas             setRowguid()    Sets the current record's "rowguid" value
 * @method Cuentas             setInactivo()   Sets the current record's "inactivo" value
 * @method Cuentas             setRowId()      Sets the current record's "row_id" value
 * @method Cuentas             setUsaChra()    Sets the current record's "usa_chra" value
 * @method Cuentas             setEjecCu()     Sets the current record's "ejec_cu" value
 * @method Cuentas             setDireccion()  Sets the current record's "direccion" value
 * @method Cuentas             setEmail()      Sets the current record's "email" value
 * @method Cuentas             setSaldoCo()    Sets the current record's "saldo_co" value
 * @method Cuentas             setTipoCu()     Sets the current record's "tipo_cu" value
 * @method Cuentas             setFecini()     Sets the current record's "fecini" value
 * @method Cuentas             setFecChra()    Sets the current record's "fec_chra" value
 * @method Cuentas             setBancos()     Sets the current record's "Bancos" value
 * @method Cuentas             setChequeras()  Sets the current record's "Chequeras" collection
 * @method Cuentas             setConcAut()    Sets the current record's "ConcAut" collection
 * @method Cuentas             setDepCaj()     Sets the current record's "DepCaj" collection
 * @method Cuentas             setMovBan()     Sets the current record's "MovBan" collection
 * 
 * @package    gesser
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCuentas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cuentas');
        $this->hasColumn('cod_cta', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('co_banco', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('num_cta', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('dis_cen', 'string', 2147483647, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('sucursal', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('cta_contab', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('telefono', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('mes_ini', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(convert(varchar(10),getdate(),104))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('saldo_i', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('saldo_ic', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('saldo_a', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('saldo_c', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('moneda', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('campo1', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo2', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo3', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo4', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('co_us_in', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_in', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_mo', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_mo', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_el', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_el', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('revisado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('trasnfe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('co_sucu', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('rowguid', 'string', 36, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(newid())',
             'primary' => false,
             'autoincrement' => false,
             'length' => 36,
             ));
        $this->hasColumn('inactivo', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('row_id', 'timestamp', 8, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('usa_chra', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('ejec_cu', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('direccion', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 120,
             ));
        $this->hasColumn('email', 'string', 40, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('saldo_co', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('tipo_cu', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('fecini', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(convert(datetime,floor(convert(float,getdate()))))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('fec_chra', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(convert(datetime,floor(convert(float,getdate()))))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Bancos', array(
             'local' => 'co_banco',
             'foreign' => 'co_ban'));

        $this->hasMany('Chequeras', array(
             'local' => 'cod_cta',
             'foreign' => 'cod_cta'));

        $this->hasMany('ConcAut', array(
             'local' => 'cod_cta',
             'foreign' => 'cod_cta'));

        $this->hasMany('DepCaj', array(
             'local' => 'cod_cta',
             'foreign' => 'cod_cta'));

        $this->hasMany('MovBan', array(
             'local' => 'cod_cta',
             'foreign' => 'codigo'));
    }
}