<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SubLin', 'profit');

/**
 * BaseSubLin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $co_subl
 * @property string $subl_des
 * @property string $co_lin
 * @property string $campo1
 * @property string $campo2
 * @property string $campo3
 * @property string $campo4
 * @property string $co_us_in
 * @property timestamp $fe_us_in
 * @property string $co_us_mo
 * @property timestamp $fe_us_mo
 * @property string $co_us_el
 * @property timestamp $fe_us_el
 * @property string $revisado
 * @property string $trasnfe
 * @property string $co_sucu
 * @property string $rowguid
 * @property string $co_imun
 * @property string $co_reten
 * @property string $i_subl_des
 * @property boolean $movil
 * @property LinArt $LinArt
 * @property Doctrine_Collection $Art
 * @property Doctrine_Collection $Art_4
 * 
 * @method string              getCoSubl()     Returns the current record's "co_subl" value
 * @method string              getSublDes()    Returns the current record's "subl_des" value
 * @method string              getCoLin()      Returns the current record's "co_lin" value
 * @method string              getCampo1()     Returns the current record's "campo1" value
 * @method string              getCampo2()     Returns the current record's "campo2" value
 * @method string              getCampo3()     Returns the current record's "campo3" value
 * @method string              getCampo4()     Returns the current record's "campo4" value
 * @method string              getCoUsIn()     Returns the current record's "co_us_in" value
 * @method timestamp           getFeUsIn()     Returns the current record's "fe_us_in" value
 * @method string              getCoUsMo()     Returns the current record's "co_us_mo" value
 * @method timestamp           getFeUsMo()     Returns the current record's "fe_us_mo" value
 * @method string              getCoUsEl()     Returns the current record's "co_us_el" value
 * @method timestamp           getFeUsEl()     Returns the current record's "fe_us_el" value
 * @method string              getRevisado()   Returns the current record's "revisado" value
 * @method string              getTrasnfe()    Returns the current record's "trasnfe" value
 * @method string              getCoSucu()     Returns the current record's "co_sucu" value
 * @method string              getRowguid()    Returns the current record's "rowguid" value
 * @method string              getCoImun()     Returns the current record's "co_imun" value
 * @method string              getCoReten()    Returns the current record's "co_reten" value
 * @method string              getISublDes()   Returns the current record's "i_subl_des" value
 * @method boolean             getMovil()      Returns the current record's "movil" value
 * @method LinArt              getLinArt()     Returns the current record's "LinArt" value
 * @method Doctrine_Collection getArt()        Returns the current record's "Art" collection
 * @method Doctrine_Collection getArt4()       Returns the current record's "Art_4" collection
 * @method SubLin              setCoSubl()     Sets the current record's "co_subl" value
 * @method SubLin              setSublDes()    Sets the current record's "subl_des" value
 * @method SubLin              setCoLin()      Sets the current record's "co_lin" value
 * @method SubLin              setCampo1()     Sets the current record's "campo1" value
 * @method SubLin              setCampo2()     Sets the current record's "campo2" value
 * @method SubLin              setCampo3()     Sets the current record's "campo3" value
 * @method SubLin              setCampo4()     Sets the current record's "campo4" value
 * @method SubLin              setCoUsIn()     Sets the current record's "co_us_in" value
 * @method SubLin              setFeUsIn()     Sets the current record's "fe_us_in" value
 * @method SubLin              setCoUsMo()     Sets the current record's "co_us_mo" value
 * @method SubLin              setFeUsMo()     Sets the current record's "fe_us_mo" value
 * @method SubLin              setCoUsEl()     Sets the current record's "co_us_el" value
 * @method SubLin              setFeUsEl()     Sets the current record's "fe_us_el" value
 * @method SubLin              setRevisado()   Sets the current record's "revisado" value
 * @method SubLin              setTrasnfe()    Sets the current record's "trasnfe" value
 * @method SubLin              setCoSucu()     Sets the current record's "co_sucu" value
 * @method SubLin              setRowguid()    Sets the current record's "rowguid" value
 * @method SubLin              setCoImun()     Sets the current record's "co_imun" value
 * @method SubLin              setCoReten()    Sets the current record's "co_reten" value
 * @method SubLin              setISublDes()   Sets the current record's "i_subl_des" value
 * @method SubLin              setMovil()      Sets the current record's "movil" value
 * @method SubLin              setLinArt()     Sets the current record's "LinArt" value
 * @method SubLin              setArt()        Sets the current record's "Art" collection
 * @method SubLin              setArt4()       Sets the current record's "Art_4" collection
 * 
 * @package    gesser
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubLin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_lin');
        $this->hasColumn('co_subl', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('subl_des', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('co_lin', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('campo1', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo2', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo3', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo4', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('co_us_in', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_in', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_mo', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_mo', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_el', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_el', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('revisado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('trasnfe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('co_sucu', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('rowguid', 'string', 36, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(newid())',
             'primary' => false,
             'autoincrement' => false,
             'length' => 36,
             ));
        $this->hasColumn('co_imun', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('co_reten', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('i_subl_des', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('movil', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LinArt', array(
             'local' => 'co_lin',
             'foreign' => 'co_lin'));

        $this->hasMany('Art', array(
             'local' => 'co_lin',
             'foreign' => 'co_lin'));

        $this->hasMany('Art as Art_4', array(
             'local' => 'co_subl',
             'foreign' => 'co_subl'));
    }
}