<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Spimplosion', 'profit');

/**
 * BaseSpimplosion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $inp_num
 * @property timestamp $fecha
 * @property string $alm_orig
 * @property string $motivo_glo
 * @property string $co_art
 * @property string $art_des
 * @property string $campo1
 * @property string $campo2
 * @property string $campo3
 * @property string $campo4
 * @property string $campo5
 * @property string $campo6
 * @property string $campo7
 * @property string $campo8
 * @property string $co_us_in
 * @property timestamp $fe_us_in
 * @property string $co_us_mo
 * @property timestamp $fe_us_mo
 * @property string $co_us_el
 * @property timestamp $fe_us_el
 * @property string $revisado
 * @property string $impnfe
 * @property string $co_sucu
 * @property string $comentario
 * @property decimal $maxima
 * @property string $unidad
 * @property string $rowguid
 * @property string $trasnfe
 * @property integer $cod_ced
 * @property string $co_alma
 * @property Doctrine_Collection $RengImp
 * 
 * @method integer             getInpNum()     Returns the current record's "inp_num" value
 * @method timestamp           getFecha()      Returns the current record's "fecha" value
 * @method string              getAlmOrig()    Returns the current record's "alm_orig" value
 * @method string              getMotivoGlo()  Returns the current record's "motivo_glo" value
 * @method string              getCoArt()      Returns the current record's "co_art" value
 * @method string              getArtDes()     Returns the current record's "art_des" value
 * @method string              getCampo1()     Returns the current record's "campo1" value
 * @method string              getCampo2()     Returns the current record's "campo2" value
 * @method string              getCampo3()     Returns the current record's "campo3" value
 * @method string              getCampo4()     Returns the current record's "campo4" value
 * @method string              getCampo5()     Returns the current record's "campo5" value
 * @method string              getCampo6()     Returns the current record's "campo6" value
 * @method string              getCampo7()     Returns the current record's "campo7" value
 * @method string              getCampo8()     Returns the current record's "campo8" value
 * @method string              getCoUsIn()     Returns the current record's "co_us_in" value
 * @method timestamp           getFeUsIn()     Returns the current record's "fe_us_in" value
 * @method string              getCoUsMo()     Returns the current record's "co_us_mo" value
 * @method timestamp           getFeUsMo()     Returns the current record's "fe_us_mo" value
 * @method string              getCoUsEl()     Returns the current record's "co_us_el" value
 * @method timestamp           getFeUsEl()     Returns the current record's "fe_us_el" value
 * @method string              getRevisado()   Returns the current record's "revisado" value
 * @method string              getImpnfe()     Returns the current record's "impnfe" value
 * @method string              getCoSucu()     Returns the current record's "co_sucu" value
 * @method string              getComentario() Returns the current record's "comentario" value
 * @method decimal             getMaxima()     Returns the current record's "maxima" value
 * @method string              getUnidad()     Returns the current record's "unidad" value
 * @method string              getRowguid()    Returns the current record's "rowguid" value
 * @method string              getTrasnfe()    Returns the current record's "trasnfe" value
 * @method integer             getCodCed()     Returns the current record's "cod_ced" value
 * @method string              getCoAlma()     Returns the current record's "co_alma" value
 * @method Doctrine_Collection getRengImp()    Returns the current record's "RengImp" collection
 * @method Spimplosion         setInpNum()     Sets the current record's "inp_num" value
 * @method Spimplosion         setFecha()      Sets the current record's "fecha" value
 * @method Spimplosion         setAlmOrig()    Sets the current record's "alm_orig" value
 * @method Spimplosion         setMotivoGlo()  Sets the current record's "motivo_glo" value
 * @method Spimplosion         setCoArt()      Sets the current record's "co_art" value
 * @method Spimplosion         setArtDes()     Sets the current record's "art_des" value
 * @method Spimplosion         setCampo1()     Sets the current record's "campo1" value
 * @method Spimplosion         setCampo2()     Sets the current record's "campo2" value
 * @method Spimplosion         setCampo3()     Sets the current record's "campo3" value
 * @method Spimplosion         setCampo4()     Sets the current record's "campo4" value
 * @method Spimplosion         setCampo5()     Sets the current record's "campo5" value
 * @method Spimplosion         setCampo6()     Sets the current record's "campo6" value
 * @method Spimplosion         setCampo7()     Sets the current record's "campo7" value
 * @method Spimplosion         setCampo8()     Sets the current record's "campo8" value
 * @method Spimplosion         setCoUsIn()     Sets the current record's "co_us_in" value
 * @method Spimplosion         setFeUsIn()     Sets the current record's "fe_us_in" value
 * @method Spimplosion         setCoUsMo()     Sets the current record's "co_us_mo" value
 * @method Spimplosion         setFeUsMo()     Sets the current record's "fe_us_mo" value
 * @method Spimplosion         setCoUsEl()     Sets the current record's "co_us_el" value
 * @method Spimplosion         setFeUsEl()     Sets the current record's "fe_us_el" value
 * @method Spimplosion         setRevisado()   Sets the current record's "revisado" value
 * @method Spimplosion         setImpnfe()     Sets the current record's "impnfe" value
 * @method Spimplosion         setCoSucu()     Sets the current record's "co_sucu" value
 * @method Spimplosion         setComentario() Sets the current record's "comentario" value
 * @method Spimplosion         setMaxima()     Sets the current record's "maxima" value
 * @method Spimplosion         setUnidad()     Sets the current record's "unidad" value
 * @method Spimplosion         setRowguid()    Sets the current record's "rowguid" value
 * @method Spimplosion         setTrasnfe()    Sets the current record's "trasnfe" value
 * @method Spimplosion         setCodCed()     Sets the current record's "cod_ced" value
 * @method Spimplosion         setCoAlma()     Sets the current record's "co_alma" value
 * @method Spimplosion         setRengImp()    Sets the current record's "RengImp" collection
 * 
 * @package    gesser
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpimplosion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('spimplosion');
        $this->hasColumn('inp_num', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(convert(varchar(10),getdate(),104))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('alm_orig', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('motivo_glo', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('co_art', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('art_des', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo1', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo2', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo3', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo4', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo5', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo6', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo7', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('campo8', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('co_us_in', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_in', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_mo', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_mo', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('co_us_el', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fe_us_el', 'timestamp', 16, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(dateadd(millisecond,(((-datepart(millisecond,getdate())))),getdate()))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('revisado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('impnfe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('co_sucu', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('comentario', 'string', 2147483647, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('maxima', 'decimal', 20, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('unidad', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('rowguid', 'string', 36, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(newid())',
             'primary' => false,
             'autoincrement' => false,
             'length' => 36,
             ));
        $this->hasColumn('trasnfe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('cod_ced', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('co_alma', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(space(1))',
             'primary' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RengImp', array(
             'local' => 'inp_num',
             'foreign' => 'inp_num'));
    }
}