# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Gestión Servicios al Cliente
    description:  Gestion de servicios al cliente en Agencia Royal 33 C.A.
    keywords:     gestion, servicios, agencia, royal, clientes
    language:     es
    robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    [jquery-1.6.4.min.js, presupuestos.js]

  has_layout:     true
  layout:         layout_base
