dev:
  profit:
    param:
      classname: DebugPDO
  gesser:
    param:
      classname: DebugPDO
test:
  profit:
    param:
      classname: DebugPDO
  gesser:
    param:
      classname: DebugPDO
all:
  profit:
    class: sfDoctrineDatabase
    param:
      phptype:   mssql
      classname: MssqlPropelPDO
      dsn:       dblib:host=10.10.1.100;dbname=RECADMAR
      username:  gescob
      password:  797965
      encoding:
      pooling:   true
  gesser:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql://root:123456@localhost/servicios'
      username: root
      password: 123456
