<?php

/**
 * Clientes form base class.
 *
 * @method Clientes getObject() Returns the current form's model object
 *
 * @package    gesser
 * @subpackage form
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 29553 2010-05-20 14:33:00Z Kris.Wallsmith $
 */
abstract class BaseClientesForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'co_cli'     => new sfWidgetFormInputHidden(),
      'tipo'       => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('TipoCli'), 'add_empty' => false)),
      'cli_des'    => new sfWidgetFormInputText(),
      'direc1'     => new sfWidgetFormTextarea(),
      'direc2'     => new sfWidgetFormInputText(),
      'telefonos'  => new sfWidgetFormInputText(),
      'fax'        => new sfWidgetFormInputText(),
      'inactivo'   => new sfWidgetFormInputCheckbox(),
      'comentario' => new sfWidgetFormTextarea(),
      'respons'    => new sfWidgetFormInputText(),
      'fecha_reg'  => new sfWidgetFormDateTime(),
      'puntaje'    => new sfWidgetFormInputText(),
      'saldo'      => new sfWidgetFormInputText(),
      'saldo_ini'  => new sfWidgetFormInputText(),
      'fac_ult_ve' => new sfWidgetFormInputText(),
      'fec_ult_ve' => new sfWidgetFormDateTime(),
      'net_ult_ve' => new sfWidgetFormInputText(),
      'mont_cre'   => new sfWidgetFormInputText(),
      'plaz_pag'   => new sfWidgetFormInputText(),
      'desc_ppago' => new sfWidgetFormInputText(),
      'co_zon'     => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Zona'), 'add_empty' => false)),
      'co_seg'     => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Segmento'), 'add_empty' => false)),
      'co_ven'     => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Vendedor'), 'add_empty' => false)),
      'desc_glob'  => new sfWidgetFormInputText(),
      'horar_caja' => new sfWidgetFormInputText(),
      'frecu_vist' => new sfWidgetFormInputText(),
      'lunes'      => new sfWidgetFormInputCheckbox(),
      'martes'     => new sfWidgetFormInputCheckbox(),
      'miercoles'  => new sfWidgetFormInputCheckbox(),
      'jueves'     => new sfWidgetFormInputCheckbox(),
      'viernes'    => new sfWidgetFormInputCheckbox(),
      'sabado'     => new sfWidgetFormInputCheckbox(),
      'domingo'    => new sfWidgetFormInputCheckbox(),
      'dir_ent2'   => new sfWidgetFormTextarea(),
      'tipo_iva'   => new sfWidgetFormInputText(),
      'iva'        => new sfWidgetFormInputText(),
      'rif'        => new sfWidgetFormInputText(),
      'contribu'   => new sfWidgetFormInputCheckbox(),
      'dis_cen'    => new sfWidgetFormTextarea(),
      'nit'        => new sfWidgetFormInputText(),
      'email'      => new sfWidgetFormInputText(),
      'co_ingr'    => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CtaIngr'), 'add_empty' => false)),
      'campo1'     => new sfWidgetFormInputText(),
      'campo2'     => new sfWidgetFormInputText(),
      'campo3'     => new sfWidgetFormInputText(),
      'campo4'     => new sfWidgetFormInputText(),
      'campo5'     => new sfWidgetFormInputText(),
      'campo6'     => new sfWidgetFormInputText(),
      'campo7'     => new sfWidgetFormInputText(),
      'campo8'     => new sfWidgetFormInputText(),
      'co_us_in'   => new sfWidgetFormInputText(),
      'fe_us_in'   => new sfWidgetFormDateTime(),
      'co_us_mo'   => new sfWidgetFormInputText(),
      'fe_us_mo'   => new sfWidgetFormDateTime(),
      'co_us_el'   => new sfWidgetFormInputText(),
      'fe_us_el'   => new sfWidgetFormDateTime(),
      'revisado'   => new sfWidgetFormInputText(),
      'trasnfe'    => new sfWidgetFormInputText(),
      'co_sucu'    => new sfWidgetFormInputText(),
      'rowguid'    => new sfWidgetFormInputText(),
      'juridico'   => new sfWidgetFormInputCheckbox(),
      'tipo_adi'   => new sfWidgetFormInputText(),
      'matriz'     => new sfWidgetFormInputText(),
      'co_tab'     => new sfWidgetFormInputText(),
      'tipo_per'   => new sfWidgetFormInputText(),
      'serialp'    => new sfWidgetFormInputText(),
      'valido'     => new sfWidgetFormInputCheckbox(),
      'row_id'     => new sfWidgetFormDateTime(),
      'estado'     => new sfWidgetFormInputText(),
      'id'         => new sfWidgetFormInputText(),
      'co_pais'    => new sfWidgetFormInputText(),
      'ciudad'     => new sfWidgetFormInputText(),
      'zip'        => new sfWidgetFormInputText(),
      'login'      => new sfWidgetFormInputText(),
      'password'   => new sfWidgetFormInputText(),
      'website'    => new sfWidgetFormInputText(),
      'salestax'   => new sfWidgetFormInputText(),
      'contribu_e' => new sfWidgetFormInputCheckbox(),
      'porc_esp'   => new sfWidgetFormInputText(),
      'sincredito' => new sfWidgetFormInputCheckbox(),
    ));

    $this->setValidators(array(
      'co_cli'     => new sfValidatorChoice(array('choices' => array($this->getObject()->get('co_cli')), 'empty_value' => $this->getObject()->get('co_cli'), 'required' => false)),
      'tipo'       => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('TipoCli'), 'required' => false)),
      'cli_des'    => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'direc1'     => new sfValidatorString(array('max_length' => 2147483647, 'required' => false)),
      'direc2'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'telefonos'  => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'fax'        => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'inactivo'   => new sfValidatorBoolean(array('required' => false)),
      'comentario' => new sfValidatorString(array('max_length' => 2147483647, 'required' => false)),
      'respons'    => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'fecha_reg'  => new sfValidatorDateTime(array('required' => false)),
      'puntaje'    => new sfValidatorInteger(array('required' => false)),
      'saldo'      => new sfValidatorNumber(array('required' => false)),
      'saldo_ini'  => new sfValidatorNumber(array('required' => false)),
      'fac_ult_ve' => new sfValidatorInteger(array('required' => false)),
      'fec_ult_ve' => new sfValidatorDateTime(array('required' => false)),
      'net_ult_ve' => new sfValidatorNumber(array('required' => false)),
      'mont_cre'   => new sfValidatorNumber(array('required' => false)),
      'plaz_pag'   => new sfValidatorInteger(array('required' => false)),
      'desc_ppago' => new sfValidatorNumber(array('required' => false)),
      'co_zon'     => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Zona'), 'required' => false)),
      'co_seg'     => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Segmento'), 'required' => false)),
      'co_ven'     => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Vendedor'), 'required' => false)),
      'desc_glob'  => new sfValidatorNumber(array('required' => false)),
      'horar_caja' => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'frecu_vist' => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'lunes'      => new sfValidatorBoolean(array('required' => false)),
      'martes'     => new sfValidatorBoolean(array('required' => false)),
      'miercoles'  => new sfValidatorBoolean(array('required' => false)),
      'jueves'     => new sfValidatorBoolean(array('required' => false)),
      'viernes'    => new sfValidatorBoolean(array('required' => false)),
      'sabado'     => new sfValidatorBoolean(array('required' => false)),
      'domingo'    => new sfValidatorBoolean(array('required' => false)),
      'dir_ent2'   => new sfValidatorString(array('max_length' => 2147483647, 'required' => false)),
      'tipo_iva'   => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'iva'        => new sfValidatorNumber(array('required' => false)),
      'rif'        => new sfValidatorString(array('max_length' => 18, 'required' => false)),
      'contribu'   => new sfValidatorBoolean(array('required' => false)),
      'dis_cen'    => new sfValidatorString(array('max_length' => 2147483647, 'required' => false)),
      'nit'        => new sfValidatorString(array('max_length' => 18, 'required' => false)),
      'email'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'co_ingr'    => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('CtaIngr'), 'required' => false)),
      'campo1'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo2'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo3'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo4'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo5'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo6'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo7'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo8'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'co_us_in'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_in'   => new sfValidatorDateTime(array('required' => false)),
      'co_us_mo'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_mo'   => new sfValidatorDateTime(array('required' => false)),
      'co_us_el'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_el'   => new sfValidatorDateTime(array('required' => false)),
      'revisado'   => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'trasnfe'    => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'co_sucu'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'rowguid'    => new sfValidatorString(array('max_length' => 36, 'required' => false)),
      'juridico'   => new sfValidatorBoolean(array('required' => false)),
      'tipo_adi'   => new sfValidatorNumber(array('required' => false)),
      'matriz'     => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'co_tab'     => new sfValidatorInteger(array('required' => false)),
      'tipo_per'   => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'serialp'    => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'valido'     => new sfValidatorBoolean(array('required' => false)),
      'row_id'     => new sfValidatorDateTime(),
      'estado'     => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'id'         => new sfValidatorInteger(array('required' => false)),
      'co_pais'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'ciudad'     => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'zip'        => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'login'      => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'password'   => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'website'    => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'salestax'   => new sfValidatorString(array('max_length' => 8, 'required' => false)),
      'contribu_e' => new sfValidatorBoolean(array('required' => false)),
      'porc_esp'   => new sfValidatorNumber(array('required' => false)),
      'sincredito' => new sfValidatorBoolean(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('clientes[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Clientes';
  }

}
