<?php

/**
 * Ambclpro form base class.
 *
 * @method Ambclpro getObject() Returns the current form's model object
 *
 * @package    gesser
 * @subpackage form
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 29553 2010-05-20 14:33:00Z Kris.Wallsmith $
 */
abstract class BaseAmbclproForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'amb_usua'   => new sfWidgetFormInputHidden(),
      'tipo_cyp'   => new sfWidgetFormInputHidden(),
      'co_cliv'    => new sfWidgetFormInputCheckbox(),
      'tipod'      => new sfWidgetFormInputCheckbox(),
      'tipov'      => new sfWidgetFormInputCheckbox(),
      'tipo'       => new sfWidgetFormInputText(),
      'cli_desv'   => new sfWidgetFormInputCheckbox(),
      'direc1v'    => new sfWidgetFormInputCheckbox(),
      'direc2v'    => new sfWidgetFormInputCheckbox(),
      'telefonosv' => new sfWidgetFormInputCheckbox(),
      'faxv'       => new sfWidgetFormInputCheckbox(),
      'inactivov'  => new sfWidgetFormInputCheckbox(),
      'comentariv' => new sfWidgetFormInputCheckbox(),
      'responsv'   => new sfWidgetFormInputCheckbox(),
      'fecha_regv' => new sfWidgetFormInputCheckbox(),
      'saldov'     => new sfWidgetFormInputCheckbox(),
      'mont_crev'  => new sfWidgetFormInputCheckbox(),
      'plaz_pagv'  => new sfWidgetFormInputCheckbox(),
      'descppagov' => new sfWidgetFormInputCheckbox(),
      'con_zond'   => new sfWidgetFormInputCheckbox(),
      'co_zonv'    => new sfWidgetFormInputCheckbox(),
      'co_zon'     => new sfWidgetFormInputText(),
      'co_segd'    => new sfWidgetFormInputCheckbox(),
      'co_segv'    => new sfWidgetFormInputCheckbox(),
      'co_seg'     => new sfWidgetFormInputText(),
      'con_vend'   => new sfWidgetFormInputCheckbox(),
      'co_venv'    => new sfWidgetFormInputCheckbox(),
      'co_ven'     => new sfWidgetFormInputText(),
      'desc_globv' => new sfWidgetFormInputCheckbox(),
      'horarcajav' => new sfWidgetFormInputCheckbox(),
      'frecuvistv' => new sfWidgetFormInputCheckbox(),
      'lunesv'     => new sfWidgetFormInputCheckbox(),
      'martesv'    => new sfWidgetFormInputCheckbox(),
      'miercolesv' => new sfWidgetFormInputCheckbox(),
      'juevesv'    => new sfWidgetFormInputCheckbox(),
      'viernesv'   => new sfWidgetFormInputCheckbox(),
      'sabadov'    => new sfWidgetFormInputCheckbox(),
      'domingov'   => new sfWidgetFormInputCheckbox(),
      'dir_ent2v'  => new sfWidgetFormInputCheckbox(),
      'rifv'       => new sfWidgetFormInputCheckbox(),
      'contribuv'  => new sfWidgetFormInputCheckbox(),
      'dis_cenv'   => new sfWidgetFormInputCheckbox(),
      'nitv'       => new sfWidgetFormInputCheckbox(),
      'emailv'     => new sfWidgetFormInputCheckbox(),
      'co_ingrd'   => new sfWidgetFormInputCheckbox(),
      'co_ingrv'   => new sfWidgetFormInputCheckbox(),
      'co_ingr'    => new sfWidgetFormInputText(),
      'tipo_perd'  => new sfWidgetFormInputCheckbox(),
      'tipo_perv'  => new sfWidgetFormInputCheckbox(),
      'tipo_per'   => new sfWidgetFormInputText(),
      'co_tabv'    => new sfWidgetFormInputCheckbox(),
      'tipo_adid'  => new sfWidgetFormInputCheckbox(),
      'tipo_adiv'  => new sfWidgetFormInputCheckbox(),
      'tipo_adi'   => new sfWidgetFormInputText(),
      'matrizd'    => new sfWidgetFormInputCheckbox(),
      'matrizv'    => new sfWidgetFormInputCheckbox(),
      'matriz'     => new sfWidgetFormInputText(),
      'campo1'     => new sfWidgetFormInputText(),
      'campo2'     => new sfWidgetFormInputText(),
      'campo3'     => new sfWidgetFormInputText(),
      'campo4'     => new sfWidgetFormInputText(),
      'campo5'     => new sfWidgetFormInputText(),
      'campo6'     => new sfWidgetFormInputText(),
      'campo7'     => new sfWidgetFormInputText(),
      'campo8'     => new sfWidgetFormInputText(),
      'co_us_in'   => new sfWidgetFormInputText(),
      'fe_us_in'   => new sfWidgetFormDateTime(),
      'co_us_mo'   => new sfWidgetFormInputText(),
      'fe_us_mo'   => new sfWidgetFormDateTime(),
      'co_us_el'   => new sfWidgetFormInputText(),
      'fe_us_el'   => new sfWidgetFormDateTime(),
      'revisado'   => new sfWidgetFormInputText(),
      'trasnfe'    => new sfWidgetFormInputText(),
      'co_sucu'    => new sfWidgetFormInputText(),
      'serialp'    => new sfWidgetFormInputText(),
      'valido'     => new sfWidgetFormInputCheckbox(),
      'rowguid'    => new sfWidgetFormInputText(),
      'loginv'     => new sfWidgetFormInputCheckbox(),
      'passwordv'  => new sfWidgetFormInputCheckbox(),
      'estadov'    => new sfWidgetFormInputCheckbox(),
      'vpasswordv' => new sfWidgetFormInputCheckbox(),
      'co_paisv'   => new sfWidgetFormInputCheckbox(),
      'co_paisd'   => new sfWidgetFormInputCheckbox(),
      'co_pais'    => new sfWidgetFormInputText(),
      'zipv'       => new sfWidgetFormInputCheckbox(),
      'ciudadv'    => new sfWidgetFormInputCheckbox(),
      'taxidv'     => new sfWidgetFormInputCheckbox(),
      'formtypev'  => new sfWidgetFormInputCheckbox(),
      'formtyped'  => new sfWidgetFormInputCheckbox(),
      'formtype'   => new sfWidgetFormInputText(),
      'websitev'   => new sfWidgetFormInputCheckbox(),
      'bwebsitev'  => new sfWidgetFormInputCheckbox(),
      'bemailv'    => new sfWidgetFormInputCheckbox(),
      'salestaxv'  => new sfWidgetFormInputCheckbox(),
      'salestaxd'  => new sfWidgetFormInputCheckbox(),
      'salestax'   => new sfWidgetFormInputText(),
    ));

    $this->setValidators(array(
      'amb_usua'   => new sfValidatorChoice(array('choices' => array($this->getObject()->get('amb_usua')), 'empty_value' => $this->getObject()->get('amb_usua'), 'required' => false)),
      'tipo_cyp'   => new sfValidatorChoice(array('choices' => array($this->getObject()->get('tipo_cyp')), 'empty_value' => $this->getObject()->get('tipo_cyp'), 'required' => false)),
      'co_cliv'    => new sfValidatorBoolean(array('required' => false)),
      'tipod'      => new sfValidatorBoolean(array('required' => false)),
      'tipov'      => new sfValidatorBoolean(array('required' => false)),
      'tipo'       => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'cli_desv'   => new sfValidatorBoolean(array('required' => false)),
      'direc1v'    => new sfValidatorBoolean(array('required' => false)),
      'direc2v'    => new sfValidatorBoolean(array('required' => false)),
      'telefonosv' => new sfValidatorBoolean(array('required' => false)),
      'faxv'       => new sfValidatorBoolean(array('required' => false)),
      'inactivov'  => new sfValidatorBoolean(array('required' => false)),
      'comentariv' => new sfValidatorBoolean(array('required' => false)),
      'responsv'   => new sfValidatorBoolean(array('required' => false)),
      'fecha_regv' => new sfValidatorBoolean(array('required' => false)),
      'saldov'     => new sfValidatorBoolean(array('required' => false)),
      'mont_crev'  => new sfValidatorBoolean(array('required' => false)),
      'plaz_pagv'  => new sfValidatorBoolean(array('required' => false)),
      'descppagov' => new sfValidatorBoolean(array('required' => false)),
      'con_zond'   => new sfValidatorBoolean(array('required' => false)),
      'co_zonv'    => new sfValidatorBoolean(array('required' => false)),
      'co_zon'     => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'co_segd'    => new sfValidatorBoolean(array('required' => false)),
      'co_segv'    => new sfValidatorBoolean(array('required' => false)),
      'co_seg'     => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'con_vend'   => new sfValidatorBoolean(array('required' => false)),
      'co_venv'    => new sfValidatorBoolean(array('required' => false)),
      'co_ven'     => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'desc_globv' => new sfValidatorBoolean(array('required' => false)),
      'horarcajav' => new sfValidatorBoolean(array('required' => false)),
      'frecuvistv' => new sfValidatorBoolean(array('required' => false)),
      'lunesv'     => new sfValidatorBoolean(array('required' => false)),
      'martesv'    => new sfValidatorBoolean(array('required' => false)),
      'miercolesv' => new sfValidatorBoolean(array('required' => false)),
      'juevesv'    => new sfValidatorBoolean(array('required' => false)),
      'viernesv'   => new sfValidatorBoolean(array('required' => false)),
      'sabadov'    => new sfValidatorBoolean(array('required' => false)),
      'domingov'   => new sfValidatorBoolean(array('required' => false)),
      'dir_ent2v'  => new sfValidatorBoolean(array('required' => false)),
      'rifv'       => new sfValidatorBoolean(array('required' => false)),
      'contribuv'  => new sfValidatorBoolean(array('required' => false)),
      'dis_cenv'   => new sfValidatorBoolean(array('required' => false)),
      'nitv'       => new sfValidatorBoolean(array('required' => false)),
      'emailv'     => new sfValidatorBoolean(array('required' => false)),
      'co_ingrd'   => new sfValidatorBoolean(array('required' => false)),
      'co_ingrv'   => new sfValidatorBoolean(array('required' => false)),
      'co_ingr'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'tipo_perd'  => new sfValidatorBoolean(array('required' => false)),
      'tipo_perv'  => new sfValidatorBoolean(array('required' => false)),
      'tipo_per'   => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'co_tabv'    => new sfValidatorBoolean(array('required' => false)),
      'tipo_adid'  => new sfValidatorBoolean(array('required' => false)),
      'tipo_adiv'  => new sfValidatorBoolean(array('required' => false)),
      'tipo_adi'   => new sfValidatorInteger(array('required' => false)),
      'matrizd'    => new sfValidatorBoolean(array('required' => false)),
      'matrizv'    => new sfValidatorBoolean(array('required' => false)),
      'matriz'     => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'campo1'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo2'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo3'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo4'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo5'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo6'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo7'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo8'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'co_us_in'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_in'   => new sfValidatorDateTime(array('required' => false)),
      'co_us_mo'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_mo'   => new sfValidatorDateTime(array('required' => false)),
      'co_us_el'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_el'   => new sfValidatorDateTime(array('required' => false)),
      'revisado'   => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'trasnfe'    => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'co_sucu'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'serialp'    => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'valido'     => new sfValidatorBoolean(array('required' => false)),
      'rowguid'    => new sfValidatorString(array('max_length' => 36, 'required' => false)),
      'loginv'     => new sfValidatorBoolean(array('required' => false)),
      'passwordv'  => new sfValidatorBoolean(array('required' => false)),
      'estadov'    => new sfValidatorBoolean(array('required' => false)),
      'vpasswordv' => new sfValidatorBoolean(array('required' => false)),
      'co_paisv'   => new sfValidatorBoolean(array('required' => false)),
      'co_paisd'   => new sfValidatorBoolean(array('required' => false)),
      'co_pais'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'zipv'       => new sfValidatorBoolean(array('required' => false)),
      'ciudadv'    => new sfValidatorBoolean(array('required' => false)),
      'taxidv'     => new sfValidatorBoolean(array('required' => false)),
      'formtypev'  => new sfValidatorBoolean(array('required' => false)),
      'formtyped'  => new sfValidatorBoolean(array('required' => false)),
      'formtype'   => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'websitev'   => new sfValidatorBoolean(array('required' => false)),
      'bwebsitev'  => new sfValidatorBoolean(array('required' => false)),
      'bemailv'    => new sfValidatorBoolean(array('required' => false)),
      'salestaxv'  => new sfValidatorBoolean(array('required' => false)),
      'salestaxd'  => new sfValidatorBoolean(array('required' => false)),
      'salestax'   => new sfValidatorString(array('max_length' => 8, 'required' => false)),
    ));

    $this->widgetSchema->setNameFormat('ambclpro[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Ambclpro';
  }

}
