<?php

/**
 * Almacen form base class.
 *
 * @method Almacen getObject() Returns the current form's model object
 *
 * @package    gesser
 * @subpackage form
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 29553 2010-05-20 14:33:00Z Kris.Wallsmith $
 */
abstract class BaseAlmacenForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'co_alma'     => new sfWidgetFormInputHidden(),
      'alma_des'    => new sfWidgetFormInputText(),
      'nro_fact'    => new sfWidgetFormInputText(),
      'num_fac_ini' => new sfWidgetFormInputText(),
      'num_fac_fin' => new sfWidgetFormInputText(),
      'campo1'      => new sfWidgetFormInputText(),
      'campo2'      => new sfWidgetFormInputText(),
      'campo3'      => new sfWidgetFormInputText(),
      'campo4'      => new sfWidgetFormInputText(),
      'co_us_in'    => new sfWidgetFormInputText(),
      'fe_us_in'    => new sfWidgetFormDateTime(),
      'co_us_mo'    => new sfWidgetFormInputText(),
      'fe_us_mo'    => new sfWidgetFormDateTime(),
      'co_us_el'    => new sfWidgetFormInputText(),
      'fe_us_el'    => new sfWidgetFormDateTime(),
      'revisado'    => new sfWidgetFormInputText(),
      'trasnfe'     => new sfWidgetFormInputText(),
      'co_sucu'     => new sfWidgetFormInputText(),
      'rowguid'     => new sfWidgetFormInputText(),
      'nc_num'      => new sfWidgetFormInputText(),
      'nd_num'      => new sfWidgetFormInputText(),
      'ajus_num'    => new sfWidgetFormInputText(),
      'tras_num'    => new sfWidgetFormInputText(),
      'fisi_num'    => new sfWidgetFormInputText(),
      'num_kit'     => new sfWidgetFormInputText(),
      'genk_num'    => new sfWidgetFormInputText(),
      'fact_num'    => new sfWidgetFormInputText(),
      'ped_num'     => new sfWidgetFormInputText(),
      'cotc_num'    => new sfWidgetFormInputText(),
      'devc_num'    => new sfWidgetFormInputText(),
      'nde_num'     => new sfWidgetFormInputText(),
      'ndd_num'     => new sfWidgetFormInputText(),
      'post_num'    => new sfWidgetFormInputText(),
      'cfxg_num'    => new sfWidgetFormInputText(),
      'chdv_num'    => new sfWidgetFormInputText(),
      'giro_num'    => new sfWidgetFormInputText(),
      'reten_num'   => new sfWidgetFormInputText(),
      'cb_num'      => new sfWidgetFormInputText(),
      'movb_num'    => new sfWidgetFormInputText(),
      'movc_num'    => new sfWidgetFormInputText(),
      'ordp_num'    => new sfWidgetFormInputText(),
      'depc_num'    => new sfWidgetFormInputText(),
      'comp_num'    => new sfWidgetFormInputText(),
      'ord_num'     => new sfWidgetFormInputText(),
      'cotp_num'    => new sfWidgetFormInputText(),
      'devp_num'    => new sfWidgetFormInputText(),
      'ndr_num'     => new sfWidgetFormInputText(),
      'postcppnum'  => new sfWidgetFormInputText(),
      'ccxg_num'    => new sfWidgetFormInputText(),
      'chdvcppnum'  => new sfWidgetFormInputText(),
      'girocppnum'  => new sfWidgetFormInputText(),
      'nccpp_num'   => new sfWidgetFormInputText(),
      'ndcpp_num'   => new sfWidgetFormInputText(),
      'retencppnum' => new sfWidgetFormInputText(),
      'pg_num'      => new sfWidgetFormInputText(),
      'aju_posm'    => new sfWidgetFormInputText(),
      'aju_posa'    => new sfWidgetFormInputText(),
      'aju_negm'    => new sfWidgetFormInputText(),
      'aju_nega'    => new sfWidgetFormInputText(),
      'aju_posmc'   => new sfWidgetFormInputText(),
      'aju_posac'   => new sfWidgetFormInputText(),
      'aju_negmc'   => new sfWidgetFormInputText(),
      'aju_negac'   => new sfWidgetFormInputText(),
      'pventa'      => new sfWidgetFormInputText(),
      'turnosic'    => new sfWidgetFormInputText(),
      'plv_num'     => new sfWidgetFormInputText(),
      'plc_num'     => new sfWidgetFormInputText(),
      'tabislr'     => new sfWidgetFormInputText(),
      'imp_num'     => new sfWidgetFormInputText(),
      'rma_cli'     => new sfWidgetFormInputText(),
      'rma_prov'    => new sfWidgetFormInputText(),
      'rma_entc'    => new sfWidgetFormInputText(),
      'rma_entp'    => new sfWidgetFormInputText(),
      'rma_regs'    => new sfWidgetFormInputText(),
      'fact_s1'     => new sfWidgetFormInputText(),
      'fact_s2'     => new sfWidgetFormInputText(),
      'fact_s3'     => new sfWidgetFormInputText(),
      'fact_s4'     => new sfWidgetFormInputText(),
      'fact_s5'     => new sfWidgetFormInputText(),
      'nde_s1'      => new sfWidgetFormInputText(),
      'nde_s2'      => new sfWidgetFormInputText(),
      'nde_s3'      => new sfWidgetFormInputText(),
      'nde_s4'      => new sfWidgetFormInputText(),
      'nde_s5'      => new sfWidgetFormInputText(),
      'nc_s1'       => new sfWidgetFormInputText(),
      'nc_s2'       => new sfWidgetFormInputText(),
      'nc_s3'       => new sfWidgetFormInputText(),
      'nc_s4'       => new sfWidgetFormInputText(),
      'nc_s5'       => new sfWidgetFormInputText(),
      'nd_s1'       => new sfWidgetFormInputText(),
      'nd_s2'       => new sfWidgetFormInputText(),
      'nd_s3'       => new sfWidgetFormInputText(),
      'nd_s4'       => new sfWidgetFormInputText(),
      'nd_s5'       => new sfWidgetFormInputText(),
      'fact_f1'     => new sfWidgetFormInputText(),
      'fact_f2'     => new sfWidgetFormInputText(),
      'fact_f3'     => new sfWidgetFormInputText(),
      'fact_f4'     => new sfWidgetFormInputText(),
      'nde_f1'      => new sfWidgetFormInputText(),
      'nde_f2'      => new sfWidgetFormInputText(),
      'nde_f3'      => new sfWidgetFormInputText(),
      'nde_f4'      => new sfWidgetFormInputText(),
      'nc_f1'       => new sfWidgetFormInputText(),
      'nc_f2'       => new sfWidgetFormInputText(),
      'nc_f3'       => new sfWidgetFormInputText(),
      'nc_f4'       => new sfWidgetFormInputText(),
      'nd_f1'       => new sfWidgetFormInputText(),
      'nd_f2'       => new sfWidgetFormInputText(),
      'nd_f3'       => new sfWidgetFormInputText(),
      'nd_f4'       => new sfWidgetFormInputText(),
      'fact_p1'     => new sfWidgetFormInputText(),
      'fact_p2'     => new sfWidgetFormInputText(),
      'fact_p3'     => new sfWidgetFormInputText(),
      'fact_p4'     => new sfWidgetFormInputText(),
      'fact_p5'     => new sfWidgetFormInputText(),
      'nde_p1'      => new sfWidgetFormInputText(),
      'nde_p2'      => new sfWidgetFormInputText(),
      'nde_p3'      => new sfWidgetFormInputText(),
      'nde_p4'      => new sfWidgetFormInputText(),
      'nde_p5'      => new sfWidgetFormInputText(),
      'nc_p1'       => new sfWidgetFormInputText(),
      'nc_p2'       => new sfWidgetFormInputText(),
      'nc_p3'       => new sfWidgetFormInputText(),
      'nc_p4'       => new sfWidgetFormInputText(),
      'nc_p5'       => new sfWidgetFormInputText(),
      'nd_p1'       => new sfWidgetFormInputText(),
      'nd_p2'       => new sfWidgetFormInputText(),
      'nd_p3'       => new sfWidgetFormInputText(),
      'nd_p4'       => new sfWidgetFormInputText(),
      'nd_p5'       => new sfWidgetFormInputText(),
      'fact_num2'   => new sfWidgetFormInputText(),
      'fact_num3'   => new sfWidgetFormInputText(),
      'fact_num4'   => new sfWidgetFormInputText(),
      'fact_num5'   => new sfWidgetFormInputText(),
      'nde_num2'    => new sfWidgetFormInputText(),
      'nde_num3'    => new sfWidgetFormInputText(),
      'nde_num4'    => new sfWidgetFormInputText(),
      'nde_num5'    => new sfWidgetFormInputText(),
      'nc_num2'     => new sfWidgetFormInputText(),
      'nc_num3'     => new sfWidgetFormInputText(),
      'nc_num4'     => new sfWidgetFormInputText(),
      'nc_num5'     => new sfWidgetFormInputText(),
      'nd_num2'     => new sfWidgetFormInputText(),
      'nd_num3'     => new sfWidgetFormInputText(),
      'nd_num4'     => new sfWidgetFormInputText(),
      'nd_num5'     => new sfWidgetFormInputText(),
      'serie2'      => new sfWidgetFormInputCheckbox(),
      'serie3'      => new sfWidgetFormInputCheckbox(),
      'serie4'      => new sfWidgetFormInputCheckbox(),
      'serie5'      => new sfWidgetFormInputCheckbox(),
      'emp_num'     => new sfWidgetFormInputText(),
      'dmc_num'     => new sfWidgetFormInputText(),
      'tax_num'     => new sfWidgetFormInputText(),
      'ced_num'     => new sfWidgetFormInputText(),
      'ent_num'     => new sfWidgetFormInputText(),
      'cie_num'     => new sfWidgetFormInputText(),
      'odp_num'     => new sfWidgetFormInputText(),
      'req_num'     => new sfWidgetFormInputText(),
      'dev_num'     => new sfWidgetFormInputText(),
      'exp_num'     => new sfWidgetFormInputText(),
      'inp_num'     => new sfWidgetFormInputText(),
      'cost_num'    => new sfWidgetFormInputText(),
      'par_num'     => new sfWidgetFormInputText(),
      'esc_num'     => new sfWidgetFormInputText(),
      'pla_num'     => new sfWidgetFormInputText(),
      'men_num'     => new sfWidgetFormInputText(),
      'dist_num'    => new sfWidgetFormInputText(),
      'exp_numi'    => new sfWidgetFormInputText(),
    ));

    $this->setValidators(array(
      'co_alma'     => new sfValidatorChoice(array('choices' => array($this->getObject()->get('co_alma')), 'empty_value' => $this->getObject()->get('co_alma'), 'required' => false)),
      'alma_des'    => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'nro_fact'    => new sfValidatorInteger(array('required' => false)),
      'num_fac_ini' => new sfValidatorInteger(array('required' => false)),
      'num_fac_fin' => new sfValidatorInteger(array('required' => false)),
      'campo1'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo2'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo3'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo4'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'co_us_in'    => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_in'    => new sfValidatorDateTime(array('required' => false)),
      'co_us_mo'    => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_mo'    => new sfValidatorDateTime(array('required' => false)),
      'co_us_el'    => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_el'    => new sfValidatorDateTime(array('required' => false)),
      'revisado'    => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'trasnfe'     => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'co_sucu'     => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'rowguid'     => new sfValidatorString(array('max_length' => 36, 'required' => false)),
      'nc_num'      => new sfValidatorInteger(array('required' => false)),
      'nd_num'      => new sfValidatorInteger(array('required' => false)),
      'ajus_num'    => new sfValidatorInteger(array('required' => false)),
      'tras_num'    => new sfValidatorInteger(array('required' => false)),
      'fisi_num'    => new sfValidatorInteger(array('required' => false)),
      'num_kit'     => new sfValidatorInteger(array('required' => false)),
      'genk_num'    => new sfValidatorInteger(array('required' => false)),
      'fact_num'    => new sfValidatorInteger(array('required' => false)),
      'ped_num'     => new sfValidatorInteger(array('required' => false)),
      'cotc_num'    => new sfValidatorInteger(array('required' => false)),
      'devc_num'    => new sfValidatorInteger(array('required' => false)),
      'nde_num'     => new sfValidatorInteger(array('required' => false)),
      'ndd_num'     => new sfValidatorInteger(array('required' => false)),
      'post_num'    => new sfValidatorInteger(array('required' => false)),
      'cfxg_num'    => new sfValidatorInteger(array('required' => false)),
      'chdv_num'    => new sfValidatorInteger(array('required' => false)),
      'giro_num'    => new sfValidatorInteger(array('required' => false)),
      'reten_num'   => new sfValidatorInteger(array('required' => false)),
      'cb_num'      => new sfValidatorInteger(array('required' => false)),
      'movb_num'    => new sfValidatorInteger(array('required' => false)),
      'movc_num'    => new sfValidatorInteger(array('required' => false)),
      'ordp_num'    => new sfValidatorInteger(array('required' => false)),
      'depc_num'    => new sfValidatorInteger(array('required' => false)),
      'comp_num'    => new sfValidatorInteger(array('required' => false)),
      'ord_num'     => new sfValidatorInteger(array('required' => false)),
      'cotp_num'    => new sfValidatorInteger(array('required' => false)),
      'devp_num'    => new sfValidatorInteger(array('required' => false)),
      'ndr_num'     => new sfValidatorInteger(array('required' => false)),
      'postcppnum'  => new sfValidatorInteger(array('required' => false)),
      'ccxg_num'    => new sfValidatorInteger(array('required' => false)),
      'chdvcppnum'  => new sfValidatorInteger(array('required' => false)),
      'girocppnum'  => new sfValidatorInteger(array('required' => false)),
      'nccpp_num'   => new sfValidatorInteger(array('required' => false)),
      'ndcpp_num'   => new sfValidatorInteger(array('required' => false)),
      'retencppnum' => new sfValidatorInteger(array('required' => false)),
      'pg_num'      => new sfValidatorInteger(array('required' => false)),
      'aju_posm'    => new sfValidatorInteger(array('required' => false)),
      'aju_posa'    => new sfValidatorInteger(array('required' => false)),
      'aju_negm'    => new sfValidatorInteger(array('required' => false)),
      'aju_nega'    => new sfValidatorInteger(array('required' => false)),
      'aju_posmc'   => new sfValidatorInteger(array('required' => false)),
      'aju_posac'   => new sfValidatorInteger(array('required' => false)),
      'aju_negmc'   => new sfValidatorInteger(array('required' => false)),
      'aju_negac'   => new sfValidatorInteger(array('required' => false)),
      'pventa'      => new sfValidatorInteger(array('required' => false)),
      'turnosic'    => new sfValidatorInteger(array('required' => false)),
      'plv_num'     => new sfValidatorInteger(array('required' => false)),
      'plc_num'     => new sfValidatorInteger(array('required' => false)),
      'tabislr'     => new sfValidatorInteger(array('required' => false)),
      'imp_num'     => new sfValidatorInteger(array('required' => false)),
      'rma_cli'     => new sfValidatorInteger(array('required' => false)),
      'rma_prov'    => new sfValidatorInteger(array('required' => false)),
      'rma_entc'    => new sfValidatorInteger(array('required' => false)),
      'rma_entp'    => new sfValidatorInteger(array('required' => false)),
      'rma_regs'    => new sfValidatorInteger(array('required' => false)),
      'fact_s1'     => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'fact_s2'     => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'fact_s3'     => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'fact_s4'     => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'fact_s5'     => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nde_s1'      => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nde_s2'      => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nde_s3'      => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nde_s4'      => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nde_s5'      => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nc_s1'       => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nc_s2'       => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nc_s3'       => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nc_s4'       => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nc_s5'       => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nd_s1'       => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nd_s2'       => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nd_s3'       => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nd_s4'       => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'nd_s5'       => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'fact_f1'     => new sfValidatorInteger(array('required' => false)),
      'fact_f2'     => new sfValidatorInteger(array('required' => false)),
      'fact_f3'     => new sfValidatorInteger(array('required' => false)),
      'fact_f4'     => new sfValidatorInteger(array('required' => false)),
      'nde_f1'      => new sfValidatorInteger(array('required' => false)),
      'nde_f2'      => new sfValidatorInteger(array('required' => false)),
      'nde_f3'      => new sfValidatorInteger(array('required' => false)),
      'nde_f4'      => new sfValidatorInteger(array('required' => false)),
      'nc_f1'       => new sfValidatorInteger(array('required' => false)),
      'nc_f2'       => new sfValidatorInteger(array('required' => false)),
      'nc_f3'       => new sfValidatorInteger(array('required' => false)),
      'nc_f4'       => new sfValidatorInteger(array('required' => false)),
      'nd_f1'       => new sfValidatorInteger(array('required' => false)),
      'nd_f2'       => new sfValidatorInteger(array('required' => false)),
      'nd_f3'       => new sfValidatorInteger(array('required' => false)),
      'nd_f4'       => new sfValidatorInteger(array('required' => false)),
      'fact_p1'     => new sfValidatorInteger(array('required' => false)),
      'fact_p2'     => new sfValidatorInteger(array('required' => false)),
      'fact_p3'     => new sfValidatorInteger(array('required' => false)),
      'fact_p4'     => new sfValidatorInteger(array('required' => false)),
      'fact_p5'     => new sfValidatorInteger(array('required' => false)),
      'nde_p1'      => new sfValidatorInteger(array('required' => false)),
      'nde_p2'      => new sfValidatorInteger(array('required' => false)),
      'nde_p3'      => new sfValidatorInteger(array('required' => false)),
      'nde_p4'      => new sfValidatorInteger(array('required' => false)),
      'nde_p5'      => new sfValidatorInteger(array('required' => false)),
      'nc_p1'       => new sfValidatorInteger(array('required' => false)),
      'nc_p2'       => new sfValidatorInteger(array('required' => false)),
      'nc_p3'       => new sfValidatorInteger(array('required' => false)),
      'nc_p4'       => new sfValidatorInteger(array('required' => false)),
      'nc_p5'       => new sfValidatorInteger(array('required' => false)),
      'nd_p1'       => new sfValidatorInteger(array('required' => false)),
      'nd_p2'       => new sfValidatorInteger(array('required' => false)),
      'nd_p3'       => new sfValidatorInteger(array('required' => false)),
      'nd_p4'       => new sfValidatorInteger(array('required' => false)),
      'nd_p5'       => new sfValidatorInteger(array('required' => false)),
      'fact_num2'   => new sfValidatorInteger(array('required' => false)),
      'fact_num3'   => new sfValidatorInteger(array('required' => false)),
      'fact_num4'   => new sfValidatorInteger(array('required' => false)),
      'fact_num5'   => new sfValidatorInteger(array('required' => false)),
      'nde_num2'    => new sfValidatorInteger(array('required' => false)),
      'nde_num3'    => new sfValidatorInteger(array('required' => false)),
      'nde_num4'    => new sfValidatorInteger(array('required' => false)),
      'nde_num5'    => new sfValidatorInteger(array('required' => false)),
      'nc_num2'     => new sfValidatorInteger(array('required' => false)),
      'nc_num3'     => new sfValidatorInteger(array('required' => false)),
      'nc_num4'     => new sfValidatorInteger(array('required' => false)),
      'nc_num5'     => new sfValidatorInteger(array('required' => false)),
      'nd_num2'     => new sfValidatorInteger(array('required' => false)),
      'nd_num3'     => new sfValidatorInteger(array('required' => false)),
      'nd_num4'     => new sfValidatorInteger(array('required' => false)),
      'nd_num5'     => new sfValidatorInteger(array('required' => false)),
      'serie2'      => new sfValidatorBoolean(array('required' => false)),
      'serie3'      => new sfValidatorBoolean(array('required' => false)),
      'serie4'      => new sfValidatorBoolean(array('required' => false)),
      'serie5'      => new sfValidatorBoolean(array('required' => false)),
      'emp_num'     => new sfValidatorInteger(array('required' => false)),
      'dmc_num'     => new sfValidatorInteger(array('required' => false)),
      'tax_num'     => new sfValidatorInteger(array('required' => false)),
      'ced_num'     => new sfValidatorInteger(array('required' => false)),
      'ent_num'     => new sfValidatorInteger(array('required' => false)),
      'cie_num'     => new sfValidatorInteger(array('required' => false)),
      'odp_num'     => new sfValidatorInteger(array('required' => false)),
      'req_num'     => new sfValidatorInteger(array('required' => false)),
      'dev_num'     => new sfValidatorInteger(array('required' => false)),
      'exp_num'     => new sfValidatorInteger(array('required' => false)),
      'inp_num'     => new sfValidatorInteger(array('required' => false)),
      'cost_num'    => new sfValidatorInteger(array('required' => false)),
      'par_num'     => new sfValidatorInteger(array('required' => false)),
      'esc_num'     => new sfValidatorInteger(array('required' => false)),
      'pla_num'     => new sfValidatorInteger(array('required' => false)),
      'men_num'     => new sfValidatorInteger(array('required' => false)),
      'dist_num'    => new sfValidatorInteger(array('required' => false)),
      'exp_numi'    => new sfValidatorInteger(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('almacen[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Almacen';
  }

}
