<?php

/**
 * ParEmp form base class.
 *
 * @method ParEmp getObject() Returns the current form's model object
 *
 * @package    gesser
 * @subpackage form
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 29553 2010-05-20 14:33:00Z Kris.Wallsmith $
 */
abstract class BaseParEmpForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'cod_emp'     => new sfWidgetFormInputHidden(),
      'emp_imp'     => new sfWidgetFormInputText(),
      'temp_num'    => new sfWidgetFormInputText(),
      'cfxg_num'    => new sfWidgetFormInputText(),
      'ccxg_num'    => new sfWidgetFormInputText(),
      'fact_num'    => new sfWidgetFormInputText(),
      'giro_num'    => new sfWidgetFormInputText(),
      'girocppnum'  => new sfWidgetFormInputText(),
      'nota_num'    => new sfWidgetFormInputText(),
      'ped_num'     => new sfWidgetFormInputText(),
      'ord_num'     => new sfWidgetFormInputText(),
      'cotc_num'    => new sfWidgetFormInputText(),
      'cotp_num'    => new sfWidgetFormInputText(),
      'nde_num'     => new sfWidgetFormInputText(),
      'cb_num'      => new sfWidgetFormInputText(),
      'pg_num'      => new sfWidgetFormInputText(),
      'nd_num'      => new sfWidgetFormInputText(),
      'ndcpp_num'   => new sfWidgetFormInputText(),
      'nc_num'      => new sfWidgetFormInputText(),
      'nccpp_num'   => new sfWidgetFormInputText(),
      'chdv_num'    => new sfWidgetFormInputText(),
      'chdvcppnum'  => new sfWidgetFormInputText(),
      'comp_num'    => new sfWidgetFormInputText(),
      'devp_num'    => new sfWidgetFormInputText(),
      'devc_num'    => new sfWidgetFormInputText(),
      'ajus_num'    => new sfWidgetFormInputText(),
      'depc_num'    => new sfWidgetFormInputText(),
      'tras_num'    => new sfWidgetFormInputText(),
      'genk_num'    => new sfWidgetFormInputText(),
      'ords_num'    => new sfWidgetFormInputText(),
      'ordp_num'    => new sfWidgetFormInputText(),
      'ejep_num'    => new sfWidgetFormInputText(),
      'inte_num'    => new sfWidgetFormInputText(),
      'porc_db'     => new sfWidgetFormInputText(),
      'post_num'    => new sfWidgetFormInputText(),
      'postcppnum'  => new sfWidgetFormInputText(),
      'reten_num'   => new sfWidgetFormInputText(),
      'retencppnum' => new sfWidgetFormInputText(),
      'ndr_num'     => new sfWidgetFormInputText(),
      'ndd_num'     => new sfWidgetFormInputText(),
      'movc_num'    => new sfWidgetFormInputText(),
      'movb_num'    => new sfWidgetFormInputText(),
      'desc_num'    => new sfWidgetFormInputText(),
      'desccppnum'  => new sfWidgetFormInputText(),
      'num_kit'     => new sfWidgetFormInputText(),
      'fisi_num'    => new sfWidgetFormInputText(),
      'docum1'      => new sfWidgetFormInputText(),
      'docum2'      => new sfWidgetFormInputText(),
      'temp_char1'  => new sfWidgetFormInputText(),
      'temp_char2'  => new sfWidgetFormInputText(),
      'temp_char3'  => new sfWidgetFormInputText(),
      'temp_char4'  => new sfWidgetFormInputText(),
      'temp_char5'  => new sfWidgetFormInputText(),
      'temp_char6'  => new sfWidgetFormInputText(),
      'temp_char7'  => new sfWidgetFormInputText(),
      'temp_char8'  => new sfWidgetFormInputText(),
      'p_comv_vol'  => new sfWidgetFormInputCheckbox(),
      'p_comv_klu'  => new sfWidgetFormInputCheckbox(),
      'p_comv_ven'  => new sfWidgetFormInputCheckbox(),
      'p_comv_con'  => new sfWidgetFormInputCheckbox(),
      'p_comv_r_c'  => new sfWidgetFormInputCheckbox(),
      'p_comv_r_p'  => new sfWidgetFormInputCheckbox(),
      'p_comv_tip'  => new sfWidgetFormInputCheckbox(),
      'p_desc_art'  => new sfWidgetFormInputCheckbox(),
      'p_desc_cat'  => new sfWidgetFormInputCheckbox(),
      'p_desc_glo'  => new sfWidgetFormInputCheckbox(),
      'p_desc_ofe'  => new sfWidgetFormInputCheckbox(),
      'p_desc_lin'  => new sfWidgetFormInputCheckbox(),
      'p_prec_isv'  => new sfWidgetFormInputCheckbox(),
      'p_prec1_isv' => new sfWidgetFormInputCheckbox(),
      'p_prec2_isv' => new sfWidgetFormInputCheckbox(),
      'p_prec3_isv' => new sfWidgetFormInputCheckbox(),
      'p_prec4_isv' => new sfWidgetFormInputCheckbox(),
      'p_prec5_isv' => new sfWidgetFormInputCheckbox(),
      'p_roundfac'  => new sfWidgetFormInputCheckbox(),
      'p_roundinf'  => new sfWidgetFormInputCheckbox(),
      'p_val_red'   => new sfWidgetFormInputText(),
      'p_roundequ'  => new sfWidgetFormInputCheckbox(),
      'p_roundsup'  => new sfWidgetFormInputCheckbox(),
      'p_costo_do'  => new sfWidgetFormInputCheckbox(),
      'p_com_auto'  => new sfWidgetFormInputCheckbox(),
      'p_stock_neg' => new sfWidgetFormInputCheckbox(),
      'p_ent_new'   => new sfWidgetFormInputCheckbox(),
      'p_aju_comi'  => new sfWidgetFormInputCheckbox(),
      'p_doble_un'  => new sfWidgetFormInputCheckbox(),
      'p_pront_pg'  => new sfWidgetFormInputCheckbox(),
      'p_grab_ren'  => new sfWidgetFormInputCheckbox(),
      'p_para1'     => new sfWidgetFormInputCheckbox(),
      'p_para2'     => new sfWidgetFormInputCheckbox(),
      'p_para3'     => new sfWidgetFormInputCheckbox(),
      'p_para4'     => new sfWidgetFormInputCheckbox(),
      'p_para5'     => new sfWidgetFormInputCheckbox(),
      'p_para6'     => new sfWidgetFormInputCheckbox(),
      'p_para7'     => new sfWidgetFormInputCheckbox(),
      'p_para8'     => new sfWidgetFormInputCheckbox(),
      'p_para9'     => new sfWidgetFormInputCheckbox(),
      'p_para10'    => new sfWidgetFormInputCheckbox(),
      'p_open_com'  => new sfWidgetFormInputCheckbox(),
      'p_marg_cap'  => new sfWidgetFormInputCheckbox(),
      'p_dir_ent'   => new sfWidgetFormInputCheckbox(),
      'p_art_20'    => new sfWidgetFormInputCheckbox(),
      'p_imp_kit'   => new sfWidgetFormInputCheckbox(),
      'p_red_com'   => new sfWidgetFormInputCheckbox(),
      'p_cyf_dol'   => new sfWidgetFormInputCheckbox(),
      'p_ser_art'   => new sfWidgetFormInputCheckbox(),
      'p_art_dol'   => new sfWidgetFormInputCheckbox(),
      'mone_art'    => new sfWidgetFormInputText(),
      'p_deb_ban'   => new sfWidgetFormInputCheckbox(),
      'p_deb_aut'   => new sfWidgetFormInputCheckbox(),
      'p_fact_alm'  => new sfWidgetFormInputCheckbox(),
      'p_despacho'  => new sfWidgetFormInputCheckbox(),
      'p_idb'       => new sfWidgetFormInputCheckbox(),
      'val_idb'     => new sfWidgetFormInputText(),
      'tempor1'     => new sfWidgetFormInputText(),
      'fecha_res'   => new sfWidgetFormDateTime(),
      'fecha_fisi'  => new sfWidgetFormDateTime(),
      'open_fisi'   => new sfWidgetFormInputCheckbox(),
      'serial'      => new sfWidgetFormInputText(),
      'cadena'      => new sfWidgetFormInputText(),
      'inv_emp'     => new sfWidgetFormInputText(),
      'temp_char'   => new sfWidgetFormInputText(),
      'fec_inte'    => new sfWidgetFormDateTime(),
      'temp_fech'   => new sfWidgetFormDateTime(),
      'ele_linea'   => new sfWidgetFormInputCheckbox(),
      'lon_linea'   => new sfWidgetFormInputText(),
      'ele_categ'   => new sfWidgetFormInputCheckbox(),
      'lon_categ'   => new sfWidgetFormInputText(),
      'ele_medid'   => new sfWidgetFormInputCheckbox(),
      'lon_medid'   => new sfWidgetFormInputText(),
      'ele_item'    => new sfWidgetFormInputCheckbox(),
      'lon_item'    => new sfWidgetFormInputText(),
      'ele_color'   => new sfWidgetFormInputCheckbox(),
      'lon_color'   => new sfWidgetFormInputText(),
      'ele_carter'  => new sfWidgetFormInputCheckbox(),
      'caracter'    => new sfWidgetFormInputText(),
      'dec_prec'    => new sfWidgetFormInputText(),
      'dec_cost'    => new sfWidgetFormInputText(),
      'cant_art'    => new sfWidgetFormInputText(),
      'total_cod'   => new sfWidgetFormInputText(),
      'tipo_com'    => new sfWidgetFormInputCheckbox(),
      'tipo_lib'    => new sfWidgetFormInputCheckbox(),
      'co_us_in'    => new sfWidgetFormInputText(),
      'fe_us_in'    => new sfWidgetFormDateTime(),
      'co_us_mo'    => new sfWidgetFormInputText(),
      'fe_us_mo'    => new sfWidgetFormDateTime(),
      'logo'        => new sfWidgetFormTextarea(),
      'revisado'    => new sfWidgetFormInputText(),
      'trasnfe'     => new sfWidgetFormInputText(),
      'p_sucursal'  => new sfWidgetFormInputCheckbox(),
      'rowguid'     => new sfWidgetFormInputText(),
      'p_licores'   => new sfWidgetFormInputCheckbox(),
      'p_lotenro'   => new sfWidgetFormInputCheckbox(),
      'p_lotefec'   => new sfWidgetFormInputCheckbox(),
      'serverolap'  => new sfWidgetFormInputText(),
      'dataolap'    => new sfWidgetFormInputText(),
      'p_loteaut'   => new sfWidgetFormInputCheckbox(),
      'tipo_inve'   => new sfWidgetFormInputText(),
      'aju_posm'    => new sfWidgetFormInputText(),
      'aju_posa'    => new sfWidgetFormInputText(),
      'aju_negm'    => new sfWidgetFormInputText(),
      'aju_nega'    => new sfWidgetFormInputText(),
      'aju_posmc'   => new sfWidgetFormInputText(),
      'aju_posac'   => new sfWidgetFormInputText(),
      'aju_negmc'   => new sfWidgetFormInputText(),
      'aju_negac'   => new sfWidgetFormInputText(),
      'plv_num'     => new sfWidgetFormInputText(),
      'plc_num'     => new sfWidgetFormInputText(),
      'pventa'      => new sfWidgetFormInputText(),
      'turnosic'    => new sfWidgetFormInputText(),
      'tabislr'     => new sfWidgetFormInputText(),
      'moneda'      => new sfWidgetFormInputText(),
      'imp_num'     => new sfWidgetFormInputText(),
      'rma_cli'     => new sfWidgetFormInputText(),
      'rma_prov'    => new sfWidgetFormInputText(),
      'rma_entc'    => new sfWidgetFormInputText(),
      'rma_entp'    => new sfWidgetFormInputText(),
      'rma_regs'    => new sfWidgetFormInputText(),
      'p_prov_new'  => new sfWidgetFormInputCheckbox(),
      'p_ser_new'   => new sfWidgetFormInputCheckbox(),
      'rmacliente'  => new sfWidgetFormInputText(),
      'rma_trans'   => new sfWidgetFormInputText(),
      'garantia'    => new sfWidgetFormInputText(),
      'reem_prov'   => new sfWidgetFormInputText(),
      'des_ser'     => new sfWidgetFormInputText(),
      'ser_auto'    => new sfWidgetFormInputText(),
      'pcontrol_1'  => new sfWidgetFormInputCheckbox(),
      'pcontrol_2'  => new sfWidgetFormInputCheckbox(),
      'pcontrol_3'  => new sfWidgetFormInputCheckbox(),
      'pcontrol_4'  => new sfWidgetFormInputCheckbox(),
      'pcontrol_5'  => new sfWidgetFormInputCheckbox(),
      'idioma'      => new sfWidgetFormInputText(),
      'serie'       => new sfWidgetFormInputCheckbox(),
      'aux01'       => new sfWidgetFormInputText(),
      'aux02'       => new sfWidgetFormInputText(),
      'eprofit'     => new sfWidgetFormInputCheckbox(),
      'pais'        => new sfWidgetFormInputText(),
      'emp_num'     => new sfWidgetFormInputText(),
      'dmc_num'     => new sfWidgetFormInputText(),
      'tax_num'     => new sfWidgetFormInputText(),
      'ced_num'     => new sfWidgetFormInputText(),
      'ent_num'     => new sfWidgetFormInputText(),
      'artinmp'     => new sfWidgetFormInputCheckbox(),
      'tip_costo'   => new sfWidgetFormInputText(),
      'tip_cmat'    => new sfWidgetFormInputText(),
      'co_aent'     => new sfWidgetFormInputText(),
      'cie_num'     => new sfWidgetFormInputText(),
      'odp_num'     => new sfWidgetFormInputText(),
      'req_num'     => new sfWidgetFormInputText(),
      'dev_num'     => new sfWidgetFormInputText(),
      'co_asal'     => new sfWidgetFormInputText(),
      'devmax'      => new sfWidgetFormInputCheckbox(),
      'exp_num'     => new sfWidgetFormInputText(),
      'inp_num'     => new sfWidgetFormInputText(),
      'cost_num'    => new sfWidgetFormInputText(),
      'par_num'     => new sfWidgetFormInputText(),
      'esc_num'     => new sfWidgetFormInputText(),
      'cierre_mes'  => new sfWidgetFormInputCheckbox(),
      'pla_num'     => new sfWidgetFormInputText(),
      'men_num'     => new sfWidgetFormInputText(),
      'tipcosdev'   => new sfWidgetFormInputText(),
      'max_lin'     => new sfWidgetFormInputText(),
      'dist_num'    => new sfWidgetFormInputText(),
      'exp_numi'    => new sfWidgetFormInputText(),
      'p_imp65'     => new sfWidgetFormInputCheckbox(),
      'val_max'     => new sfWidgetFormInputCheckbox(),
      'server'      => new sfWidgetFormInputText(),
      'namedb'      => new sfWidgetFormInputText(),
      'login'       => new sfWidgetFormInputText(),
      'password'    => new sfWidgetFormInputText(),
      'man_impr'    => new sfWidgetFormInputCheckbox(),
    ));

    $this->setValidators(array(
      'cod_emp'     => new sfValidatorChoice(array('choices' => array($this->getObject()->get('cod_emp')), 'empty_value' => $this->getObject()->get('cod_emp'), 'required' => false)),
      'emp_imp'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'temp_num'    => new sfValidatorInteger(array('required' => false)),
      'cfxg_num'    => new sfValidatorInteger(array('required' => false)),
      'ccxg_num'    => new sfValidatorInteger(array('required' => false)),
      'fact_num'    => new sfValidatorInteger(array('required' => false)),
      'giro_num'    => new sfValidatorInteger(array('required' => false)),
      'girocppnum'  => new sfValidatorInteger(array('required' => false)),
      'nota_num'    => new sfValidatorInteger(array('required' => false)),
      'ped_num'     => new sfValidatorInteger(array('required' => false)),
      'ord_num'     => new sfValidatorInteger(array('required' => false)),
      'cotc_num'    => new sfValidatorInteger(array('required' => false)),
      'cotp_num'    => new sfValidatorInteger(array('required' => false)),
      'nde_num'     => new sfValidatorInteger(array('required' => false)),
      'cb_num'      => new sfValidatorInteger(array('required' => false)),
      'pg_num'      => new sfValidatorInteger(array('required' => false)),
      'nd_num'      => new sfValidatorInteger(array('required' => false)),
      'ndcpp_num'   => new sfValidatorInteger(array('required' => false)),
      'nc_num'      => new sfValidatorInteger(array('required' => false)),
      'nccpp_num'   => new sfValidatorInteger(array('required' => false)),
      'chdv_num'    => new sfValidatorInteger(array('required' => false)),
      'chdvcppnum'  => new sfValidatorInteger(array('required' => false)),
      'comp_num'    => new sfValidatorInteger(array('required' => false)),
      'devp_num'    => new sfValidatorInteger(array('required' => false)),
      'devc_num'    => new sfValidatorInteger(array('required' => false)),
      'ajus_num'    => new sfValidatorInteger(array('required' => false)),
      'depc_num'    => new sfValidatorInteger(array('required' => false)),
      'tras_num'    => new sfValidatorInteger(array('required' => false)),
      'genk_num'    => new sfValidatorInteger(array('required' => false)),
      'ords_num'    => new sfValidatorInteger(array('required' => false)),
      'ordp_num'    => new sfValidatorInteger(array('required' => false)),
      'ejep_num'    => new sfValidatorInteger(array('required' => false)),
      'inte_num'    => new sfValidatorInteger(array('required' => false)),
      'porc_db'     => new sfValidatorNumber(array('required' => false)),
      'post_num'    => new sfValidatorInteger(array('required' => false)),
      'postcppnum'  => new sfValidatorInteger(array('required' => false)),
      'reten_num'   => new sfValidatorInteger(array('required' => false)),
      'retencppnum' => new sfValidatorInteger(array('required' => false)),
      'ndr_num'     => new sfValidatorInteger(array('required' => false)),
      'ndd_num'     => new sfValidatorInteger(array('required' => false)),
      'movc_num'    => new sfValidatorInteger(array('required' => false)),
      'movb_num'    => new sfValidatorInteger(array('required' => false)),
      'desc_num'    => new sfValidatorInteger(array('required' => false)),
      'desccppnum'  => new sfValidatorInteger(array('required' => false)),
      'num_kit'     => new sfValidatorInteger(array('required' => false)),
      'fisi_num'    => new sfValidatorInteger(array('required' => false)),
      'docum1'      => new sfValidatorInteger(array('required' => false)),
      'docum2'      => new sfValidatorInteger(array('required' => false)),
      'temp_char1'  => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'temp_char2'  => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'temp_char3'  => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'temp_char4'  => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'temp_char5'  => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'temp_char6'  => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'temp_char7'  => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'temp_char8'  => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'p_comv_vol'  => new sfValidatorBoolean(array('required' => false)),
      'p_comv_klu'  => new sfValidatorBoolean(array('required' => false)),
      'p_comv_ven'  => new sfValidatorBoolean(array('required' => false)),
      'p_comv_con'  => new sfValidatorBoolean(array('required' => false)),
      'p_comv_r_c'  => new sfValidatorBoolean(array('required' => false)),
      'p_comv_r_p'  => new sfValidatorBoolean(array('required' => false)),
      'p_comv_tip'  => new sfValidatorBoolean(array('required' => false)),
      'p_desc_art'  => new sfValidatorBoolean(array('required' => false)),
      'p_desc_cat'  => new sfValidatorBoolean(array('required' => false)),
      'p_desc_glo'  => new sfValidatorBoolean(array('required' => false)),
      'p_desc_ofe'  => new sfValidatorBoolean(array('required' => false)),
      'p_desc_lin'  => new sfValidatorBoolean(array('required' => false)),
      'p_prec_isv'  => new sfValidatorBoolean(array('required' => false)),
      'p_prec1_isv' => new sfValidatorBoolean(array('required' => false)),
      'p_prec2_isv' => new sfValidatorBoolean(array('required' => false)),
      'p_prec3_isv' => new sfValidatorBoolean(array('required' => false)),
      'p_prec4_isv' => new sfValidatorBoolean(array('required' => false)),
      'p_prec5_isv' => new sfValidatorBoolean(array('required' => false)),
      'p_roundfac'  => new sfValidatorBoolean(array('required' => false)),
      'p_roundinf'  => new sfValidatorBoolean(array('required' => false)),
      'p_val_red'   => new sfValidatorInteger(array('required' => false)),
      'p_roundequ'  => new sfValidatorBoolean(array('required' => false)),
      'p_roundsup'  => new sfValidatorBoolean(array('required' => false)),
      'p_costo_do'  => new sfValidatorBoolean(array('required' => false)),
      'p_com_auto'  => new sfValidatorBoolean(array('required' => false)),
      'p_stock_neg' => new sfValidatorBoolean(array('required' => false)),
      'p_ent_new'   => new sfValidatorBoolean(array('required' => false)),
      'p_aju_comi'  => new sfValidatorBoolean(array('required' => false)),
      'p_doble_un'  => new sfValidatorBoolean(array('required' => false)),
      'p_pront_pg'  => new sfValidatorBoolean(array('required' => false)),
      'p_grab_ren'  => new sfValidatorBoolean(array('required' => false)),
      'p_para1'     => new sfValidatorBoolean(array('required' => false)),
      'p_para2'     => new sfValidatorBoolean(array('required' => false)),
      'p_para3'     => new sfValidatorBoolean(array('required' => false)),
      'p_para4'     => new sfValidatorBoolean(array('required' => false)),
      'p_para5'     => new sfValidatorBoolean(array('required' => false)),
      'p_para6'     => new sfValidatorBoolean(array('required' => false)),
      'p_para7'     => new sfValidatorBoolean(array('required' => false)),
      'p_para8'     => new sfValidatorBoolean(array('required' => false)),
      'p_para9'     => new sfValidatorBoolean(array('required' => false)),
      'p_para10'    => new sfValidatorBoolean(array('required' => false)),
      'p_open_com'  => new sfValidatorBoolean(array('required' => false)),
      'p_marg_cap'  => new sfValidatorBoolean(array('required' => false)),
      'p_dir_ent'   => new sfValidatorBoolean(array('required' => false)),
      'p_art_20'    => new sfValidatorBoolean(array('required' => false)),
      'p_imp_kit'   => new sfValidatorBoolean(array('required' => false)),
      'p_red_com'   => new sfValidatorBoolean(array('required' => false)),
      'p_cyf_dol'   => new sfValidatorBoolean(array('required' => false)),
      'p_ser_art'   => new sfValidatorBoolean(array('required' => false)),
      'p_art_dol'   => new sfValidatorBoolean(array('required' => false)),
      'mone_art'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'p_deb_ban'   => new sfValidatorBoolean(array('required' => false)),
      'p_deb_aut'   => new sfValidatorBoolean(array('required' => false)),
      'p_fact_alm'  => new sfValidatorBoolean(array('required' => false)),
      'p_despacho'  => new sfValidatorBoolean(array('required' => false)),
      'p_idb'       => new sfValidatorBoolean(array('required' => false)),
      'val_idb'     => new sfValidatorNumber(array('required' => false)),
      'tempor1'     => new sfValidatorInteger(array('required' => false)),
      'fecha_res'   => new sfValidatorDateTime(array('required' => false)),
      'fecha_fisi'  => new sfValidatorDateTime(array('required' => false)),
      'open_fisi'   => new sfValidatorBoolean(array('required' => false)),
      'serial'      => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'cadena'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'inv_emp'     => new sfValidatorString(array('max_length' => 250, 'required' => false)),
      'temp_char'   => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'fec_inte'    => new sfValidatorDateTime(array('required' => false)),
      'temp_fech'   => new sfValidatorDateTime(array('required' => false)),
      'ele_linea'   => new sfValidatorBoolean(array('required' => false)),
      'lon_linea'   => new sfValidatorInteger(array('required' => false)),
      'ele_categ'   => new sfValidatorBoolean(array('required' => false)),
      'lon_categ'   => new sfValidatorInteger(array('required' => false)),
      'ele_medid'   => new sfValidatorBoolean(array('required' => false)),
      'lon_medid'   => new sfValidatorInteger(array('required' => false)),
      'ele_item'    => new sfValidatorBoolean(array('required' => false)),
      'lon_item'    => new sfValidatorInteger(array('required' => false)),
      'ele_color'   => new sfValidatorBoolean(array('required' => false)),
      'lon_color'   => new sfValidatorInteger(array('required' => false)),
      'ele_carter'  => new sfValidatorBoolean(array('required' => false)),
      'caracter'    => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'dec_prec'    => new sfValidatorInteger(array('required' => false)),
      'dec_cost'    => new sfValidatorInteger(array('required' => false)),
      'cant_art'    => new sfValidatorInteger(array('required' => false)),
      'total_cod'   => new sfValidatorInteger(array('required' => false)),
      'tipo_com'    => new sfValidatorBoolean(array('required' => false)),
      'tipo_lib'    => new sfValidatorBoolean(array('required' => false)),
      'co_us_in'    => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_in'    => new sfValidatorDateTime(array('required' => false)),
      'co_us_mo'    => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_mo'    => new sfValidatorDateTime(array('required' => false)),
      'logo'        => new sfValidatorString(array('required' => false)),
      'revisado'    => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'trasnfe'     => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'p_sucursal'  => new sfValidatorBoolean(array('required' => false)),
      'rowguid'     => new sfValidatorString(array('max_length' => 36, 'required' => false)),
      'p_licores'   => new sfValidatorBoolean(array('required' => false)),
      'p_lotenro'   => new sfValidatorBoolean(array('required' => false)),
      'p_lotefec'   => new sfValidatorBoolean(array('required' => false)),
      'serverolap'  => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'dataolap'    => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'p_loteaut'   => new sfValidatorBoolean(array('required' => false)),
      'tipo_inve'   => new sfValidatorNumber(array('required' => false)),
      'aju_posm'    => new sfValidatorInteger(array('required' => false)),
      'aju_posa'    => new sfValidatorInteger(array('required' => false)),
      'aju_negm'    => new sfValidatorInteger(array('required' => false)),
      'aju_nega'    => new sfValidatorInteger(array('required' => false)),
      'aju_posmc'   => new sfValidatorInteger(array('required' => false)),
      'aju_posac'   => new sfValidatorInteger(array('required' => false)),
      'aju_negmc'   => new sfValidatorInteger(array('required' => false)),
      'aju_negac'   => new sfValidatorInteger(array('required' => false)),
      'plv_num'     => new sfValidatorInteger(array('required' => false)),
      'plc_num'     => new sfValidatorInteger(array('required' => false)),
      'pventa'      => new sfValidatorInteger(array('required' => false)),
      'turnosic'    => new sfValidatorInteger(array('required' => false)),
      'tabislr'     => new sfValidatorInteger(array('required' => false)),
      'moneda'      => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'imp_num'     => new sfValidatorInteger(array('required' => false)),
      'rma_cli'     => new sfValidatorInteger(array('required' => false)),
      'rma_prov'    => new sfValidatorInteger(array('required' => false)),
      'rma_entc'    => new sfValidatorInteger(array('required' => false)),
      'rma_entp'    => new sfValidatorInteger(array('required' => false)),
      'rma_regs'    => new sfValidatorInteger(array('required' => false)),
      'p_prov_new'  => new sfValidatorBoolean(array('required' => false)),
      'p_ser_new'   => new sfValidatorBoolean(array('required' => false)),
      'rmacliente'  => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'rma_trans'   => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'garantia'    => new sfValidatorString(array('max_length' => 8, 'required' => false)),
      'reem_prov'   => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'des_ser'     => new sfValidatorString(array('max_length' => 12, 'required' => false)),
      'ser_auto'    => new sfValidatorNumber(array('required' => false)),
      'pcontrol_1'  => new sfValidatorBoolean(array('required' => false)),
      'pcontrol_2'  => new sfValidatorBoolean(array('required' => false)),
      'pcontrol_3'  => new sfValidatorBoolean(array('required' => false)),
      'pcontrol_4'  => new sfValidatorBoolean(array('required' => false)),
      'pcontrol_5'  => new sfValidatorBoolean(array('required' => false)),
      'idioma'      => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'serie'       => new sfValidatorBoolean(array('required' => false)),
      'aux01'       => new sfValidatorNumber(array('required' => false)),
      'aux02'       => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'eprofit'     => new sfValidatorBoolean(array('required' => false)),
      'pais'        => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'emp_num'     => new sfValidatorInteger(array('required' => false)),
      'dmc_num'     => new sfValidatorInteger(array('required' => false)),
      'tax_num'     => new sfValidatorInteger(array('required' => false)),
      'ced_num'     => new sfValidatorInteger(array('required' => false)),
      'ent_num'     => new sfValidatorInteger(array('required' => false)),
      'artinmp'     => new sfValidatorBoolean(array('required' => false)),
      'tip_costo'   => new sfValidatorInteger(array('required' => false)),
      'tip_cmat'    => new sfValidatorInteger(array('required' => false)),
      'co_aent'     => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'cie_num'     => new sfValidatorInteger(array('required' => false)),
      'odp_num'     => new sfValidatorInteger(array('required' => false)),
      'req_num'     => new sfValidatorInteger(array('required' => false)),
      'dev_num'     => new sfValidatorInteger(array('required' => false)),
      'co_asal'     => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'devmax'      => new sfValidatorBoolean(array('required' => false)),
      'exp_num'     => new sfValidatorInteger(array('required' => false)),
      'inp_num'     => new sfValidatorInteger(array('required' => false)),
      'cost_num'    => new sfValidatorInteger(array('required' => false)),
      'par_num'     => new sfValidatorInteger(array('required' => false)),
      'esc_num'     => new sfValidatorInteger(array('required' => false)),
      'cierre_mes'  => new sfValidatorBoolean(array('required' => false)),
      'pla_num'     => new sfValidatorInteger(array('required' => false)),
      'men_num'     => new sfValidatorInteger(array('required' => false)),
      'tipcosdev'   => new sfValidatorInteger(array('required' => false)),
      'max_lin'     => new sfValidatorInteger(array('required' => false)),
      'dist_num'    => new sfValidatorInteger(array('required' => false)),
      'exp_numi'    => new sfValidatorInteger(array('required' => false)),
      'p_imp65'     => new sfValidatorBoolean(array('required' => false)),
      'val_max'     => new sfValidatorBoolean(array('required' => false)),
      'server'      => new sfValidatorString(array('max_length' => 32, 'required' => false)),
      'namedb'      => new sfValidatorString(array('max_length' => 32, 'required' => false)),
      'login'       => new sfValidatorString(array('max_length' => 32, 'required' => false)),
      'password'    => new sfValidatorString(array('max_length' => 32, 'required' => false)),
      'man_impr'    => new sfValidatorBoolean(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('par_emp[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'ParEmp';
  }

}
