<?php

/**
 * Ambart form base class.
 *
 * @method Ambart getObject() Returns the current form's model object
 *
 * @package    gesser
 * @subpackage form
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 29553 2010-05-20 14:33:00Z Kris.Wallsmith $
 */
abstract class BaseAmbartForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'amb_usua'    => new sfWidgetFormInputHidden(),
      'co_artv'     => new sfWidgetFormInputCheckbox(),
      'art_desv'    => new sfWidgetFormInputCheckbox(),
      'fecha_regv'  => new sfWidgetFormInputCheckbox(),
      'manj_serv'   => new sfWidgetFormInputCheckbox(),
      'co_lind'     => new sfWidgetFormInputCheckbox(),
      'co_linv'     => new sfWidgetFormInputCheckbox(),
      'co_lin'      => new sfWidgetFormInputText(),
      'co_catd'     => new sfWidgetFormInputCheckbox(),
      'co_catv'     => new sfWidgetFormInputCheckbox(),
      'co_cat'      => new sfWidgetFormInputText(),
      'co_subld'    => new sfWidgetFormInputCheckbox(),
      'co_sublv'    => new sfWidgetFormInputCheckbox(),
      'co_subl'     => new sfWidgetFormInputText(),
      'co_colord'   => new sfWidgetFormInputCheckbox(),
      'co_colorv'   => new sfWidgetFormInputCheckbox(),
      'co_color'    => new sfWidgetFormInputText(),
      'itemv'       => new sfWidgetFormInputCheckbox(),
      'refv'        => new sfWidgetFormInputCheckbox(),
      'modelov'     => new sfWidgetFormInputCheckbox(),
      'procedencd'  => new sfWidgetFormInputCheckbox(),
      'procedencv'  => new sfWidgetFormInputCheckbox(),
      'procedenci'  => new sfWidgetFormInputText(),
      'comentariv'  => new sfWidgetFormInputCheckbox(),
      'co_provd'    => new sfWidgetFormInputCheckbox(),
      'co_provv'    => new sfWidgetFormInputCheckbox(),
      'co_prov'     => new sfWidgetFormInputText(),
      'ubicacionv'  => new sfWidgetFormInputCheckbox(),
      'relac_autd'  => new sfWidgetFormInputCheckbox(),
      'relac_autv'  => new sfWidgetFormInputCheckbox(),
      'relac_aut'   => new sfWidgetFormInputText(),
      'pto_pedidv'  => new sfWidgetFormInputCheckbox(),
      'stock_maxv'  => new sfWidgetFormInputCheckbox(),
      'stock_minv'  => new sfWidgetFormInputCheckbox(),
      'prec_omv'    => new sfWidgetFormInputCheckbox(),
      'prec_vta1v'  => new sfWidgetFormInputCheckbox(),
      'prec_vta2v'  => new sfWidgetFormInputCheckbox(),
      'prec_vta3v'  => new sfWidgetFormInputCheckbox(),
      'prec_vta4v'  => new sfWidgetFormInputCheckbox(),
      'prec_vta5v'  => new sfWidgetFormInputCheckbox(),
      'prec_agr1v'  => new sfWidgetFormInputCheckbox(),
      'prec_agr2v'  => new sfWidgetFormInputCheckbox(),
      'prec_agr3v'  => new sfWidgetFormInputCheckbox(),
      'prec_agr4v'  => new sfWidgetFormInputCheckbox(),
      'prec_agr5v'  => new sfWidgetFormInputCheckbox(),
      'can_agrv'    => new sfWidgetFormInputCheckbox(),
      'marg_minv'   => new sfWidgetFormInputCheckbox(),
      'ult_cos_v'   => new sfWidgetFormInputCheckbox(),
      'cos_pro_v'   => new sfWidgetFormInputCheckbox(),
      'cos_merc_v'  => new sfWidgetFormInputCheckbox(),
      'cos_prov_v'  => new sfWidgetFormInputCheckbox(),
      'ult_cosdov'  => new sfWidgetFormInputCheckbox(),
      'cos_unanv'   => new sfWidgetFormInputCheckbox(),
      'ult_cosomv'  => new sfWidgetFormInputCheckbox(),
      'cos_proomv'  => new sfWidgetFormInputCheckbox(),
      'fec_proomv'  => new sfWidgetFormInputCheckbox(),
      'tipo_cosd'   => new sfWidgetFormInputCheckbox(),
      'tipo_cosv'   => new sfWidgetFormInputCheckbox(),
      'tipo_cos'    => new sfWidgetFormInputText(),
      'mont_comiv'  => new sfWidgetFormInputCheckbox(),
      'punt_cliv'   => new sfWidgetFormInputCheckbox(),
      'punt_prov'   => new sfWidgetFormInputCheckbox(),
      'anuladov'    => new sfWidgetFormInputCheckbox(),
      'tipo_impd'   => new sfWidgetFormInputCheckbox(),
      'tipo_impv'   => new sfWidgetFormInputCheckbox(),
      'tipo_imp'    => new sfWidgetFormInputText(),
      'licorv'      => new sfWidgetFormInputCheckbox(),
      'picturev'    => new sfWidgetFormInputCheckbox(),
      'campo1'      => new sfWidgetFormInputText(),
      'campo2'      => new sfWidgetFormInputText(),
      'campo3'      => new sfWidgetFormInputText(),
      'campo4'      => new sfWidgetFormInputText(),
      'campo5'      => new sfWidgetFormInputText(),
      'campo6'      => new sfWidgetFormInputText(),
      'campo7'      => new sfWidgetFormInputText(),
      'campo8'      => new sfWidgetFormInputText(),
      'co_us_in'    => new sfWidgetFormInputText(),
      'fe_us_in'    => new sfWidgetFormDateTime(),
      'co_us_mo'    => new sfWidgetFormInputText(),
      'fe_us_mo'    => new sfWidgetFormDateTime(),
      'co_us_el'    => new sfWidgetFormInputText(),
      'fe_us_el'    => new sfWidgetFormDateTime(),
      'revisado'    => new sfWidgetFormInputText(),
      'trasnfe'     => new sfWidgetFormInputText(),
      'co_sucu'     => new sfWidgetFormInputText(),
      'pesov'       => new sfWidgetFormInputCheckbox(),
      'piev'        => new sfWidgetFormInputCheckbox(),
      'margen1v'    => new sfWidgetFormInputCheckbox(),
      'margen2v'    => new sfWidgetFormInputCheckbox(),
      'margen3v'    => new sfWidgetFormInputCheckbox(),
      'margen4v'    => new sfWidgetFormInputCheckbox(),
      'margen5v'    => new sfWidgetFormInputCheckbox(),
      'tipod'       => new sfWidgetFormInputCheckbox(),
      'tipov'       => new sfWidgetFormInputCheckbox(),
      'tipo'        => new sfWidgetFormInputText(),
      'lotev'       => new sfWidgetFormInputCheckbox(),
      'reactivar'   => new sfWidgetFormInputCheckbox(),
      'relacartv'   => new sfWidgetFormInputCheckbox(),
      'porc_adiv'   => new sfWidgetFormInputCheckbox(),
      'garantiav'   => new sfWidgetFormInputCheckbox(),
      'rowguid'     => new sfWidgetFormInputText(),
      'bt_preclote' => new sfWidgetFormInputCheckbox(),
      'art_desiv'   => new sfWidgetFormInputCheckbox(),
      'imagen1v'    => new sfWidgetFormInputCheckbox(),
      'imagen2v'    => new sfWidgetFormInputCheckbox(),
      'bt_aranc'    => new sfWidgetFormInputCheckbox(),
    ));

    $this->setValidators(array(
      'amb_usua'    => new sfValidatorChoice(array('choices' => array($this->getObject()->get('amb_usua')), 'empty_value' => $this->getObject()->get('amb_usua'), 'required' => false)),
      'co_artv'     => new sfValidatorBoolean(array('required' => false)),
      'art_desv'    => new sfValidatorBoolean(array('required' => false)),
      'fecha_regv'  => new sfValidatorBoolean(array('required' => false)),
      'manj_serv'   => new sfValidatorBoolean(array('required' => false)),
      'co_lind'     => new sfValidatorBoolean(array('required' => false)),
      'co_linv'     => new sfValidatorBoolean(array('required' => false)),
      'co_lin'      => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'co_catd'     => new sfValidatorBoolean(array('required' => false)),
      'co_catv'     => new sfValidatorBoolean(array('required' => false)),
      'co_cat'      => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'co_subld'    => new sfValidatorBoolean(array('required' => false)),
      'co_sublv'    => new sfValidatorBoolean(array('required' => false)),
      'co_subl'     => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'co_colord'   => new sfValidatorBoolean(array('required' => false)),
      'co_colorv'   => new sfValidatorBoolean(array('required' => false)),
      'co_color'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'itemv'       => new sfValidatorBoolean(array('required' => false)),
      'refv'        => new sfValidatorBoolean(array('required' => false)),
      'modelov'     => new sfValidatorBoolean(array('required' => false)),
      'procedencd'  => new sfValidatorBoolean(array('required' => false)),
      'procedencv'  => new sfValidatorBoolean(array('required' => false)),
      'procedenci'  => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'comentariv'  => new sfValidatorBoolean(array('required' => false)),
      'co_provd'    => new sfValidatorBoolean(array('required' => false)),
      'co_provv'    => new sfValidatorBoolean(array('required' => false)),
      'co_prov'     => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'ubicacionv'  => new sfValidatorBoolean(array('required' => false)),
      'relac_autd'  => new sfValidatorBoolean(array('required' => false)),
      'relac_autv'  => new sfValidatorBoolean(array('required' => false)),
      'relac_aut'   => new sfValidatorInteger(array('required' => false)),
      'pto_pedidv'  => new sfValidatorBoolean(array('required' => false)),
      'stock_maxv'  => new sfValidatorBoolean(array('required' => false)),
      'stock_minv'  => new sfValidatorBoolean(array('required' => false)),
      'prec_omv'    => new sfValidatorBoolean(array('required' => false)),
      'prec_vta1v'  => new sfValidatorBoolean(array('required' => false)),
      'prec_vta2v'  => new sfValidatorBoolean(array('required' => false)),
      'prec_vta3v'  => new sfValidatorBoolean(array('required' => false)),
      'prec_vta4v'  => new sfValidatorBoolean(array('required' => false)),
      'prec_vta5v'  => new sfValidatorBoolean(array('required' => false)),
      'prec_agr1v'  => new sfValidatorBoolean(array('required' => false)),
      'prec_agr2v'  => new sfValidatorBoolean(array('required' => false)),
      'prec_agr3v'  => new sfValidatorBoolean(array('required' => false)),
      'prec_agr4v'  => new sfValidatorBoolean(array('required' => false)),
      'prec_agr5v'  => new sfValidatorBoolean(array('required' => false)),
      'can_agrv'    => new sfValidatorBoolean(array('required' => false)),
      'marg_minv'   => new sfValidatorBoolean(array('required' => false)),
      'ult_cos_v'   => new sfValidatorBoolean(array('required' => false)),
      'cos_pro_v'   => new sfValidatorBoolean(array('required' => false)),
      'cos_merc_v'  => new sfValidatorBoolean(array('required' => false)),
      'cos_prov_v'  => new sfValidatorBoolean(array('required' => false)),
      'ult_cosdov'  => new sfValidatorBoolean(array('required' => false)),
      'cos_unanv'   => new sfValidatorBoolean(array('required' => false)),
      'ult_cosomv'  => new sfValidatorBoolean(array('required' => false)),
      'cos_proomv'  => new sfValidatorBoolean(array('required' => false)),
      'fec_proomv'  => new sfValidatorBoolean(array('required' => false)),
      'tipo_cosd'   => new sfValidatorBoolean(array('required' => false)),
      'tipo_cosv'   => new sfValidatorBoolean(array('required' => false)),
      'tipo_cos'    => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'mont_comiv'  => new sfValidatorBoolean(array('required' => false)),
      'punt_cliv'   => new sfValidatorBoolean(array('required' => false)),
      'punt_prov'   => new sfValidatorBoolean(array('required' => false)),
      'anuladov'    => new sfValidatorBoolean(array('required' => false)),
      'tipo_impd'   => new sfValidatorBoolean(array('required' => false)),
      'tipo_impv'   => new sfValidatorBoolean(array('required' => false)),
      'tipo_imp'    => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'licorv'      => new sfValidatorBoolean(array('required' => false)),
      'picturev'    => new sfValidatorBoolean(array('required' => false)),
      'campo1'      => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo2'      => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo3'      => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo4'      => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo5'      => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo6'      => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo7'      => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo8'      => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'co_us_in'    => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_in'    => new sfValidatorDateTime(array('required' => false)),
      'co_us_mo'    => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_mo'    => new sfValidatorDateTime(array('required' => false)),
      'co_us_el'    => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_el'    => new sfValidatorDateTime(array('required' => false)),
      'revisado'    => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'trasnfe'     => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'co_sucu'     => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'pesov'       => new sfValidatorBoolean(array('required' => false)),
      'piev'        => new sfValidatorBoolean(array('required' => false)),
      'margen1v'    => new sfValidatorBoolean(array('required' => false)),
      'margen2v'    => new sfValidatorBoolean(array('required' => false)),
      'margen3v'    => new sfValidatorBoolean(array('required' => false)),
      'margen4v'    => new sfValidatorBoolean(array('required' => false)),
      'margen5v'    => new sfValidatorBoolean(array('required' => false)),
      'tipod'       => new sfValidatorBoolean(array('required' => false)),
      'tipov'       => new sfValidatorBoolean(array('required' => false)),
      'tipo'        => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'lotev'       => new sfValidatorBoolean(array('required' => false)),
      'reactivar'   => new sfValidatorBoolean(array('required' => false)),
      'relacartv'   => new sfValidatorBoolean(array('required' => false)),
      'porc_adiv'   => new sfValidatorBoolean(array('required' => false)),
      'garantiav'   => new sfValidatorBoolean(array('required' => false)),
      'rowguid'     => new sfValidatorString(array('max_length' => 36, 'required' => false)),
      'bt_preclote' => new sfValidatorBoolean(array('required' => false)),
      'art_desiv'   => new sfValidatorBoolean(array('required' => false)),
      'imagen1v'    => new sfValidatorBoolean(array('required' => false)),
      'imagen2v'    => new sfValidatorBoolean(array('required' => false)),
      'bt_aranc'    => new sfValidatorBoolean(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('ambart[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Ambart';
  }

}
