<?php

/**
 * RmaAmb form base class.
 *
 * @method RmaAmb getObject() Returns the current form's model object
 *
 * @package    gesser
 * @subpackage form
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 29553 2010-05-20 14:33:00Z Kris.Wallsmith $
 */
abstract class BaseRmaAmbForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id'         => new sfWidgetFormInputHidden(),
      'amb_usua'   => new sfWidgetFormInputText(),
      'amb_rma'    => new sfWidgetFormInputText(),
      'rma_num'    => new sfWidgetFormInputCheckbox(),
      'nro_ent_pr' => new sfWidgetFormInputCheckbox(),
      'fec_emis'   => new sfWidgetFormInputCheckbox(),
      'vco_cli'    => new sfWidgetFormInputText(),
      'dco_cli'    => new sfWidgetFormInputCheckbox(),
      'co_cli'     => new sfWidgetFormInputCheckbox(),
      'rma_prov'   => new sfWidgetFormInputCheckbox(),
      'vco_tran'   => new sfWidgetFormInputText(),
      'dco_tran'   => new sfWidgetFormInputCheckbox(),
      'co_tran'    => new sfWidgetFormInputCheckbox(),
      'descrip'    => new sfWidgetFormInputCheckbox(),
      'vmoneda'    => new sfWidgetFormInputText(),
      'dmoneda'    => new sfWidgetFormInputCheckbox(),
      'moneda'     => new sfWidgetFormInputCheckbox(),
      'vreng_1'    => new sfWidgetFormInputText(),
      'dreng_1'    => new sfWidgetFormInputCheckbox(),
      'reng_1'     => new sfWidgetFormInputCheckbox(),
      'vreng_2'    => new sfWidgetFormInputText(),
      'dreng_2'    => new sfWidgetFormInputCheckbox(),
      'reng_2'     => new sfWidgetFormInputCheckbox(),
      'vreng_3'    => new sfWidgetFormInputText(),
      'dreng_3'    => new sfWidgetFormInputCheckbox(),
      'reng_3'     => new sfWidgetFormInputCheckbox(),
      'b_art'      => new sfWidgetFormInputCheckbox(),
      'b_importar' => new sfWidgetFormInputCheckbox(),
      'b_seriales' => new sfWidgetFormInputCheckbox(),
      'b_anular'   => new sfWidgetFormInputCheckbox(),
      'b_procesar' => new sfWidgetFormInputCheckbox(),
      'b_reversar' => new sfWidgetFormInputCheckbox(),
      'b_clien'    => new sfWidgetFormInputCheckbox(),
      'tamcol01'   => new sfWidgetFormInputText(),
      'tamcol02'   => new sfWidgetFormInputText(),
      'tamcol03'   => new sfWidgetFormInputText(),
      'tamcol04'   => new sfWidgetFormInputText(),
      'tamcol05'   => new sfWidgetFormInputText(),
      'tamcol06'   => new sfWidgetFormInputText(),
      'tamcol07'   => new sfWidgetFormInputText(),
      'tamcol08'   => new sfWidgetFormInputText(),
      'tamcol09'   => new sfWidgetFormInputText(),
      'tamcol10'   => new sfWidgetFormInputText(),
      'tamcol11'   => new sfWidgetFormInputText(),
      'tamcol12'   => new sfWidgetFormInputText(),
      'tamcol13'   => new sfWidgetFormInputText(),
      'tamcol14'   => new sfWidgetFormInputText(),
      'tamcol15'   => new sfWidgetFormInputText(),
      'tamcol16'   => new sfWidgetFormInputText(),
      'tamcol17'   => new sfWidgetFormInputText(),
      'tamcol18'   => new sfWidgetFormInputText(),
      'tamcol19'   => new sfWidgetFormInputText(),
      'tamcol20'   => new sfWidgetFormInputText(),
      'tamcol21'   => new sfWidgetFormInputText(),
      'tamcol22'   => new sfWidgetFormInputText(),
      'poscol01'   => new sfWidgetFormInputText(),
      'poscol02'   => new sfWidgetFormInputText(),
      'poscol03'   => new sfWidgetFormInputText(),
      'poscol04'   => new sfWidgetFormInputText(),
      'poscol05'   => new sfWidgetFormInputText(),
      'poscol06'   => new sfWidgetFormInputText(),
      'poscol07'   => new sfWidgetFormInputText(),
      'poscol08'   => new sfWidgetFormInputText(),
      'poscol09'   => new sfWidgetFormInputText(),
      'poscol10'   => new sfWidgetFormInputText(),
      'poscol11'   => new sfWidgetFormInputText(),
      'poscol12'   => new sfWidgetFormInputText(),
      'poscol13'   => new sfWidgetFormInputText(),
      'poscol14'   => new sfWidgetFormInputText(),
      'poscol15'   => new sfWidgetFormInputText(),
      'poscol16'   => new sfWidgetFormInputText(),
      'poscol17'   => new sfWidgetFormInputText(),
      'poscol18'   => new sfWidgetFormInputText(),
      'poscol19'   => new sfWidgetFormInputText(),
      'poscol20'   => new sfWidgetFormInputText(),
      'poscol21'   => new sfWidgetFormInputText(),
      'poscol22'   => new sfWidgetFormInputText(),
      'pseriales'  => new sfWidgetFormInputCheckbox(),
      'pnvo_prov'  => new sfWidgetFormInputCheckbox(),
      'camb_doc'   => new sfWidgetFormInputCheckbox(),
      'sin_docu'   => new sfWidgetFormInputCheckbox(),
      'gar_venc'   => new sfWidgetFormInputCheckbox(),
      'ser_nulo'   => new sfWidgetFormInputCheckbox(),
      'saldo'      => new sfWidgetFormInputCheckbox(),
      'fvenc'      => new sfWidgetFormInputCheckbox(),
      'chdev'      => new sfWidgetFormInputCheckbox(),
      'camb_art'   => new sfWidgetFormInputCheckbox(),
      'entc_art'   => new sfWidgetFormInputCheckbox(),
      'listar'     => new sfWidgetFormInputText(),
      'num_listar' => new sfWidgetFormInputText(),
      'numcopia'   => new sfWidgetFormInputText(),
      'campo1'     => new sfWidgetFormInputText(),
      'campo2'     => new sfWidgetFormInputText(),
      'campo3'     => new sfWidgetFormInputText(),
      'campo4'     => new sfWidgetFormInputText(),
      'campo5'     => new sfWidgetFormInputText(),
      'campo6'     => new sfWidgetFormInputText(),
      'campo7'     => new sfWidgetFormInputText(),
      'campo8'     => new sfWidgetFormInputText(),
      'co_us_in'   => new sfWidgetFormInputText(),
      'fe_us_in'   => new sfWidgetFormDateTime(),
      'co_us_mo'   => new sfWidgetFormInputText(),
      'fe_us_mo'   => new sfWidgetFormDateTime(),
      'co_us_el'   => new sfWidgetFormInputText(),
      'fe_us_el'   => new sfWidgetFormDateTime(),
      'revisado'   => new sfWidgetFormInputText(),
      'trasnfe'    => new sfWidgetFormInputText(),
      'co_sucu'    => new sfWidgetFormInputText(),
      'rowguid'    => new sfWidgetFormInputText(),
    ));

    $this->setValidators(array(
      'id'         => new sfValidatorChoice(array('choices' => array($this->getObject()->get('id')), 'empty_value' => $this->getObject()->get('id'), 'required' => false)),
      'amb_usua'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'amb_rma'    => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'rma_num'    => new sfValidatorBoolean(array('required' => false)),
      'nro_ent_pr' => new sfValidatorBoolean(array('required' => false)),
      'fec_emis'   => new sfValidatorBoolean(array('required' => false)),
      'vco_cli'    => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'dco_cli'    => new sfValidatorBoolean(array('required' => false)),
      'co_cli'     => new sfValidatorBoolean(array('required' => false)),
      'rma_prov'   => new sfValidatorBoolean(array('required' => false)),
      'vco_tran'   => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'dco_tran'   => new sfValidatorBoolean(array('required' => false)),
      'co_tran'    => new sfValidatorBoolean(array('required' => false)),
      'descrip'    => new sfValidatorBoolean(array('required' => false)),
      'vmoneda'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'dmoneda'    => new sfValidatorBoolean(array('required' => false)),
      'moneda'     => new sfValidatorBoolean(array('required' => false)),
      'vreng_1'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'dreng_1'    => new sfValidatorBoolean(array('required' => false)),
      'reng_1'     => new sfValidatorBoolean(array('required' => false)),
      'vreng_2'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'dreng_2'    => new sfValidatorBoolean(array('required' => false)),
      'reng_2'     => new sfValidatorBoolean(array('required' => false)),
      'vreng_3'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'dreng_3'    => new sfValidatorBoolean(array('required' => false)),
      'reng_3'     => new sfValidatorBoolean(array('required' => false)),
      'b_art'      => new sfValidatorBoolean(array('required' => false)),
      'b_importar' => new sfValidatorBoolean(array('required' => false)),
      'b_seriales' => new sfValidatorBoolean(array('required' => false)),
      'b_anular'   => new sfValidatorBoolean(array('required' => false)),
      'b_procesar' => new sfValidatorBoolean(array('required' => false)),
      'b_reversar' => new sfValidatorBoolean(array('required' => false)),
      'b_clien'    => new sfValidatorBoolean(array('required' => false)),
      'tamcol01'   => new sfValidatorInteger(array('required' => false)),
      'tamcol02'   => new sfValidatorInteger(array('required' => false)),
      'tamcol03'   => new sfValidatorInteger(array('required' => false)),
      'tamcol04'   => new sfValidatorInteger(array('required' => false)),
      'tamcol05'   => new sfValidatorInteger(array('required' => false)),
      'tamcol06'   => new sfValidatorInteger(array('required' => false)),
      'tamcol07'   => new sfValidatorInteger(array('required' => false)),
      'tamcol08'   => new sfValidatorInteger(array('required' => false)),
      'tamcol09'   => new sfValidatorInteger(array('required' => false)),
      'tamcol10'   => new sfValidatorInteger(array('required' => false)),
      'tamcol11'   => new sfValidatorInteger(array('required' => false)),
      'tamcol12'   => new sfValidatorInteger(array('required' => false)),
      'tamcol13'   => new sfValidatorInteger(array('required' => false)),
      'tamcol14'   => new sfValidatorInteger(array('required' => false)),
      'tamcol15'   => new sfValidatorInteger(array('required' => false)),
      'tamcol16'   => new sfValidatorInteger(array('required' => false)),
      'tamcol17'   => new sfValidatorInteger(array('required' => false)),
      'tamcol18'   => new sfValidatorInteger(array('required' => false)),
      'tamcol19'   => new sfValidatorInteger(array('required' => false)),
      'tamcol20'   => new sfValidatorInteger(array('required' => false)),
      'tamcol21'   => new sfValidatorInteger(array('required' => false)),
      'tamcol22'   => new sfValidatorInteger(array('required' => false)),
      'poscol01'   => new sfValidatorInteger(array('required' => false)),
      'poscol02'   => new sfValidatorInteger(array('required' => false)),
      'poscol03'   => new sfValidatorInteger(array('required' => false)),
      'poscol04'   => new sfValidatorInteger(array('required' => false)),
      'poscol05'   => new sfValidatorInteger(array('required' => false)),
      'poscol06'   => new sfValidatorInteger(array('required' => false)),
      'poscol07'   => new sfValidatorInteger(array('required' => false)),
      'poscol08'   => new sfValidatorInteger(array('required' => false)),
      'poscol09'   => new sfValidatorInteger(array('required' => false)),
      'poscol10'   => new sfValidatorInteger(array('required' => false)),
      'poscol11'   => new sfValidatorInteger(array('required' => false)),
      'poscol12'   => new sfValidatorInteger(array('required' => false)),
      'poscol13'   => new sfValidatorInteger(array('required' => false)),
      'poscol14'   => new sfValidatorInteger(array('required' => false)),
      'poscol15'   => new sfValidatorInteger(array('required' => false)),
      'poscol16'   => new sfValidatorInteger(array('required' => false)),
      'poscol17'   => new sfValidatorInteger(array('required' => false)),
      'poscol18'   => new sfValidatorInteger(array('required' => false)),
      'poscol19'   => new sfValidatorInteger(array('required' => false)),
      'poscol20'   => new sfValidatorInteger(array('required' => false)),
      'poscol21'   => new sfValidatorInteger(array('required' => false)),
      'poscol22'   => new sfValidatorInteger(array('required' => false)),
      'pseriales'  => new sfValidatorBoolean(array('required' => false)),
      'pnvo_prov'  => new sfValidatorBoolean(array('required' => false)),
      'camb_doc'   => new sfValidatorBoolean(array('required' => false)),
      'sin_docu'   => new sfValidatorBoolean(array('required' => false)),
      'gar_venc'   => new sfValidatorBoolean(array('required' => false)),
      'ser_nulo'   => new sfValidatorBoolean(array('required' => false)),
      'saldo'      => new sfValidatorBoolean(array('required' => false)),
      'fvenc'      => new sfValidatorBoolean(array('required' => false)),
      'chdev'      => new sfValidatorBoolean(array('required' => false)),
      'camb_art'   => new sfValidatorBoolean(array('required' => false)),
      'entc_art'   => new sfValidatorBoolean(array('required' => false)),
      'listar'     => new sfValidatorInteger(array('required' => false)),
      'num_listar' => new sfValidatorInteger(array('required' => false)),
      'numcopia'   => new sfValidatorInteger(array('required' => false)),
      'campo1'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo2'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo3'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo4'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo5'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo6'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo7'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'campo8'     => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'co_us_in'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_in'   => new sfValidatorDateTime(array('required' => false)),
      'co_us_mo'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_mo'   => new sfValidatorDateTime(array('required' => false)),
      'co_us_el'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_el'   => new sfValidatorDateTime(array('required' => false)),
      'revisado'   => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'trasnfe'    => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'co_sucu'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'rowguid'    => new sfValidatorString(array('max_length' => 36, 'required' => false)),
    ));

    $this->widgetSchema->setNameFormat('rma_amb[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'RmaAmb';
  }

}
