<?php

/**
 * Art form base class.
 *
 * @method Art getObject() Returns the current form's model object
 *
 * @package    gesser
 * @subpackage form
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 29553 2010-05-20 14:33:00Z Kris.Wallsmith $
 */
abstract class BaseArtForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'co_art'     => new sfWidgetFormInputHidden(),
      'art_des'    => new sfWidgetFormInputText(),
      'fecha_reg'  => new sfWidgetFormDateTime(),
      'manj_ser'   => new sfWidgetFormInputCheckbox(),
      'co_lin'     => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('LinArt'), 'add_empty' => false)),
      'co_cat'     => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('CatArt'), 'add_empty' => false)),
      'co_subl'    => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('SubLin_4'), 'add_empty' => false)),
      'co_color'   => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Colores'), 'add_empty' => false)),
      'item'       => new sfWidgetFormInputText(),
      'ref'        => new sfWidgetFormInputText(),
      'modelo'     => new sfWidgetFormInputText(),
      'procedenci' => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Proceden'), 'add_empty' => false)),
      'comentario' => new sfWidgetFormTextarea(),
      'co_prov'    => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Prov'), 'add_empty' => false)),
      'ubicacion'  => new sfWidgetFormInputText(),
      'uni_venta'  => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Unidades'), 'add_empty' => false)),
      'uni_compra' => new sfWidgetFormInputText(),
      'uni_relac'  => new sfWidgetFormInputText(),
      'relac_aut'  => new sfWidgetFormInputText(),
      'stock_act'  => new sfWidgetFormInputText(),
      'stock_com'  => new sfWidgetFormInputText(),
      'sstock_com' => new sfWidgetFormInputText(),
      'stock_lle'  => new sfWidgetFormInputText(),
      'sstock_lle' => new sfWidgetFormInputText(),
      'stock_des'  => new sfWidgetFormInputText(),
      'sstock_des' => new sfWidgetFormInputText(),
      'suni_venta' => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Unidades_9'), 'add_empty' => false)),
      'suni_compr' => new sfWidgetFormInputText(),
      'suni_relac' => new sfWidgetFormInputText(),
      'sstock_act' => new sfWidgetFormInputText(),
      'relac_comp' => new sfWidgetFormInputText(),
      'relac_vent' => new sfWidgetFormInputText(),
      'pto_pedido' => new sfWidgetFormInputText(),
      'stock_max'  => new sfWidgetFormInputText(),
      'stock_min'  => new sfWidgetFormInputText(),
      'prec_om'    => new sfWidgetFormInputCheckbox(),
      'prec_vta1'  => new sfWidgetFormInputText(),
      'fec_prec_v' => new sfWidgetFormDateTime(),
      'fec_prec_2' => new sfWidgetFormDateTime(),
      'prec_vta2'  => new sfWidgetFormInputText(),
      'fec_prec_3' => new sfWidgetFormDateTime(),
      'prec_vta3'  => new sfWidgetFormInputText(),
      'fec_prec_4' => new sfWidgetFormDateTime(),
      'prec_vta4'  => new sfWidgetFormInputText(),
      'fec_prec_5' => new sfWidgetFormDateTime(),
      'prec_vta5'  => new sfWidgetFormInputText(),
      'prec_agr1'  => new sfWidgetFormInputText(),
      'prec_agr2'  => new sfWidgetFormInputText(),
      'prec_agr3'  => new sfWidgetFormInputText(),
      'prec_agr4'  => new sfWidgetFormInputText(),
      'prec_agr5'  => new sfWidgetFormInputText(),
      'can_agr'    => new sfWidgetFormInputText(),
      'fec_des_p5' => new sfWidgetFormDateTime(),
      'fec_has_p5' => new sfWidgetFormDateTime(),
      'co_imp'     => new sfWidgetFormInputText(),
      'margen_max' => new sfWidgetFormInputText(),
      'ult_cos_un' => new sfWidgetFormInputText(),
      'fec_ult_co' => new sfWidgetFormDateTime(),
      'cos_pro_un' => new sfWidgetFormInputText(),
      'fec_cos_pr' => new sfWidgetFormDateTime(),
      'cos_merc'   => new sfWidgetFormInputText(),
      'fec_cos_me' => new sfWidgetFormDateTime(),
      'cos_prov'   => new sfWidgetFormInputText(),
      'fec_cos_p2' => new sfWidgetFormDateTime(),
      'ult_cos_do' => new sfWidgetFormInputText(),
      'fec_cos_do' => new sfWidgetFormDateTime(),
      'cos_un_an'  => new sfWidgetFormInputText(),
      'fec_cos_an' => new sfWidgetFormDateTime(),
      'ult_cos_om' => new sfWidgetFormInputText(),
      'fec_ult_om' => new sfWidgetFormDateTime(),
      'cos_pro_om' => new sfWidgetFormInputText(),
      'fec_pro_om' => new sfWidgetFormDateTime(),
      'tipo_cos'   => new sfWidgetFormInputText(),
      'mont_comi'  => new sfWidgetFormInputText(),
      'porc_cos'   => new sfWidgetFormInputText(),
      'mont_cos'   => new sfWidgetFormInputText(),
      'porc_gas'   => new sfWidgetFormInputText(),
      'mont_gas'   => new sfWidgetFormInputText(),
      'f_cost'     => new sfWidgetFormDateTime(),
      'fisico'     => new sfWidgetFormInputCheckbox(),
      'punt_cli'   => new sfWidgetFormInputText(),
      'punt_pro'   => new sfWidgetFormInputText(),
      'dias_repos' => new sfWidgetFormInputText(),
      'tipo'       => new sfWidgetFormInputText(),
      'alm_prin'   => new sfWidgetFormInputText(),
      'anulado'    => new sfWidgetFormInputCheckbox(),
      'tipo_imp'   => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Tabulado'), 'add_empty' => false)),
      'dis_cen'    => new sfWidgetFormTextarea(),
      'mon_ilc'    => new sfWidgetFormInputText(),
      'capacidad'  => new sfWidgetFormInputText(),
      'grado_al'   => new sfWidgetFormInputText(),
      'tipo_licor' => new sfWidgetFormInputText(),
      'compuesto'  => new sfWidgetFormInputCheckbox(),
      'picture'    => new sfWidgetFormTextarea(),
      'campo1'     => new sfWidgetFormInputText(),
      'campo2'     => new sfWidgetFormInputText(),
      'campo3'     => new sfWidgetFormInputText(),
      'campo4'     => new sfWidgetFormInputText(),
      'campo5'     => new sfWidgetFormInputText(),
      'campo6'     => new sfWidgetFormInputText(),
      'campo7'     => new sfWidgetFormInputText(),
      'campo8'     => new sfWidgetFormInputText(),
      'co_us_in'   => new sfWidgetFormInputText(),
      'fe_us_in'   => new sfWidgetFormDateTime(),
      'co_us_mo'   => new sfWidgetFormInputText(),
      'fe_us_mo'   => new sfWidgetFormDateTime(),
      'co_us_el'   => new sfWidgetFormInputText(),
      'fe_us_el'   => new sfWidgetFormDateTime(),
      'revisado'   => new sfWidgetFormInputText(),
      'trasnfe'    => new sfWidgetFormInputText(),
      'co_sucu'    => new sfWidgetFormInputText(),
      'rowguid'    => new sfWidgetFormInputText(),
      'tuni_venta' => new sfWidgetFormInputText(),
      'equi_uni1'  => new sfWidgetFormInputText(),
      'equi_uni2'  => new sfWidgetFormInputText(),
      'equi_uni3'  => new sfWidgetFormInputText(),
      'lote'       => new sfWidgetFormInputCheckbox(),
      'serialp'    => new sfWidgetFormInputText(),
      'valido'     => new sfWidgetFormInputCheckbox(),
      'atributo1'  => new sfWidgetFormInputCheckbox(),
      'vatributo1' => new sfWidgetFormInputText(),
      'atributo2'  => new sfWidgetFormInputCheckbox(),
      'vatributo2' => new sfWidgetFormInputText(),
      'atributo3'  => new sfWidgetFormInputCheckbox(),
      'vatributo3' => new sfWidgetFormInputText(),
      'atributo4'  => new sfWidgetFormInputCheckbox(),
      'vatributo4' => new sfWidgetFormInputText(),
      'atributo5'  => new sfWidgetFormInputCheckbox(),
      'vatributo5' => new sfWidgetFormInputText(),
      'atributo6'  => new sfWidgetFormInputCheckbox(),
      'vatributo6' => new sfWidgetFormInputText(),
      'garantia'   => new sfWidgetFormInputText(),
      'peso'       => new sfWidgetFormInputText(),
      'pie'        => new sfWidgetFormInputText(),
      'margen1'    => new sfWidgetFormInputText(),
      'margen2'    => new sfWidgetFormInputText(),
      'margen3'    => new sfWidgetFormInputText(),
      'margen4'    => new sfWidgetFormInputText(),
      'margen5'    => new sfWidgetFormInputText(),
      'row_id'     => new sfWidgetFormDateTime(),
      'imagen1'    => new sfWidgetFormInputText(),
      'imagen2'    => new sfWidgetFormInputText(),
      'i_art_des'  => new sfWidgetFormInputText(),
      'uni_emp'    => new sfWidgetFormInputText(),
      'rel_emp'    => new sfWidgetFormInputText(),
      'movil'      => new sfWidgetFormInputCheckbox(),
    ));

    $this->setValidators(array(
      'co_art'     => new sfValidatorChoice(array('choices' => array($this->getObject()->get('co_art')), 'empty_value' => $this->getObject()->get('co_art'), 'required' => false)),
      'art_des'    => new sfValidatorString(array('max_length' => 120, 'required' => false)),
      'fecha_reg'  => new sfValidatorDateTime(array('required' => false)),
      'manj_ser'   => new sfValidatorBoolean(array('required' => false)),
      'co_lin'     => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('LinArt'), 'required' => false)),
      'co_cat'     => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('CatArt'), 'required' => false)),
      'co_subl'    => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('SubLin_4'), 'required' => false)),
      'co_color'   => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Colores'), 'required' => false)),
      'item'       => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'ref'        => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'modelo'     => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'procedenci' => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Proceden'), 'required' => false)),
      'comentario' => new sfValidatorString(array('max_length' => 2147483647, 'required' => false)),
      'co_prov'    => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Prov'), 'required' => false)),
      'ubicacion'  => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'uni_venta'  => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Unidades'), 'required' => false)),
      'uni_compra' => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'uni_relac'  => new sfValidatorNumber(array('required' => false)),
      'relac_aut'  => new sfValidatorInteger(array('required' => false)),
      'stock_act'  => new sfValidatorNumber(array('required' => false)),
      'stock_com'  => new sfValidatorNumber(array('required' => false)),
      'sstock_com' => new sfValidatorNumber(array('required' => false)),
      'stock_lle'  => new sfValidatorNumber(array('required' => false)),
      'sstock_lle' => new sfValidatorNumber(array('required' => false)),
      'stock_des'  => new sfValidatorNumber(array('required' => false)),
      'sstock_des' => new sfValidatorNumber(array('required' => false)),
      'suni_venta' => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Unidades_9'), 'required' => false)),
      'suni_compr' => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'suni_relac' => new sfValidatorNumber(array('required' => false)),
      'sstock_act' => new sfValidatorNumber(array('required' => false)),
      'relac_comp' => new sfValidatorNumber(array('required' => false)),
      'relac_vent' => new sfValidatorNumber(array('required' => false)),
      'pto_pedido' => new sfValidatorNumber(array('required' => false)),
      'stock_max'  => new sfValidatorNumber(array('required' => false)),
      'stock_min'  => new sfValidatorNumber(array('required' => false)),
      'prec_om'    => new sfValidatorBoolean(array('required' => false)),
      'prec_vta1'  => new sfValidatorNumber(array('required' => false)),
      'fec_prec_v' => new sfValidatorDateTime(array('required' => false)),
      'fec_prec_2' => new sfValidatorDateTime(array('required' => false)),
      'prec_vta2'  => new sfValidatorNumber(array('required' => false)),
      'fec_prec_3' => new sfValidatorDateTime(array('required' => false)),
      'prec_vta3'  => new sfValidatorNumber(array('required' => false)),
      'fec_prec_4' => new sfValidatorDateTime(array('required' => false)),
      'prec_vta4'  => new sfValidatorNumber(array('required' => false)),
      'fec_prec_5' => new sfValidatorDateTime(array('required' => false)),
      'prec_vta5'  => new sfValidatorNumber(array('required' => false)),
      'prec_agr1'  => new sfValidatorNumber(array('required' => false)),
      'prec_agr2'  => new sfValidatorNumber(array('required' => false)),
      'prec_agr3'  => new sfValidatorNumber(array('required' => false)),
      'prec_agr4'  => new sfValidatorNumber(array('required' => false)),
      'prec_agr5'  => new sfValidatorNumber(array('required' => false)),
      'can_agr'    => new sfValidatorNumber(array('required' => false)),
      'fec_des_p5' => new sfValidatorDateTime(array('required' => false)),
      'fec_has_p5' => new sfValidatorDateTime(array('required' => false)),
      'co_imp'     => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'margen_max' => new sfValidatorNumber(array('required' => false)),
      'ult_cos_un' => new sfValidatorNumber(array('required' => false)),
      'fec_ult_co' => new sfValidatorDateTime(array('required' => false)),
      'cos_pro_un' => new sfValidatorNumber(array('required' => false)),
      'fec_cos_pr' => new sfValidatorDateTime(array('required' => false)),
      'cos_merc'   => new sfValidatorNumber(array('required' => false)),
      'fec_cos_me' => new sfValidatorDateTime(array('required' => false)),
      'cos_prov'   => new sfValidatorNumber(array('required' => false)),
      'fec_cos_p2' => new sfValidatorDateTime(array('required' => false)),
      'ult_cos_do' => new sfValidatorNumber(array('required' => false)),
      'fec_cos_do' => new sfValidatorDateTime(array('required' => false)),
      'cos_un_an'  => new sfValidatorNumber(array('required' => false)),
      'fec_cos_an' => new sfValidatorDateTime(array('required' => false)),
      'ult_cos_om' => new sfValidatorNumber(array('required' => false)),
      'fec_ult_om' => new sfValidatorDateTime(array('required' => false)),
      'cos_pro_om' => new sfValidatorNumber(array('required' => false)),
      'fec_pro_om' => new sfValidatorDateTime(array('required' => false)),
      'tipo_cos'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'mont_comi'  => new sfValidatorNumber(array('required' => false)),
      'porc_cos'   => new sfValidatorNumber(array('required' => false)),
      'mont_cos'   => new sfValidatorNumber(array('required' => false)),
      'porc_gas'   => new sfValidatorNumber(array('required' => false)),
      'mont_gas'   => new sfValidatorNumber(array('required' => false)),
      'f_cost'     => new sfValidatorDateTime(array('required' => false)),
      'fisico'     => new sfValidatorBoolean(array('required' => false)),
      'punt_cli'   => new sfValidatorNumber(array('required' => false)),
      'punt_pro'   => new sfValidatorNumber(array('required' => false)),
      'dias_repos' => new sfValidatorInteger(array('required' => false)),
      'tipo'       => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'alm_prin'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'anulado'    => new sfValidatorBoolean(array('required' => false)),
      'tipo_imp'   => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Tabulado'), 'required' => false)),
      'dis_cen'    => new sfValidatorString(array('max_length' => 2147483647, 'required' => false)),
      'mon_ilc'    => new sfValidatorNumber(array('required' => false)),
      'capacidad'  => new sfValidatorNumber(array('required' => false)),
      'grado_al'   => new sfValidatorNumber(array('required' => false)),
      'tipo_licor' => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'compuesto'  => new sfValidatorBoolean(array('required' => false)),
      'picture'    => new sfValidatorString(array('required' => false)),
      'campo1'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo2'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo3'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo4'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo5'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo6'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo7'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'campo8'     => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'co_us_in'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_in'   => new sfValidatorDateTime(array('required' => false)),
      'co_us_mo'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_mo'   => new sfValidatorDateTime(array('required' => false)),
      'co_us_el'   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fe_us_el'   => new sfValidatorDateTime(array('required' => false)),
      'revisado'   => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'trasnfe'    => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'co_sucu'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'rowguid'    => new sfValidatorString(array('max_length' => 36, 'required' => false)),
      'tuni_venta' => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'equi_uni1'  => new sfValidatorNumber(array('required' => false)),
      'equi_uni2'  => new sfValidatorNumber(array('required' => false)),
      'equi_uni3'  => new sfValidatorNumber(array('required' => false)),
      'lote'       => new sfValidatorBoolean(array('required' => false)),
      'serialp'    => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'valido'     => new sfValidatorBoolean(array('required' => false)),
      'atributo1'  => new sfValidatorBoolean(array('required' => false)),
      'vatributo1' => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'atributo2'  => new sfValidatorBoolean(array('required' => false)),
      'vatributo2' => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'atributo3'  => new sfValidatorBoolean(array('required' => false)),
      'vatributo3' => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'atributo4'  => new sfValidatorBoolean(array('required' => false)),
      'vatributo4' => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'atributo5'  => new sfValidatorBoolean(array('required' => false)),
      'vatributo5' => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'atributo6'  => new sfValidatorBoolean(array('required' => false)),
      'vatributo6' => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'garantia'   => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'peso'       => new sfValidatorNumber(array('required' => false)),
      'pie'        => new sfValidatorNumber(array('required' => false)),
      'margen1'    => new sfValidatorNumber(array('required' => false)),
      'margen2'    => new sfValidatorNumber(array('required' => false)),
      'margen3'    => new sfValidatorNumber(array('required' => false)),
      'margen4'    => new sfValidatorNumber(array('required' => false)),
      'margen5'    => new sfValidatorNumber(array('required' => false)),
      'row_id'     => new sfValidatorDateTime(),
      'imagen1'    => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'imagen2'    => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'i_art_des'  => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'uni_emp'    => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'rel_emp'    => new sfValidatorNumber(array('required' => false)),
      'movil'      => new sfValidatorBoolean(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('art[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Art';
  }

}
